// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My007171Component } from './my.007171.component';
import { My007172Component } from './my.007172.component';
import { My007173Component } from './my.007173.component';
import { My007174Component } from './my.007174.component';
import { My007175Component } from './my.007175.component';
import { My007176Component } from './my.007176.component';
import { My007177Component } from './my.007177.component';
import { My007178Component } from './my.007178.component';
import { My007179Component } from './my.007179.component';
import { My007180Component } from './my.007180.component';
import { My007181Component } from './my.007181.component';
import { My007182Component } from './my.007182.component';
import { My007183Component } from './my.007183.component';
import { My007184Component } from './my.007184.component';
import { My007185Component } from './my.007185.component';
import { My007186Component } from './my.007186.component';
import { My007187Component } from './my.007187.component';
import { My007188Component } from './my.007188.component';
import { My007189Component } from './my.007189.component';
import { My007190Component } from './my.007190.component';
import { My007191Component } from './my.007191.component';
import { My007192Component } from './my.007192.component';
import { My007193Component } from './my.007193.component';
import { My007194Component } from './my.007194.component';
import { My007195Component } from './my.007195.component';
import { My007196Component } from './my.007196.component';
import { My007197Component } from './my.007197.component';
import { My007198Component } from './my.007198.component';
import { My007199Component } from './my.007199.component';
import { My007200Component } from './my.007200.component';
import { My007201Component } from './my.007201.component';
import { My007202Component } from './my.007202.component';
import { My007203Component } from './my.007203.component';
import { My007204Component } from './my.007204.component';
import { My007205Component } from './my.007205.component';
import { My007206Component } from './my.007206.component';
import { My007207Component } from './my.007207.component';
import { My007208Component } from './my.007208.component';
import { My007209Component } from './my.007209.component';
import { My007210Component } from './my.007210.component';
import { My007211Component } from './my.007211.component';
import { My007212Component } from './my.007212.component';
import { My007213Component } from './my.007213.component';
import { My007214Component } from './my.007214.component';
import { My007215Component } from './my.007215.component';
import { My007216Component } from './my.007216.component';
import { My007217Component } from './my.007217.component';
import { My007218Component } from './my.007218.component';
import { My007219Component } from './my.007219.component';
import { My007220Component } from './my.007220.component';
import { My007221Component } from './my.007221.component';
import { My007222Component } from './my.007222.component';
import { My007223Component } from './my.007223.component';
import { My007224Component } from './my.007224.component';
import { My007225Component } from './my.007225.component';
import { My007226Component } from './my.007226.component';
import { My007227Component } from './my.007227.component';
import { My007228Component } from './my.007228.component';
import { My007229Component } from './my.007229.component';
import { My007230Component } from './my.007230.component';
import { My007231Component } from './my.007231.component';
import { My007232Component } from './my.007232.component';
import { My007233Component } from './my.007233.component';
import { My007234Component } from './my.007234.component';
import { My007235Component } from './my.007235.component';
import { My007236Component } from './my.007236.component';
import { My007237Component } from './my.007237.component';
import { My007238Component } from './my.007238.component';
import { My007239Component } from './my.007239.component';
import { My007240Component } from './my.007240.component';
import { My007241Component } from './my.007241.component';
import { My007242Component } from './my.007242.component';
import { My007243Component } from './my.007243.component';
import { My007244Component } from './my.007244.component';
import { My007245Component } from './my.007245.component';
import { My007246Component } from './my.007246.component';
import { My007247Component } from './my.007247.component';
import { My007248Component } from './my.007248.component';
import { My007249Component } from './my.007249.component';
import { My007250Component } from './my.007250.component';
import { My007251Component } from './my.007251.component';
import { My007252Component } from './my.007252.component';
import { My007253Component } from './my.007253.component';
import { My007254Component } from './my.007254.component';
import { My007255Component } from './my.007255.component';
import { My007256Component } from './my.007256.component';
import { My007257Component } from './my.007257.component';
import { My007258Component } from './my.007258.component';
import { My007259Component } from './my.007259.component';
import { My007260Component } from './my.007260.component';
import { My007261Component } from './my.007261.component';
import { My007262Component } from './my.007262.component';
import { My007263Component } from './my.007263.component';
import { My007264Component } from './my.007264.component';
import { My007265Component } from './my.007265.component';
import { My007266Component } from './my.007266.component';
import { My007267Component } from './my.007267.component';
import { My007268Component } from './my.007268.component';
import { My007269Component } from './my.007269.component';
import { My007270Component } from './my.007270.component';
import { My007271Component } from './my.007271.component';

@NgModule({
  declarations: [
    My007171Component,
    My007172Component,
    My007173Component,
    My007174Component,
    My007175Component,
    My007176Component,
    My007177Component,
    My007178Component,
    My007179Component,
    My007180Component,
    My007181Component,
    My007182Component,
    My007183Component,
    My007184Component,
    My007185Component,
    My007186Component,
    My007187Component,
    My007188Component,
    My007189Component,
    My007190Component,
    My007191Component,
    My007192Component,
    My007193Component,
    My007194Component,
    My007195Component,
    My007196Component,
    My007197Component,
    My007198Component,
    My007199Component,
    My007200Component,
    My007201Component,
    My007202Component,
    My007203Component,
    My007204Component,
    My007205Component,
    My007206Component,
    My007207Component,
    My007208Component,
    My007209Component,
    My007210Component,
    My007211Component,
    My007212Component,
    My007213Component,
    My007214Component,
    My007215Component,
    My007216Component,
    My007217Component,
    My007218Component,
    My007219Component,
    My007220Component,
    My007221Component,
    My007222Component,
    My007223Component,
    My007224Component,
    My007225Component,
    My007226Component,
    My007227Component,
    My007228Component,
    My007229Component,
    My007230Component,
    My007231Component,
    My007232Component,
    My007233Component,
    My007234Component,
    My007235Component,
    My007236Component,
    My007237Component,
    My007238Component,
    My007239Component,
    My007240Component,
    My007241Component,
    My007242Component,
    My007243Component,
    My007244Component,
    My007245Component,
    My007246Component,
    My007247Component,
    My007248Component,
    My007249Component,
    My007250Component,
    My007251Component,
    My007252Component,
    My007253Component,
    My007254Component,
    My007255Component,
    My007256Component,
    My007257Component,
    My007258Component,
    My007259Component,
    My007260Component,
    My007261Component,
    My007262Component,
    My007263Component,
    My007264Component,
    My007265Component,
    My007266Component,
    My007267Component,
    My007268Component,
    My007269Component,
    My007270Component,
    My007271Component,
  ],
  imports: [CommonModule],
  exports: [
    My007171Component,
  ]
})
export class Module000071 { }
