// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007237',
  templateUrl: './my.007237.component.html'
})
export class My007237Component {
  @Input() parentName = '';
  myName = 'My007237Component';
}
