// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007180',
  templateUrl: './my.007180.component.html'
})
export class My007180Component {
  @Input() parentName = '';
  myName = 'My007180Component';
}
