// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007253',
  templateUrl: './my.007253.component.html'
})
export class My007253Component {
  @Input() parentName = '';
  myName = 'My007253Component';
}
