// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007184',
  templateUrl: './my.007184.component.html'
})
export class My007184Component {
  @Input() parentName = '';
  myName = 'My007184Component';
}
