// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007210',
  templateUrl: './my.007210.component.html'
})
export class My007210Component {
  @Input() parentName = '';
  myName = 'My007210Component';
}
