// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007243',
  templateUrl: './my.007243.component.html'
})
export class My007243Component {
  @Input() parentName = '';
  myName = 'My007243Component';
}
