// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007174',
  templateUrl: './my.007174.component.html'
})
export class My007174Component {
  @Input() parentName = '';
  myName = 'My007174Component';
}
