// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007207',
  templateUrl: './my.007207.component.html'
})
export class My007207Component {
  @Input() parentName = '';
  myName = 'My007207Component';
}
