// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007246',
  templateUrl: './my.007246.component.html'
})
export class My007246Component {
  @Input() parentName = '';
  myName = 'My007246Component';
}
