// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007222',
  templateUrl: './my.007222.component.html'
})
export class My007222Component {
  @Input() parentName = '';
  myName = 'My007222Component';
}
