// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007270',
  templateUrl: './my.007270.component.html'
})
export class My007270Component {
  @Input() parentName = '';
  myName = 'My007270Component';
}
