// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007193',
  templateUrl: './my.007193.component.html'
})
export class My007193Component {
  @Input() parentName = '';
  myName = 'My007193Component';
}
