// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007235',
  templateUrl: './my.007235.component.html'
})
export class My007235Component {
  @Input() parentName = '';
  myName = 'My007235Component';
}
