// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007254',
  templateUrl: './my.007254.component.html'
})
export class My007254Component {
  @Input() parentName = '';
  myName = 'My007254Component';
}
