// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007256',
  templateUrl: './my.007256.component.html'
})
export class My007256Component {
  @Input() parentName = '';
  myName = 'My007256Component';
}
