// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007188',
  templateUrl: './my.007188.component.html'
})
export class My007188Component {
  @Input() parentName = '';
  myName = 'My007188Component';
}
