// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007186',
  templateUrl: './my.007186.component.html'
})
export class My007186Component {
  @Input() parentName = '';
  myName = 'My007186Component';
}
