// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007259',
  templateUrl: './my.007259.component.html'
})
export class My007259Component {
  @Input() parentName = '';
  myName = 'My007259Component';
}
