// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007578',
  templateUrl: './my.007578.component.html'
})
export class My007578Component {
  @Input() parentName = '';
  myName = 'My007578Component';
}
