// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007617',
  templateUrl: './my.007617.component.html'
})
export class My007617Component {
  @Input() parentName = '';
  myName = 'My007617Component';
}
