// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007613',
  templateUrl: './my.007613.component.html'
})
export class My007613Component {
  @Input() parentName = '';
  myName = 'My007613Component';
}
