// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007581',
  templateUrl: './my.007581.component.html'
})
export class My007581Component {
  @Input() parentName = '';
  myName = 'My007581Component';
}
