// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007646',
  templateUrl: './my.007646.component.html'
})
export class My007646Component {
  @Input() parentName = '';
  myName = 'My007646Component';
}
