// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007623',
  templateUrl: './my.007623.component.html'
})
export class My007623Component {
  @Input() parentName = '';
  myName = 'My007623Component';
}
