// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007648',
  templateUrl: './my.007648.component.html'
})
export class My007648Component {
  @Input() parentName = '';
  myName = 'My007648Component';
}
