// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007596',
  templateUrl: './my.007596.component.html'
})
export class My007596Component {
  @Input() parentName = '';
  myName = 'My007596Component';
}
