// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007611',
  templateUrl: './my.007611.component.html'
})
export class My007611Component {
  @Input() parentName = '';
  myName = 'My007611Component';
}
