// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007600',
  templateUrl: './my.007600.component.html'
})
export class My007600Component {
  @Input() parentName = '';
  myName = 'My007600Component';
}
