// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007658',
  templateUrl: './my.007658.component.html'
})
export class My007658Component {
  @Input() parentName = '';
  myName = 'My007658Component';
}
