// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007645',
  templateUrl: './my.007645.component.html'
})
export class My007645Component {
  @Input() parentName = '';
  myName = 'My007645Component';
}
