// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007579',
  templateUrl: './my.007579.component.html'
})
export class My007579Component {
  @Input() parentName = '';
  myName = 'My007579Component';
}
