// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007628',
  templateUrl: './my.007628.component.html'
})
export class My007628Component {
  @Input() parentName = '';
  myName = 'My007628Component';
}
