// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007653',
  templateUrl: './my.007653.component.html'
})
export class My007653Component {
  @Input() parentName = '';
  myName = 'My007653Component';
}
