// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007630',
  templateUrl: './my.007630.component.html'
})
export class My007630Component {
  @Input() parentName = '';
  myName = 'My007630Component';
}
