// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007594',
  templateUrl: './my.007594.component.html'
})
export class My007594Component {
  @Input() parentName = '';
  myName = 'My007594Component';
}
