// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007632',
  templateUrl: './my.007632.component.html'
})
export class My007632Component {
  @Input() parentName = '';
  myName = 'My007632Component';
}
