// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006783',
  templateUrl: './my.006783.component.html'
})
export class My006783Component {
  @Input() parentName = '';
  myName = 'My006783Component';
}
