// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006812',
  templateUrl: './my.006812.component.html'
})
export class My006812Component {
  @Input() parentName = '';
  myName = 'My006812Component';
}
