// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006796',
  templateUrl: './my.006796.component.html'
})
export class My006796Component {
  @Input() parentName = '';
  myName = 'My006796Component';
}
