// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006822',
  templateUrl: './my.006822.component.html'
})
export class My006822Component {
  @Input() parentName = '';
  myName = 'My006822Component';
}
