// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006860',
  templateUrl: './my.006860.component.html'
})
export class My006860Component {
  @Input() parentName = '';
  myName = 'My006860Component';
}
