// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006768',
  templateUrl: './my.006768.component.html'
})
export class My006768Component {
  @Input() parentName = '';
  myName = 'My006768Component';
}
