// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006862',
  templateUrl: './my.006862.component.html'
})
export class My006862Component {
  @Input() parentName = '';
  myName = 'My006862Component';
}
