// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006837',
  templateUrl: './my.006837.component.html'
})
export class My006837Component {
  @Input() parentName = '';
  myName = 'My006837Component';
}
