// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006799',
  templateUrl: './my.006799.component.html'
})
export class My006799Component {
  @Input() parentName = '';
  myName = 'My006799Component';
}
