// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006863',
  templateUrl: './my.006863.component.html'
})
export class My006863Component {
  @Input() parentName = '';
  myName = 'My006863Component';
}
