// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006767',
  templateUrl: './my.006767.component.html'
})
export class My006767Component {
  @Input() parentName = '';
  myName = 'My006767Component';
}
