// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006814',
  templateUrl: './my.006814.component.html'
})
export class My006814Component {
  @Input() parentName = '';
  myName = 'My006814Component';
}
