// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006826',
  templateUrl: './my.006826.component.html'
})
export class My006826Component {
  @Input() parentName = '';
  myName = 'My006826Component';
}
