// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006802',
  templateUrl: './my.006802.component.html'
})
export class My006802Component {
  @Input() parentName = '';
  myName = 'My006802Component';
}
