// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000439Component } from './my.000439.component';
import { My000440Component } from './my.000440.component';
import { My000441Component } from './my.000441.component';
import { My000442Component } from './my.000442.component';
import { My000443Component } from './my.000443.component';
import { My000444Component } from './my.000444.component';
import { My000445Component } from './my.000445.component';
import { My000446Component } from './my.000446.component';
import { My000447Component } from './my.000447.component';
import { My000448Component } from './my.000448.component';
import { My000449Component } from './my.000449.component';
import { My000450Component } from './my.000450.component';
import { My000451Component } from './my.000451.component';
import { My000452Component } from './my.000452.component';
import { My000453Component } from './my.000453.component';
import { My000454Component } from './my.000454.component';
import { My000455Component } from './my.000455.component';
import { My000456Component } from './my.000456.component';
import { My000457Component } from './my.000457.component';
import { My000458Component } from './my.000458.component';

@NgModule({
  declarations: [
    My000439Component,
    My000440Component,
    My000441Component,
    My000442Component,
    My000443Component,
    My000444Component,
    My000445Component,
    My000446Component,
    My000447Component,
    My000448Component,
    My000449Component,
    My000450Component,
    My000451Component,
    My000452Component,
    My000453Component,
    My000454Component,
    My000455Component,
    My000456Component,
    My000457Component,
    My000458Component,
  ],
  imports: [CommonModule],
  exports: [
    My000439Component,
  ]
})
export class Module000021 { }
