// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002171',
  templateUrl: './my.002171.component.html'
})
export class My002171Component {
  @Input() parentName = '';
  myName = 'My002171Component';
}
