// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002159',
  templateUrl: './my.002159.component.html'
})
export class My002159Component {
  @Input() parentName = '';
  myName = 'My002159Component';
}
