// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002196',
  templateUrl: './my.002196.component.html'
})
export class My002196Component {
  @Input() parentName = '';
  myName = 'My002196Component';
}
