// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002180',
  templateUrl: './my.002180.component.html'
})
export class My002180Component {
  @Input() parentName = '';
  myName = 'My002180Component';
}
