// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002220',
  templateUrl: './my.002220.component.html'
})
export class My002220Component {
  @Input() parentName = '';
  myName = 'My002220Component';
}
