// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002213',
  templateUrl: './my.002213.component.html'
})
export class My002213Component {
  @Input() parentName = '';
  myName = 'My002213Component';
}
