// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002166',
  templateUrl: './my.002166.component.html'
})
export class My002166Component {
  @Input() parentName = '';
  myName = 'My002166Component';
}
