// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002146',
  templateUrl: './my.002146.component.html'
})
export class My002146Component {
  @Input() parentName = '';
  myName = 'My002146Component';
}
