// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002190',
  templateUrl: './my.002190.component.html'
})
export class My002190Component {
  @Input() parentName = '';
  myName = 'My002190Component';
}
