// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002127',
  templateUrl: './my.002127.component.html'
})
export class My002127Component {
  @Input() parentName = '';
  myName = 'My002127Component';
}
