// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002219',
  templateUrl: './my.002219.component.html'
})
export class My002219Component {
  @Input() parentName = '';
  myName = 'My002219Component';
}
