// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002192',
  templateUrl: './my.002192.component.html'
})
export class My002192Component {
  @Input() parentName = '';
  myName = 'My002192Component';
}
