// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002178',
  templateUrl: './my.002178.component.html'
})
export class My002178Component {
  @Input() parentName = '';
  myName = 'My002178Component';
}
