// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002138',
  templateUrl: './my.002138.component.html'
})
export class My002138Component {
  @Input() parentName = '';
  myName = 'My002138Component';
}
