// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002143',
  templateUrl: './my.002143.component.html'
})
export class My002143Component {
  @Input() parentName = '';
  myName = 'My002143Component';
}
