// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002136',
  templateUrl: './my.002136.component.html'
})
export class My002136Component {
  @Input() parentName = '';
  myName = 'My002136Component';
}
