// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002205',
  templateUrl: './my.002205.component.html'
})
export class My002205Component {
  @Input() parentName = '';
  myName = 'My002205Component';
}
