// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002209',
  templateUrl: './my.002209.component.html'
})
export class My002209Component {
  @Input() parentName = '';
  myName = 'My002209Component';
}
