// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002164',
  templateUrl: './my.002164.component.html'
})
export class My002164Component {
  @Input() parentName = '';
  myName = 'My002164Component';
}
