// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002195',
  templateUrl: './my.002195.component.html'
})
export class My002195Component {
  @Input() parentName = '';
  myName = 'My002195Component';
}
