// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007052',
  templateUrl: './my.007052.component.html'
})
export class My007052Component {
  @Input() parentName = '';
  myName = 'My007052Component';
}
