// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007064',
  templateUrl: './my.007064.component.html'
})
export class My007064Component {
  @Input() parentName = '';
  myName = 'My007064Component';
}
