// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007009',
  templateUrl: './my.007009.component.html'
})
export class My007009Component {
  @Input() parentName = '';
  myName = 'My007009Component';
}
