// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007013',
  templateUrl: './my.007013.component.html'
})
export class My007013Component {
  @Input() parentName = '';
  myName = 'My007013Component';
}
