// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007034',
  templateUrl: './my.007034.component.html'
})
export class My007034Component {
  @Input() parentName = '';
  myName = 'My007034Component';
}
