// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007015',
  templateUrl: './my.007015.component.html'
})
export class My007015Component {
  @Input() parentName = '';
  myName = 'My007015Component';
}
