// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007017',
  templateUrl: './my.007017.component.html'
})
export class My007017Component {
  @Input() parentName = '';
  myName = 'My007017Component';
}
