// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006991',
  templateUrl: './my.006991.component.html'
})
export class My006991Component {
  @Input() parentName = '';
  myName = 'My006991Component';
}
