// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007053',
  templateUrl: './my.007053.component.html'
})
export class My007053Component {
  @Input() parentName = '';
  myName = 'My007053Component';
}
