// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007031',
  templateUrl: './my.007031.component.html'
})
export class My007031Component {
  @Input() parentName = '';
  myName = 'My007031Component';
}
