// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007044',
  templateUrl: './my.007044.component.html'
})
export class My007044Component {
  @Input() parentName = '';
  myName = 'My007044Component';
}
