// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007005',
  templateUrl: './my.007005.component.html'
})
export class My007005Component {
  @Input() parentName = '';
  myName = 'My007005Component';
}
