// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007043',
  templateUrl: './my.007043.component.html'
})
export class My007043Component {
  @Input() parentName = '';
  myName = 'My007043Component';
}
