// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007000',
  templateUrl: './my.007000.component.html'
})
export class My007000Component {
  @Input() parentName = '';
  myName = 'My007000Component';
}
