// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006969',
  templateUrl: './my.006969.component.html'
})
export class My006969Component {
  @Input() parentName = '';
  myName = 'My006969Component';
}
