// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007473',
  templateUrl: './my.007473.component.html'
})
export class My007473Component {
  @Input() parentName = '';
  myName = 'My007473Component';
}
