// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007440',
  templateUrl: './my.007440.component.html'
})
export class My007440Component {
  @Input() parentName = '';
  myName = 'My007440Component';
}
