// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007396',
  templateUrl: './my.007396.component.html'
})
export class My007396Component {
  @Input() parentName = '';
  myName = 'My007396Component';
}
