// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007450',
  templateUrl: './my.007450.component.html'
})
export class My007450Component {
  @Input() parentName = '';
  myName = 'My007450Component';
}
