// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007430',
  templateUrl: './my.007430.component.html'
})
export class My007430Component {
  @Input() parentName = '';
  myName = 'My007430Component';
}
