// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007412',
  templateUrl: './my.007412.component.html'
})
export class My007412Component {
  @Input() parentName = '';
  myName = 'My007412Component';
}
