// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007398',
  templateUrl: './my.007398.component.html'
})
export class My007398Component {
  @Input() parentName = '';
  myName = 'My007398Component';
}
