// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007431',
  templateUrl: './my.007431.component.html'
})
export class My007431Component {
  @Input() parentName = '';
  myName = 'My007431Component';
}
