// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007419',
  templateUrl: './my.007419.component.html'
})
export class My007419Component {
  @Input() parentName = '';
  myName = 'My007419Component';
}
