// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007380',
  templateUrl: './my.007380.component.html'
})
export class My007380Component {
  @Input() parentName = '';
  myName = 'My007380Component';
}
