// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007373',
  templateUrl: './my.007373.component.html'
})
export class My007373Component {
  @Input() parentName = '';
  myName = 'My007373Component';
}
