// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007389',
  templateUrl: './my.007389.component.html'
})
export class My007389Component {
  @Input() parentName = '';
  myName = 'My007389Component';
}
