// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007417',
  templateUrl: './my.007417.component.html'
})
export class My007417Component {
  @Input() parentName = '';
  myName = 'My007417Component';
}
