// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007444',
  templateUrl: './my.007444.component.html'
})
export class My007444Component {
  @Input() parentName = '';
  myName = 'My007444Component';
}
