// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007404',
  templateUrl: './my.007404.component.html'
})
export class My007404Component {
  @Input() parentName = '';
  myName = 'My007404Component';
}
