// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007429',
  templateUrl: './my.007429.component.html'
})
export class My007429Component {
  @Input() parentName = '';
  myName = 'My007429Component';
}
