// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007460',
  templateUrl: './my.007460.component.html'
})
export class My007460Component {
  @Input() parentName = '';
  myName = 'My007460Component';
}
