// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007438',
  templateUrl: './my.007438.component.html'
})
export class My007438Component {
  @Input() parentName = '';
  myName = 'My007438Component';
}
