// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007413',
  templateUrl: './my.007413.component.html'
})
export class My007413Component {
  @Input() parentName = '';
  myName = 'My007413Component';
}
