// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007471',
  templateUrl: './my.007471.component.html'
})
export class My007471Component {
  @Input() parentName = '';
  myName = 'My007471Component';
}
