// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004630',
  templateUrl: './my.004630.component.html'
})
export class My004630Component {
  @Input() parentName = '';
  myName = 'My004630Component';
}
