// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004622',
  templateUrl: './my.004622.component.html'
})
export class My004622Component {
  @Input() parentName = '';
  myName = 'My004622Component';
}
