// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004621',
  templateUrl: './my.004621.component.html'
})
export class My004621Component {
  @Input() parentName = '';
  myName = 'My004621Component';
}
