// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004561',
  templateUrl: './my.004561.component.html'
})
export class My004561Component {
  @Input() parentName = '';
  myName = 'My004561Component';
}
