// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004637',
  templateUrl: './my.004637.component.html'
})
export class My004637Component {
  @Input() parentName = '';
  myName = 'My004637Component';
}
