// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004641',
  templateUrl: './my.004641.component.html'
})
export class My004641Component {
  @Input() parentName = '';
  myName = 'My004641Component';
}
