// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004586',
  templateUrl: './my.004586.component.html'
})
export class My004586Component {
  @Input() parentName = '';
  myName = 'My004586Component';
}
