// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004610',
  templateUrl: './my.004610.component.html'
})
export class My004610Component {
  @Input() parentName = '';
  myName = 'My004610Component';
}
