// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004580',
  templateUrl: './my.004580.component.html'
})
export class My004580Component {
  @Input() parentName = '';
  myName = 'My004580Component';
}
