// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004549',
  templateUrl: './my.004549.component.html'
})
export class My004549Component {
  @Input() parentName = '';
  myName = 'My004549Component';
}
