// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004573',
  templateUrl: './my.004573.component.html'
})
export class My004573Component {
  @Input() parentName = '';
  myName = 'My004573Component';
}
