// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004584',
  templateUrl: './my.004584.component.html'
})
export class My004584Component {
  @Input() parentName = '';
  myName = 'My004584Component';
}
