// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004611',
  templateUrl: './my.004611.component.html'
})
export class My004611Component {
  @Input() parentName = '';
  myName = 'My004611Component';
}
