// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004548',
  templateUrl: './my.004548.component.html'
})
export class My004548Component {
  @Input() parentName = '';
  myName = 'My004548Component';
}
