// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004618',
  templateUrl: './my.004618.component.html'
})
export class My004618Component {
  @Input() parentName = '';
  myName = 'My004618Component';
}
