// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004640',
  templateUrl: './my.004640.component.html'
})
export class My004640Component {
  @Input() parentName = '';
  myName = 'My004640Component';
}
