// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004148',
  templateUrl: './my.004148.component.html'
})
export class My004148Component {
  @Input() parentName = '';
  myName = 'My004148Component';
}
