// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004234',
  templateUrl: './my.004234.component.html'
})
export class My004234Component {
  @Input() parentName = '';
  myName = 'My004234Component';
}
