// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004216',
  templateUrl: './my.004216.component.html'
})
export class My004216Component {
  @Input() parentName = '';
  myName = 'My004216Component';
}
