// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004175',
  templateUrl: './my.004175.component.html'
})
export class My004175Component {
  @Input() parentName = '';
  myName = 'My004175Component';
}
