// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004178',
  templateUrl: './my.004178.component.html'
})
export class My004178Component {
  @Input() parentName = '';
  myName = 'My004178Component';
}
