// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004206',
  templateUrl: './my.004206.component.html'
})
export class My004206Component {
  @Input() parentName = '';
  myName = 'My004206Component';
}
