// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004146',
  templateUrl: './my.004146.component.html'
})
export class My004146Component {
  @Input() parentName = '';
  myName = 'My004146Component';
}
