// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004193',
  templateUrl: './my.004193.component.html'
})
export class My004193Component {
  @Input() parentName = '';
  myName = 'My004193Component';
}
