// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004220',
  templateUrl: './my.004220.component.html'
})
export class My004220Component {
  @Input() parentName = '';
  myName = 'My004220Component';
}
