// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004207',
  templateUrl: './my.004207.component.html'
})
export class My004207Component {
  @Input() parentName = '';
  myName = 'My004207Component';
}
