// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004239',
  templateUrl: './my.004239.component.html'
})
export class My004239Component {
  @Input() parentName = '';
  myName = 'My004239Component';
}
