// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004165',
  templateUrl: './my.004165.component.html'
})
export class My004165Component {
  @Input() parentName = '';
  myName = 'My004165Component';
}
