// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003023',
  templateUrl: './my.003023.component.html'
})
export class My003023Component {
  @Input() parentName = '';
  myName = 'My003023Component';
}
