// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003010',
  templateUrl: './my.003010.component.html'
})
export class My003010Component {
  @Input() parentName = '';
  myName = 'My003010Component';
}
