// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002954',
  templateUrl: './my.002954.component.html'
})
export class My002954Component {
  @Input() parentName = '';
  myName = 'My002954Component';
}
