// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003027',
  templateUrl: './my.003027.component.html'
})
export class My003027Component {
  @Input() parentName = '';
  myName = 'My003027Component';
}
