// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003011',
  templateUrl: './my.003011.component.html'
})
export class My003011Component {
  @Input() parentName = '';
  myName = 'My003011Component';
}
