// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002961',
  templateUrl: './my.002961.component.html'
})
export class My002961Component {
  @Input() parentName = '';
  myName = 'My002961Component';
}
