// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002983',
  templateUrl: './my.002983.component.html'
})
export class My002983Component {
  @Input() parentName = '';
  myName = 'My002983Component';
}
