// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002998',
  templateUrl: './my.002998.component.html'
})
export class My002998Component {
  @Input() parentName = '';
  myName = 'My002998Component';
}
