// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002936',
  templateUrl: './my.002936.component.html'
})
export class My002936Component {
  @Input() parentName = '';
  myName = 'My002936Component';
}
