// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002965',
  templateUrl: './my.002965.component.html'
})
export class My002965Component {
  @Input() parentName = '';
  myName = 'My002965Component';
}
