// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003016',
  templateUrl: './my.003016.component.html'
})
export class My003016Component {
  @Input() parentName = '';
  myName = 'My003016Component';
}
