// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003015',
  templateUrl: './my.003015.component.html'
})
export class My003015Component {
  @Input() parentName = '';
  myName = 'My003015Component';
}
