// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003021',
  templateUrl: './my.003021.component.html'
})
export class My003021Component {
  @Input() parentName = '';
  myName = 'My003021Component';
}
