// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003001',
  templateUrl: './my.003001.component.html'
})
export class My003001Component {
  @Input() parentName = '';
  myName = 'My003001Component';
}
