// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002976',
  templateUrl: './my.002976.component.html'
})
export class My002976Component {
  @Input() parentName = '';
  myName = 'My002976Component';
}
