// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002971',
  templateUrl: './my.002971.component.html'
})
export class My002971Component {
  @Input() parentName = '';
  myName = 'My002971Component';
}
