// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002952',
  templateUrl: './my.002952.component.html'
})
export class My002952Component {
  @Input() parentName = '';
  myName = 'My002952Component';
}
