// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002982',
  templateUrl: './my.002982.component.html'
})
export class My002982Component {
  @Input() parentName = '';
  myName = 'My002982Component';
}
