// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002986',
  templateUrl: './my.002986.component.html'
})
export class My002986Component {
  @Input() parentName = '';
  myName = 'My002986Component';
}
