// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002984',
  templateUrl: './my.002984.component.html'
})
export class My002984Component {
  @Input() parentName = '';
  myName = 'My002984Component';
}
