// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002934',
  templateUrl: './my.002934.component.html'
})
export class My002934Component {
  @Input() parentName = '';
  myName = 'My002934Component';
}
