// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002964',
  templateUrl: './my.002964.component.html'
})
export class My002964Component {
  @Input() parentName = '';
  myName = 'My002964Component';
}
