// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002990',
  templateUrl: './my.002990.component.html'
})
export class My002990Component {
  @Input() parentName = '';
  myName = 'My002990Component';
}
