// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003008',
  templateUrl: './my.003008.component.html'
})
export class My003008Component {
  @Input() parentName = '';
  myName = 'My003008Component';
}
