// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008556',
  templateUrl: './my.008556.component.html'
})
export class My008556Component {
  @Input() parentName = '';
  myName = 'My008556Component';
}
