// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008494',
  templateUrl: './my.008494.component.html'
})
export class My008494Component {
  @Input() parentName = '';
  myName = 'My008494Component';
}
