// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008528',
  templateUrl: './my.008528.component.html'
})
export class My008528Component {
  @Input() parentName = '';
  myName = 'My008528Component';
}
