// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008564',
  templateUrl: './my.008564.component.html'
})
export class My008564Component {
  @Input() parentName = '';
  myName = 'My008564Component';
}
