// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008561',
  templateUrl: './my.008561.component.html'
})
export class My008561Component {
  @Input() parentName = '';
  myName = 'My008561Component';
}
