// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008517',
  templateUrl: './my.008517.component.html'
})
export class My008517Component {
  @Input() parentName = '';
  myName = 'My008517Component';
}
