// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008534',
  templateUrl: './my.008534.component.html'
})
export class My008534Component {
  @Input() parentName = '';
  myName = 'My008534Component';
}
