// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008513',
  templateUrl: './my.008513.component.html'
})
export class My008513Component {
  @Input() parentName = '';
  myName = 'My008513Component';
}
