// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008560',
  templateUrl: './my.008560.component.html'
})
export class My008560Component {
  @Input() parentName = '';
  myName = 'My008560Component';
}
