// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008583',
  templateUrl: './my.008583.component.html'
})
export class My008583Component {
  @Input() parentName = '';
  myName = 'My008583Component';
}
