// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008546',
  templateUrl: './my.008546.component.html'
})
export class My008546Component {
  @Input() parentName = '';
  myName = 'My008546Component';
}
