// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008545',
  templateUrl: './my.008545.component.html'
})
export class My008545Component {
  @Input() parentName = '';
  myName = 'My008545Component';
}
