// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008584',
  templateUrl: './my.008584.component.html'
})
export class My008584Component {
  @Input() parentName = '';
  myName = 'My008584Component';
}
