// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006113',
  templateUrl: './my.006113.component.html'
})
export class My006113Component {
  @Input() parentName = '';
  myName = 'My006113Component';
}
