// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006082',
  templateUrl: './my.006082.component.html'
})
export class My006082Component {
  @Input() parentName = '';
  myName = 'My006082Component';
}
