// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006147',
  templateUrl: './my.006147.component.html'
})
export class My006147Component {
  @Input() parentName = '';
  myName = 'My006147Component';
}
