// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006131',
  templateUrl: './my.006131.component.html'
})
export class My006131Component {
  @Input() parentName = '';
  myName = 'My006131Component';
}
