// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006141',
  templateUrl: './my.006141.component.html'
})
export class My006141Component {
  @Input() parentName = '';
  myName = 'My006141Component';
}
