// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006091',
  templateUrl: './my.006091.component.html'
})
export class My006091Component {
  @Input() parentName = '';
  myName = 'My006091Component';
}
