// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006135',
  templateUrl: './my.006135.component.html'
})
export class My006135Component {
  @Input() parentName = '';
  myName = 'My006135Component';
}
