// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006099',
  templateUrl: './my.006099.component.html'
})
export class My006099Component {
  @Input() parentName = '';
  myName = 'My006099Component';
}
