// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006087',
  templateUrl: './my.006087.component.html'
})
export class My006087Component {
  @Input() parentName = '';
  myName = 'My006087Component';
}
