// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006150',
  templateUrl: './my.006150.component.html'
})
export class My006150Component {
  @Input() parentName = '';
  myName = 'My006150Component';
}
