// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006148',
  templateUrl: './my.006148.component.html'
})
export class My006148Component {
  @Input() parentName = '';
  myName = 'My006148Component';
}
