// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006160',
  templateUrl: './my.006160.component.html'
})
export class My006160Component {
  @Input() parentName = '';
  myName = 'My006160Component';
}
