// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006096',
  templateUrl: './my.006096.component.html'
})
export class My006096Component {
  @Input() parentName = '';
  myName = 'My006096Component';
}
