// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006070',
  templateUrl: './my.006070.component.html'
})
export class My006070Component {
  @Input() parentName = '';
  myName = 'My006070Component';
}
