// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006110',
  templateUrl: './my.006110.component.html'
})
export class My006110Component {
  @Input() parentName = '';
  myName = 'My006110Component';
}
