// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006106',
  templateUrl: './my.006106.component.html'
})
export class My006106Component {
  @Input() parentName = '';
  myName = 'My006106Component';
}
