// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006062',
  templateUrl: './my.006062.component.html'
})
export class My006062Component {
  @Input() parentName = '';
  myName = 'My006062Component';
}
