// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003460',
  templateUrl: './my.003460.component.html'
})
export class My003460Component {
  @Input() parentName = '';
  myName = 'My003460Component';
}
