// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003503',
  templateUrl: './my.003503.component.html'
})
export class My003503Component {
  @Input() parentName = '';
  myName = 'My003503Component';
}
