// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003507',
  templateUrl: './my.003507.component.html'
})
export class My003507Component {
  @Input() parentName = '';
  myName = 'My003507Component';
}
