// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003514',
  templateUrl: './my.003514.component.html'
})
export class My003514Component {
  @Input() parentName = '';
  myName = 'My003514Component';
}
