// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003522',
  templateUrl: './my.003522.component.html'
})
export class My003522Component {
  @Input() parentName = '';
  myName = 'My003522Component';
}
