// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003459',
  templateUrl: './my.003459.component.html'
})
export class My003459Component {
  @Input() parentName = '';
  myName = 'My003459Component';
}
