// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003521',
  templateUrl: './my.003521.component.html'
})
export class My003521Component {
  @Input() parentName = '';
  myName = 'My003521Component';
}
