// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003529',
  templateUrl: './my.003529.component.html'
})
export class My003529Component {
  @Input() parentName = '';
  myName = 'My003529Component';
}
