// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003467',
  templateUrl: './my.003467.component.html'
})
export class My003467Component {
  @Input() parentName = '';
  myName = 'My003467Component';
}
