// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003502',
  templateUrl: './my.003502.component.html'
})
export class My003502Component {
  @Input() parentName = '';
  myName = 'My003502Component';
}
