// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003501',
  templateUrl: './my.003501.component.html'
})
export class My003501Component {
  @Input() parentName = '';
  myName = 'My003501Component';
}
