// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003458',
  templateUrl: './my.003458.component.html'
})
export class My003458Component {
  @Input() parentName = '';
  myName = 'My003458Component';
}
