// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003477',
  templateUrl: './my.003477.component.html'
})
export class My003477Component {
  @Input() parentName = '';
  myName = 'My003477Component';
}
