// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003518',
  templateUrl: './my.003518.component.html'
})
export class My003518Component {
  @Input() parentName = '';
  myName = 'My003518Component';
}
