// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003439',
  templateUrl: './my.003439.component.html'
})
export class My003439Component {
  @Input() parentName = '';
  myName = 'My003439Component';
}
