// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003452',
  templateUrl: './my.003452.component.html'
})
export class My003452Component {
  @Input() parentName = '';
  myName = 'My003452Component';
}
