// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003436',
  templateUrl: './my.003436.component.html'
})
export class My003436Component {
  @Input() parentName = '';
  myName = 'My003436Component';
}
