// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003456',
  templateUrl: './my.003456.component.html'
})
export class My003456Component {
  @Input() parentName = '';
  myName = 'My003456Component';
}
