// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009777',
  templateUrl: './my.009777.component.html'
})
export class My009777Component {
  @Input() parentName = '';
  myName = 'My009777Component';
}
