// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009718',
  templateUrl: './my.009718.component.html'
})
export class My009718Component {
  @Input() parentName = '';
  myName = 'My009718Component';
}
