// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009776',
  templateUrl: './my.009776.component.html'
})
export class My009776Component {
  @Input() parentName = '';
  myName = 'My009776Component';
}
