// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009788',
  templateUrl: './my.009788.component.html'
})
export class My009788Component {
  @Input() parentName = '';
  myName = 'My009788Component';
}
