// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009710',
  templateUrl: './my.009710.component.html'
})
export class My009710Component {
  @Input() parentName = '';
  myName = 'My009710Component';
}
