// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009697',
  templateUrl: './my.009697.component.html'
})
export class My009697Component {
  @Input() parentName = '';
  myName = 'My009697Component';
}
