// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009729',
  templateUrl: './my.009729.component.html'
})
export class My009729Component {
  @Input() parentName = '';
  myName = 'My009729Component';
}
