// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009704',
  templateUrl: './my.009704.component.html'
})
export class My009704Component {
  @Input() parentName = '';
  myName = 'My009704Component';
}
