// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009706',
  templateUrl: './my.009706.component.html'
})
export class My009706Component {
  @Input() parentName = '';
  myName = 'My009706Component';
}
