// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009721',
  templateUrl: './my.009721.component.html'
})
export class My009721Component {
  @Input() parentName = '';
  myName = 'My009721Component';
}
