// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009793',
  templateUrl: './my.009793.component.html'
})
export class My009793Component {
  @Input() parentName = '';
  myName = 'My009793Component';
}
