// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009784',
  templateUrl: './my.009784.component.html'
})
export class My009784Component {
  @Input() parentName = '';
  myName = 'My009784Component';
}
