// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009722',
  templateUrl: './my.009722.component.html'
})
export class My009722Component {
  @Input() parentName = '';
  myName = 'My009722Component';
}
