// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009770',
  templateUrl: './my.009770.component.html'
})
export class My009770Component {
  @Input() parentName = '';
  myName = 'My009770Component';
}
