// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009703',
  templateUrl: './my.009703.component.html'
})
export class My009703Component {
  @Input() parentName = '';
  myName = 'My009703Component';
}
