// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009738',
  templateUrl: './my.009738.component.html'
})
export class My009738Component {
  @Input() parentName = '';
  myName = 'My009738Component';
}
