// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004379',
  templateUrl: './my.004379.component.html'
})
export class My004379Component {
  @Input() parentName = '';
  myName = 'My004379Component';
}
