// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004418',
  templateUrl: './my.004418.component.html'
})
export class My004418Component {
  @Input() parentName = '';
  myName = 'My004418Component';
}
