// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004372',
  templateUrl: './my.004372.component.html'
})
export class My004372Component {
  @Input() parentName = '';
  myName = 'My004372Component';
}
