// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004387',
  templateUrl: './my.004387.component.html'
})
export class My004387Component {
  @Input() parentName = '';
  myName = 'My004387Component';
}
