// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004365',
  templateUrl: './my.004365.component.html'
})
export class My004365Component {
  @Input() parentName = '';
  myName = 'My004365Component';
}
