// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004407',
  templateUrl: './my.004407.component.html'
})
export class My004407Component {
  @Input() parentName = '';
  myName = 'My004407Component';
}
