// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004374',
  templateUrl: './my.004374.component.html'
})
export class My004374Component {
  @Input() parentName = '';
  myName = 'My004374Component';
}
