// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004361',
  templateUrl: './my.004361.component.html'
})
export class My004361Component {
  @Input() parentName = '';
  myName = 'My004361Component';
}
