// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004388',
  templateUrl: './my.004388.component.html'
})
export class My004388Component {
  @Input() parentName = '';
  myName = 'My004388Component';
}
