// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004420',
  templateUrl: './my.004420.component.html'
})
export class My004420Component {
  @Input() parentName = '';
  myName = 'My004420Component';
}
