// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004356',
  templateUrl: './my.004356.component.html'
})
export class My004356Component {
  @Input() parentName = '';
  myName = 'My004356Component';
}
