// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004345',
  templateUrl: './my.004345.component.html'
})
export class My004345Component {
  @Input() parentName = '';
  myName = 'My004345Component';
}
