// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009601',
  templateUrl: './my.009601.component.html'
})
export class My009601Component {
  @Input() parentName = '';
  myName = 'My009601Component';
}
