// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009670',
  templateUrl: './my.009670.component.html'
})
export class My009670Component {
  @Input() parentName = '';
  myName = 'My009670Component';
}
