// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009640',
  templateUrl: './my.009640.component.html'
})
export class My009640Component {
  @Input() parentName = '';
  myName = 'My009640Component';
}
