// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009667',
  templateUrl: './my.009667.component.html'
})
export class My009667Component {
  @Input() parentName = '';
  myName = 'My009667Component';
}
