// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009641',
  templateUrl: './my.009641.component.html'
})
export class My009641Component {
  @Input() parentName = '';
  myName = 'My009641Component';
}
