// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009630',
  templateUrl: './my.009630.component.html'
})
export class My009630Component {
  @Input() parentName = '';
  myName = 'My009630Component';
}
