// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009688',
  templateUrl: './my.009688.component.html'
})
export class My009688Component {
  @Input() parentName = '';
  myName = 'My009688Component';
}
