// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009666',
  templateUrl: './my.009666.component.html'
})
export class My009666Component {
  @Input() parentName = '';
  myName = 'My009666Component';
}
