// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009606',
  templateUrl: './my.009606.component.html'
})
export class My009606Component {
  @Input() parentName = '';
  myName = 'My009606Component';
}
