// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009685',
  templateUrl: './my.009685.component.html'
})
export class My009685Component {
  @Input() parentName = '';
  myName = 'My009685Component';
}
