// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009687',
  templateUrl: './my.009687.component.html'
})
export class My009687Component {
  @Input() parentName = '';
  myName = 'My009687Component';
}
