// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009682',
  templateUrl: './my.009682.component.html'
})
export class My009682Component {
  @Input() parentName = '';
  myName = 'My009682Component';
}
