// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009647',
  templateUrl: './my.009647.component.html'
})
export class My009647Component {
  @Input() parentName = '';
  myName = 'My009647Component';
}
