// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009615',
  templateUrl: './my.009615.component.html'
})
export class My009615Component {
  @Input() parentName = '';
  myName = 'My009615Component';
}
