// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004961',
  templateUrl: './my.004961.component.html'
})
export class My004961Component {
  @Input() parentName = '';
  myName = 'My004961Component';
}
