// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005007',
  templateUrl: './my.005007.component.html'
})
export class My005007Component {
  @Input() parentName = '';
  myName = 'My005007Component';
}
