// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005025',
  templateUrl: './my.005025.component.html'
})
export class My005025Component {
  @Input() parentName = '';
  myName = 'My005025Component';
}
