// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004997',
  templateUrl: './my.004997.component.html'
})
export class My004997Component {
  @Input() parentName = '';
  myName = 'My004997Component';
}
