// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004949',
  templateUrl: './my.004949.component.html'
})
export class My004949Component {
  @Input() parentName = '';
  myName = 'My004949Component';
}
