// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004972',
  templateUrl: './my.004972.component.html'
})
export class My004972Component {
  @Input() parentName = '';
  myName = 'My004972Component';
}
