// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004950',
  templateUrl: './my.004950.component.html'
})
export class My004950Component {
  @Input() parentName = '';
  myName = 'My004950Component';
}
