// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004953',
  templateUrl: './my.004953.component.html'
})
export class My004953Component {
  @Input() parentName = '';
  myName = 'My004953Component';
}
