// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005032',
  templateUrl: './my.005032.component.html'
})
export class My005032Component {
  @Input() parentName = '';
  myName = 'My005032Component';
}
