// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005005',
  templateUrl: './my.005005.component.html'
})
export class My005005Component {
  @Input() parentName = '';
  myName = 'My005005Component';
}
