// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004999',
  templateUrl: './my.004999.component.html'
})
export class My004999Component {
  @Input() parentName = '';
  myName = 'My004999Component';
}
