// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005023',
  templateUrl: './my.005023.component.html'
})
export class My005023Component {
  @Input() parentName = '';
  myName = 'My005023Component';
}
