// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004958',
  templateUrl: './my.004958.component.html'
})
export class My004958Component {
  @Input() parentName = '';
  myName = 'My004958Component';
}
