// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004982',
  templateUrl: './my.004982.component.html'
})
export class My004982Component {
  @Input() parentName = '';
  myName = 'My004982Component';
}
