// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004998',
  templateUrl: './my.004998.component.html'
})
export class My004998Component {
  @Input() parentName = '';
  myName = 'My004998Component';
}
