// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004991',
  templateUrl: './my.004991.component.html'
})
export class My004991Component {
  @Input() parentName = '';
  myName = 'My004991Component';
}
