// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004980',
  templateUrl: './my.004980.component.html'
})
export class My004980Component {
  @Input() parentName = '';
  myName = 'My004980Component';
}
