// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005003',
  templateUrl: './my.005003.component.html'
})
export class My005003Component {
  @Input() parentName = '';
  myName = 'My005003Component';
}
