// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005046',
  templateUrl: './my.005046.component.html'
})
export class My005046Component {
  @Input() parentName = '';
  myName = 'My005046Component';
}
