// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004966',
  templateUrl: './my.004966.component.html'
})
export class My004966Component {
  @Input() parentName = '';
  myName = 'My004966Component';
}
