// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005035',
  templateUrl: './my.005035.component.html'
})
export class My005035Component {
  @Input() parentName = '';
  myName = 'My005035Component';
}
