// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005036',
  templateUrl: './my.005036.component.html'
})
export class My005036Component {
  @Input() parentName = '';
  myName = 'My005036Component';
}
