// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005027',
  templateUrl: './my.005027.component.html'
})
export class My005027Component {
  @Input() parentName = '';
  myName = 'My005027Component';
}
