// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005009',
  templateUrl: './my.005009.component.html'
})
export class My005009Component {
  @Input() parentName = '';
  myName = 'My005009Component';
}
