// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005825',
  templateUrl: './my.005825.component.html'
})
export class My005825Component {
  @Input() parentName = '';
  myName = 'My005825Component';
}
