// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005837',
  templateUrl: './my.005837.component.html'
})
export class My005837Component {
  @Input() parentName = '';
  myName = 'My005837Component';
}
