// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005832',
  templateUrl: './my.005832.component.html'
})
export class My005832Component {
  @Input() parentName = '';
  myName = 'My005832Component';
}
