// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005785',
  templateUrl: './my.005785.component.html'
})
export class My005785Component {
  @Input() parentName = '';
  myName = 'My005785Component';
}
