// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005757',
  templateUrl: './my.005757.component.html'
})
export class My005757Component {
  @Input() parentName = '';
  myName = 'My005757Component';
}
