// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005162',
  templateUrl: './my.005162.component.html'
})
export class My005162Component {
  @Input() parentName = '';
  myName = 'My005162Component';
}
