// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005152',
  templateUrl: './my.005152.component.html'
})
export class My005152Component {
  @Input() parentName = '';
  myName = 'My005152Component';
}
