// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005244',
  templateUrl: './my.005244.component.html'
})
export class My005244Component {
  @Input() parentName = '';
  myName = 'My005244Component';
}
