// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005169',
  templateUrl: './my.005169.component.html'
})
export class My005169Component {
  @Input() parentName = '';
  myName = 'My005169Component';
}
