// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005194',
  templateUrl: './my.005194.component.html'
})
export class My005194Component {
  @Input() parentName = '';
  myName = 'My005194Component';
}
