// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005225',
  templateUrl: './my.005225.component.html'
})
export class My005225Component {
  @Input() parentName = '';
  myName = 'My005225Component';
}
