// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005179',
  templateUrl: './my.005179.component.html'
})
export class My005179Component {
  @Input() parentName = '';
  myName = 'My005179Component';
}
