// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005155',
  templateUrl: './my.005155.component.html'
})
export class My005155Component {
  @Input() parentName = '';
  myName = 'My005155Component';
}
