// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005248',
  templateUrl: './my.005248.component.html'
})
export class My005248Component {
  @Input() parentName = '';
  myName = 'My005248Component';
}
