// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005158',
  templateUrl: './my.005158.component.html'
})
export class My005158Component {
  @Input() parentName = '';
  myName = 'My005158Component';
}
