// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005237',
  templateUrl: './my.005237.component.html'
})
export class My005237Component {
  @Input() parentName = '';
  myName = 'My005237Component';
}
