// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005236',
  templateUrl: './my.005236.component.html'
})
export class My005236Component {
  @Input() parentName = '';
  myName = 'My005236Component';
}
