// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005249',
  templateUrl: './my.005249.component.html'
})
export class My005249Component {
  @Input() parentName = '';
  myName = 'My005249Component';
}
