// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005166',
  templateUrl: './my.005166.component.html'
})
export class My005166Component {
  @Input() parentName = '';
  myName = 'My005166Component';
}
