// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005210',
  templateUrl: './my.005210.component.html'
})
export class My005210Component {
  @Input() parentName = '';
  myName = 'My005210Component';
}
