// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005168',
  templateUrl: './my.005168.component.html'
})
export class My005168Component {
  @Input() parentName = '';
  myName = 'My005168Component';
}
