// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006247',
  templateUrl: './my.006247.component.html'
})
export class My006247Component {
  @Input() parentName = '';
  myName = 'My006247Component';
}
