// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006204',
  templateUrl: './my.006204.component.html'
})
export class My006204Component {
  @Input() parentName = '';
  myName = 'My006204Component';
}
