// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006213',
  templateUrl: './my.006213.component.html'
})
export class My006213Component {
  @Input() parentName = '';
  myName = 'My006213Component';
}
