// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006193',
  templateUrl: './my.006193.component.html'
})
export class My006193Component {
  @Input() parentName = '';
  myName = 'My006193Component';
}
