// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006165',
  templateUrl: './my.006165.component.html'
})
export class My006165Component {
  @Input() parentName = '';
  myName = 'My006165Component';
}
