// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006217',
  templateUrl: './my.006217.component.html'
})
export class My006217Component {
  @Input() parentName = '';
  myName = 'My006217Component';
}
