// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006211',
  templateUrl: './my.006211.component.html'
})
export class My006211Component {
  @Input() parentName = '';
  myName = 'My006211Component';
}
