// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006234',
  templateUrl: './my.006234.component.html'
})
export class My006234Component {
  @Input() parentName = '';
  myName = 'My006234Component';
}
