// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006227',
  templateUrl: './my.006227.component.html'
})
export class My006227Component {
  @Input() parentName = '';
  myName = 'My006227Component';
}
