// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006260',
  templateUrl: './my.006260.component.html'
})
export class My006260Component {
  @Input() parentName = '';
  myName = 'My006260Component';
}
