// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006252',
  templateUrl: './my.006252.component.html'
})
export class My006252Component {
  @Input() parentName = '';
  myName = 'My006252Component';
}
