// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004461',
  templateUrl: './my.004461.component.html'
})
export class My004461Component {
  @Input() parentName = '';
  myName = 'My004461Component';
}
