// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004475',
  templateUrl: './my.004475.component.html'
})
export class My004475Component {
  @Input() parentName = '';
  myName = 'My004475Component';
}
