// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004533',
  templateUrl: './my.004533.component.html'
})
export class My004533Component {
  @Input() parentName = '';
  myName = 'My004533Component';
}
