// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004489',
  templateUrl: './my.004489.component.html'
})
export class My004489Component {
  @Input() parentName = '';
  myName = 'My004489Component';
}
