// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004541',
  templateUrl: './my.004541.component.html'
})
export class My004541Component {
  @Input() parentName = '';
  myName = 'My004541Component';
}
