// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004498',
  templateUrl: './my.004498.component.html'
})
export class My004498Component {
  @Input() parentName = '';
  myName = 'My004498Component';
}
