// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004544',
  templateUrl: './my.004544.component.html'
})
export class My004544Component {
  @Input() parentName = '';
  myName = 'My004544Component';
}
