// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004515',
  templateUrl: './my.004515.component.html'
})
export class My004515Component {
  @Input() parentName = '';
  myName = 'My004515Component';
}
