// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004525',
  templateUrl: './my.004525.component.html'
})
export class My004525Component {
  @Input() parentName = '';
  myName = 'My004525Component';
}
