// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004474',
  templateUrl: './my.004474.component.html'
})
export class My004474Component {
  @Input() parentName = '';
  myName = 'My004474Component';
}
