// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004477',
  templateUrl: './my.004477.component.html'
})
export class My004477Component {
  @Input() parentName = '';
  myName = 'My004477Component';
}
