// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004482',
  templateUrl: './my.004482.component.html'
})
export class My004482Component {
  @Input() parentName = '';
  myName = 'My004482Component';
}
