// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004469',
  templateUrl: './my.004469.component.html'
})
export class My004469Component {
  @Input() parentName = '';
  myName = 'My004469Component';
}
