// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002475',
  templateUrl: './my.002475.component.html'
})
export class My002475Component {
  @Input() parentName = '';
  myName = 'My002475Component';
}
