// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002517',
  templateUrl: './my.002517.component.html'
})
export class My002517Component {
  @Input() parentName = '';
  myName = 'My002517Component';
}
