// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002469',
  templateUrl: './my.002469.component.html'
})
export class My002469Component {
  @Input() parentName = '';
  myName = 'My002469Component';
}
