// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002433',
  templateUrl: './my.002433.component.html'
})
export class My002433Component {
  @Input() parentName = '';
  myName = 'My002433Component';
}
