// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002485',
  templateUrl: './my.002485.component.html'
})
export class My002485Component {
  @Input() parentName = '';
  myName = 'My002485Component';
}
