// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002488',
  templateUrl: './my.002488.component.html'
})
export class My002488Component {
  @Input() parentName = '';
  myName = 'My002488Component';
}
