// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002424',
  templateUrl: './my.002424.component.html'
})
export class My002424Component {
  @Input() parentName = '';
  myName = 'My002424Component';
}
