// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002489',
  templateUrl: './my.002489.component.html'
})
export class My002489Component {
  @Input() parentName = '';
  myName = 'My002489Component';
}
