// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002476',
  templateUrl: './my.002476.component.html'
})
export class My002476Component {
  @Input() parentName = '';
  myName = 'My002476Component';
}
