// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002521',
  templateUrl: './my.002521.component.html'
})
export class My002521Component {
  @Input() parentName = '';
  myName = 'My002521Component';
}
