// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002459',
  templateUrl: './my.002459.component.html'
})
export class My002459Component {
  @Input() parentName = '';
  myName = 'My002459Component';
}
