// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002492',
  templateUrl: './my.002492.component.html'
})
export class My002492Component {
  @Input() parentName = '';
  myName = 'My002492Component';
}
