// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002484',
  templateUrl: './my.002484.component.html'
})
export class My002484Component {
  @Input() parentName = '';
  myName = 'My002484Component';
}
