// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002514',
  templateUrl: './my.002514.component.html'
})
export class My002514Component {
  @Input() parentName = '';
  myName = 'My002514Component';
}
