// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002480',
  templateUrl: './my.002480.component.html'
})
export class My002480Component {
  @Input() parentName = '';
  myName = 'My002480Component';
}
