// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002522',
  templateUrl: './my.002522.component.html'
})
export class My002522Component {
  @Input() parentName = '';
  myName = 'My002522Component';
}
