// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002486',
  templateUrl: './my.002486.component.html'
})
export class My002486Component {
  @Input() parentName = '';
  myName = 'My002486Component';
}
