// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002452',
  templateUrl: './my.002452.component.html'
})
export class My002452Component {
  @Input() parentName = '';
  myName = 'My002452Component';
}
