// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002434',
  templateUrl: './my.002434.component.html'
})
export class My002434Component {
  @Input() parentName = '';
  myName = 'My002434Component';
}
