// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002457',
  templateUrl: './my.002457.component.html'
})
export class My002457Component {
  @Input() parentName = '';
  myName = 'My002457Component';
}
