// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002451',
  templateUrl: './my.002451.component.html'
})
export class My002451Component {
  @Input() parentName = '';
  myName = 'My002451Component';
}
