// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002428',
  templateUrl: './my.002428.component.html'
})
export class My002428Component {
  @Input() parentName = '';
  myName = 'My002428Component';
}
