// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008595',
  templateUrl: './my.008595.component.html'
})
export class My008595Component {
  @Input() parentName = '';
  myName = 'My008595Component';
}
