// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008600',
  templateUrl: './my.008600.component.html'
})
export class My008600Component {
  @Input() parentName = '';
  myName = 'My008600Component';
}
