// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008675',
  templateUrl: './my.008675.component.html'
})
export class My008675Component {
  @Input() parentName = '';
  myName = 'My008675Component';
}
