// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008631',
  templateUrl: './my.008631.component.html'
})
export class My008631Component {
  @Input() parentName = '';
  myName = 'My008631Component';
}
