// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008621',
  templateUrl: './my.008621.component.html'
})
export class My008621Component {
  @Input() parentName = '';
  myName = 'My008621Component';
}
