// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008594',
  templateUrl: './my.008594.component.html'
})
export class My008594Component {
  @Input() parentName = '';
  myName = 'My008594Component';
}
