// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008637',
  templateUrl: './my.008637.component.html'
})
export class My008637Component {
  @Input() parentName = '';
  myName = 'My008637Component';
}
