// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008677',
  templateUrl: './my.008677.component.html'
})
export class My008677Component {
  @Input() parentName = '';
  myName = 'My008677Component';
}
