// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008623',
  templateUrl: './my.008623.component.html'
})
export class My008623Component {
  @Input() parentName = '';
  myName = 'My008623Component';
}
