// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008633',
  templateUrl: './my.008633.component.html'
})
export class My008633Component {
  @Input() parentName = '';
  myName = 'My008633Component';
}
