// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008591',
  templateUrl: './my.008591.component.html'
})
export class My008591Component {
  @Input() parentName = '';
  myName = 'My008591Component';
}
