// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008634',
  templateUrl: './my.008634.component.html'
})
export class My008634Component {
  @Input() parentName = '';
  myName = 'My008634Component';
}
