// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008603',
  templateUrl: './my.008603.component.html'
})
export class My008603Component {
  @Input() parentName = '';
  myName = 'My008603Component';
}
