// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008627',
  templateUrl: './my.008627.component.html'
})
export class My008627Component {
  @Input() parentName = '';
  myName = 'My008627Component';
}
