// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008653',
  templateUrl: './my.008653.component.html'
})
export class My008653Component {
  @Input() parentName = '';
  myName = 'My008653Component';
}
