// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008635',
  templateUrl: './my.008635.component.html'
})
export class My008635Component {
  @Input() parentName = '';
  myName = 'My008635Component';
}
