// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008683',
  templateUrl: './my.008683.component.html'
})
export class My008683Component {
  @Input() parentName = '';
  myName = 'My008683Component';
}
