// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008590',
  templateUrl: './my.008590.component.html'
})
export class My008590Component {
  @Input() parentName = '';
  myName = 'My008590Component';
}
