// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005460',
  templateUrl: './my.005460.component.html'
})
export class My005460Component {
  @Input() parentName = '';
  myName = 'My005460Component';
}
