// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005517',
  templateUrl: './my.005517.component.html'
})
export class My005517Component {
  @Input() parentName = '';
  myName = 'My005517Component';
}
