// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005545',
  templateUrl: './my.005545.component.html'
})
export class My005545Component {
  @Input() parentName = '';
  myName = 'My005545Component';
}
