// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005488',
  templateUrl: './my.005488.component.html'
})
export class My005488Component {
  @Input() parentName = '';
  myName = 'My005488Component';
}
