// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005553',
  templateUrl: './my.005553.component.html'
})
export class My005553Component {
  @Input() parentName = '';
  myName = 'My005553Component';
}
