// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005478',
  templateUrl: './my.005478.component.html'
})
export class My005478Component {
  @Input() parentName = '';
  myName = 'My005478Component';
}
