// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005454',
  templateUrl: './my.005454.component.html'
})
export class My005454Component {
  @Input() parentName = '';
  myName = 'My005454Component';
}
