// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005482',
  templateUrl: './my.005482.component.html'
})
export class My005482Component {
  @Input() parentName = '';
  myName = 'My005482Component';
}
