// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005550',
  templateUrl: './my.005550.component.html'
})
export class My005550Component {
  @Input() parentName = '';
  myName = 'My005550Component';
}
