// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005486',
  templateUrl: './my.005486.component.html'
})
export class My005486Component {
  @Input() parentName = '';
  myName = 'My005486Component';
}
