// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005549',
  templateUrl: './my.005549.component.html'
})
export class My005549Component {
  @Input() parentName = '';
  myName = 'My005549Component';
}
