// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005471',
  templateUrl: './my.005471.component.html'
})
export class My005471Component {
  @Input() parentName = '';
  myName = 'My005471Component';
}
