// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005500',
  templateUrl: './my.005500.component.html'
})
export class My005500Component {
  @Input() parentName = '';
  myName = 'My005500Component';
}
