// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005463',
  templateUrl: './my.005463.component.html'
})
export class My005463Component {
  @Input() parentName = '';
  myName = 'My005463Component';
}
