// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003071',
  templateUrl: './my.003071.component.html'
})
export class My003071Component {
  @Input() parentName = '';
  myName = 'My003071Component';
}
