// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003061',
  templateUrl: './my.003061.component.html'
})
export class My003061Component {
  @Input() parentName = '';
  myName = 'My003061Component';
}
