// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003109',
  templateUrl: './my.003109.component.html'
})
export class My003109Component {
  @Input() parentName = '';
  myName = 'My003109Component';
}
