// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003123',
  templateUrl: './my.003123.component.html'
})
export class My003123Component {
  @Input() parentName = '';
  myName = 'My003123Component';
}
