// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003113',
  templateUrl: './my.003113.component.html'
})
export class My003113Component {
  @Input() parentName = '';
  myName = 'My003113Component';
}
