// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003037',
  templateUrl: './my.003037.component.html'
})
export class My003037Component {
  @Input() parentName = '';
  myName = 'My003037Component';
}
