// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003063',
  templateUrl: './my.003063.component.html'
})
export class My003063Component {
  @Input() parentName = '';
  myName = 'My003063Component';
}
