// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003102',
  templateUrl: './my.003102.component.html'
})
export class My003102Component {
  @Input() parentName = '';
  myName = 'My003102Component';
}
