// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003031',
  templateUrl: './my.003031.component.html'
})
export class My003031Component {
  @Input() parentName = '';
  myName = 'My003031Component';
}
