// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003035',
  templateUrl: './my.003035.component.html'
})
export class My003035Component {
  @Input() parentName = '';
  myName = 'My003035Component';
}
