// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003048',
  templateUrl: './my.003048.component.html'
})
export class My003048Component {
  @Input() parentName = '';
  myName = 'My003048Component';
}
