// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003041',
  templateUrl: './my.003041.component.html'
})
export class My003041Component {
  @Input() parentName = '';
  myName = 'My003041Component';
}
