// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004728',
  templateUrl: './my.004728.component.html'
})
export class My004728Component {
  @Input() parentName = '';
  myName = 'My004728Component';
}
