// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004730',
  templateUrl: './my.004730.component.html'
})
export class My004730Component {
  @Input() parentName = '';
  myName = 'My004730Component';
}
