// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004711',
  templateUrl: './my.004711.component.html'
})
export class My004711Component {
  @Input() parentName = '';
  myName = 'My004711Component';
}
