// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004674',
  templateUrl: './my.004674.component.html'
})
export class My004674Component {
  @Input() parentName = '';
  myName = 'My004674Component';
}
