// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004692',
  templateUrl: './my.004692.component.html'
})
export class My004692Component {
  @Input() parentName = '';
  myName = 'My004692Component';
}
