// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004670',
  templateUrl: './my.004670.component.html'
})
export class My004670Component {
  @Input() parentName = '';
  myName = 'My004670Component';
}
