// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004738',
  templateUrl: './my.004738.component.html'
})
export class My004738Component {
  @Input() parentName = '';
  myName = 'My004738Component';
}
