// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004679',
  templateUrl: './my.004679.component.html'
})
export class My004679Component {
  @Input() parentName = '';
  myName = 'My004679Component';
}
