// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004726',
  templateUrl: './my.004726.component.html'
})
export class My004726Component {
  @Input() parentName = '';
  myName = 'My004726Component';
}
