// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004659',
  templateUrl: './my.004659.component.html'
})
export class My004659Component {
  @Input() parentName = '';
  myName = 'My004659Component';
}
