// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004655',
  templateUrl: './my.004655.component.html'
})
export class My004655Component {
  @Input() parentName = '';
  myName = 'My004655Component';
}
