// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004709',
  templateUrl: './my.004709.component.html'
})
export class My004709Component {
  @Input() parentName = '';
  myName = 'My004709Component';
}
