// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004705',
  templateUrl: './my.004705.component.html'
})
export class My004705Component {
  @Input() parentName = '';
  myName = 'My004705Component';
}
