// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004662',
  templateUrl: './my.004662.component.html'
})
export class My004662Component {
  @Input() parentName = '';
  myName = 'My004662Component';
}
