// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004678',
  templateUrl: './my.004678.component.html'
})
export class My004678Component {
  @Input() parentName = '';
  myName = 'My004678Component';
}
