// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002662',
  templateUrl: './my.002662.component.html'
})
export class My002662Component {
  @Input() parentName = '';
  myName = 'My002662Component';
}
