// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002632',
  templateUrl: './my.002632.component.html'
})
export class My002632Component {
  @Input() parentName = '';
  myName = 'My002632Component';
}
