// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002646',
  templateUrl: './my.002646.component.html'
})
export class My002646Component {
  @Input() parentName = '';
  myName = 'My002646Component';
}
