// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002636',
  templateUrl: './my.002636.component.html'
})
export class My002636Component {
  @Input() parentName = '';
  myName = 'My002636Component';
}
