// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002633',
  templateUrl: './my.002633.component.html'
})
export class My002633Component {
  @Input() parentName = '';
  myName = 'My002633Component';
}
