// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002698',
  templateUrl: './my.002698.component.html'
})
export class My002698Component {
  @Input() parentName = '';
  myName = 'My002698Component';
}
