// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002628',
  templateUrl: './my.002628.component.html'
})
export class My002628Component {
  @Input() parentName = '';
  myName = 'My002628Component';
}
