// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002666',
  templateUrl: './my.002666.component.html'
})
export class My002666Component {
  @Input() parentName = '';
  myName = 'My002666Component';
}
