// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002629',
  templateUrl: './my.002629.component.html'
})
export class My002629Component {
  @Input() parentName = '';
  myName = 'My002629Component';
}
