// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002665',
  templateUrl: './my.002665.component.html'
})
export class My002665Component {
  @Input() parentName = '';
  myName = 'My002665Component';
}
