// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002630',
  templateUrl: './my.002630.component.html'
})
export class My002630Component {
  @Input() parentName = '';
  myName = 'My002630Component';
}
