// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002686',
  templateUrl: './my.002686.component.html'
})
export class My002686Component {
  @Input() parentName = '';
  myName = 'My002686Component';
}
