// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002692',
  templateUrl: './my.002692.component.html'
})
export class My002692Component {
  @Input() parentName = '';
  myName = 'My002692Component';
}
