// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002693',
  templateUrl: './my.002693.component.html'
})
export class My002693Component {
  @Input() parentName = '';
  myName = 'My002693Component';
}
