// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002714',
  templateUrl: './my.002714.component.html'
})
export class My002714Component {
  @Input() parentName = '';
  myName = 'My002714Component';
}
