// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002707',
  templateUrl: './my.002707.component.html'
})
export class My002707Component {
  @Input() parentName = '';
  myName = 'My002707Component';
}
