// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002639',
  templateUrl: './my.002639.component.html'
})
export class My002639Component {
  @Input() parentName = '';
  myName = 'My002639Component';
}
