// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006960',
  templateUrl: './my.006960.component.html'
})
export class My006960Component {
  @Input() parentName = '';
  myName = 'My006960Component';
}
