// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006878',
  templateUrl: './my.006878.component.html'
})
export class My006878Component {
  @Input() parentName = '';
  myName = 'My006878Component';
}
