// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006909',
  templateUrl: './my.006909.component.html'
})
export class My006909Component {
  @Input() parentName = '';
  myName = 'My006909Component';
}
