// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006935',
  templateUrl: './my.006935.component.html'
})
export class My006935Component {
  @Input() parentName = '';
  myName = 'My006935Component';
}
