// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006956',
  templateUrl: './my.006956.component.html'
})
export class My006956Component {
  @Input() parentName = '';
  myName = 'My006956Component';
}
