// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006899',
  templateUrl: './my.006899.component.html'
})
export class My006899Component {
  @Input() parentName = '';
  myName = 'My006899Component';
}
