// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006937',
  templateUrl: './my.006937.component.html'
})
export class My006937Component {
  @Input() parentName = '';
  myName = 'My006937Component';
}
