// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006897',
  templateUrl: './my.006897.component.html'
})
export class My006897Component {
  @Input() parentName = '';
  myName = 'My006897Component';
}
