// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006936',
  templateUrl: './my.006936.component.html'
})
export class My006936Component {
  @Input() parentName = '';
  myName = 'My006936Component';
}
