// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006931',
  templateUrl: './my.006931.component.html'
})
export class My006931Component {
  @Input() parentName = '';
  myName = 'My006931Component';
}
