// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006869',
  templateUrl: './my.006869.component.html'
})
export class My006869Component {
  @Input() parentName = '';
  myName = 'My006869Component';
}
