// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005696',
  templateUrl: './my.005696.component.html'
})
export class My005696Component {
  @Input() parentName = '';
  myName = 'My005696Component';
}
