// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005742',
  templateUrl: './my.005742.component.html'
})
export class My005742Component {
  @Input() parentName = '';
  myName = 'My005742Component';
}
