// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005749',
  templateUrl: './my.005749.component.html'
})
export class My005749Component {
  @Input() parentName = '';
  myName = 'My005749Component';
}
