// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005668',
  templateUrl: './my.005668.component.html'
})
export class My005668Component {
  @Input() parentName = '';
  myName = 'My005668Component';
}
