// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005715',
  templateUrl: './my.005715.component.html'
})
export class My005715Component {
  @Input() parentName = '';
  myName = 'My005715Component';
}
