// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005688',
  templateUrl: './my.005688.component.html'
})
export class My005688Component {
  @Input() parentName = '';
  myName = 'My005688Component';
}
