// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005750',
  templateUrl: './my.005750.component.html'
})
export class My005750Component {
  @Input() parentName = '';
  myName = 'My005750Component';
}
