// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005679',
  templateUrl: './my.005679.component.html'
})
export class My005679Component {
  @Input() parentName = '';
  myName = 'My005679Component';
}
