// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005711',
  templateUrl: './my.005711.component.html'
})
export class My005711Component {
  @Input() parentName = '';
  myName = 'My005711Component';
}
