// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005707',
  templateUrl: './my.005707.component.html'
})
export class My005707Component {
  @Input() parentName = '';
  myName = 'My005707Component';
}
