// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006002',
  templateUrl: './my.006002.component.html'
})
export class My006002Component {
  @Input() parentName = '';
  myName = 'My006002Component';
}
