// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006036',
  templateUrl: './my.006036.component.html'
})
export class My006036Component {
  @Input() parentName = '';
  myName = 'My006036Component';
}
