// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005973',
  templateUrl: './my.005973.component.html'
})
export class My005973Component {
  @Input() parentName = '';
  myName = 'My005973Component';
}
