// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006034',
  templateUrl: './my.006034.component.html'
})
export class My006034Component {
  @Input() parentName = '';
  myName = 'My006034Component';
}
