// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006030',
  templateUrl: './my.006030.component.html'
})
export class My006030Component {
  @Input() parentName = '';
  myName = 'My006030Component';
}
