// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006004',
  templateUrl: './my.006004.component.html'
})
export class My006004Component {
  @Input() parentName = '';
  myName = 'My006004Component';
}
