// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006054',
  templateUrl: './my.006054.component.html'
})
export class My006054Component {
  @Input() parentName = '';
  myName = 'My006054Component';
}
