// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006055',
  templateUrl: './my.006055.component.html'
})
export class My006055Component {
  @Input() parentName = '';
  myName = 'My006055Component';
}
