// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005962',
  templateUrl: './my.005962.component.html'
})
export class My005962Component {
  @Input() parentName = '';
  myName = 'My005962Component';
}
