// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006048',
  templateUrl: './my.006048.component.html'
})
export class My006048Component {
  @Input() parentName = '';
  myName = 'My006048Component';
}
