// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006008',
  templateUrl: './my.006008.component.html'
})
export class My006008Component {
  @Input() parentName = '';
  myName = 'My006008Component';
}
