// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004337',
  templateUrl: './my.004337.component.html'
})
export class My004337Component {
  @Input() parentName = '';
  myName = 'My004337Component';
}
