// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004306',
  templateUrl: './my.004306.component.html'
})
export class My004306Component {
  @Input() parentName = '';
  myName = 'My004306Component';
}
