// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004273',
  templateUrl: './my.004273.component.html'
})
export class My004273Component {
  @Input() parentName = '';
  myName = 'My004273Component';
}
