// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004246',
  templateUrl: './my.004246.component.html'
})
export class My004246Component {
  @Input() parentName = '';
  myName = 'My004246Component';
}
