// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004327',
  templateUrl: './my.004327.component.html'
})
export class My004327Component {
  @Input() parentName = '';
  myName = 'My004327Component';
}
