// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004286',
  templateUrl: './my.004286.component.html'
})
export class My004286Component {
  @Input() parentName = '';
  myName = 'My004286Component';
}
