// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004300',
  templateUrl: './my.004300.component.html'
})
export class My004300Component {
  @Input() parentName = '';
  myName = 'My004300Component';
}
