// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004307',
  templateUrl: './my.004307.component.html'
})
export class My004307Component {
  @Input() parentName = '';
  myName = 'My004307Component';
}
