// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004285',
  templateUrl: './my.004285.component.html'
})
export class My004285Component {
  @Input() parentName = '';
  myName = 'My004285Component';
}
