// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004268',
  templateUrl: './my.004268.component.html'
})
export class My004268Component {
  @Input() parentName = '';
  myName = 'My004268Component';
}
