// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004256',
  templateUrl: './my.004256.component.html'
})
export class My004256Component {
  @Input() parentName = '';
  myName = 'My004256Component';
}
