// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004287',
  templateUrl: './my.004287.component.html'
})
export class My004287Component {
  @Input() parentName = '';
  myName = 'My004287Component';
}
