// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004294',
  templateUrl: './my.004294.component.html'
})
export class My004294Component {
  @Input() parentName = '';
  myName = 'My004294Component';
}
