// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007893',
  templateUrl: './my.007893.component.html'
})
export class My007893Component {
  @Input() parentName = '';
  myName = 'My007893Component';
}
