// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007921',
  templateUrl: './my.007921.component.html'
})
export class My007921Component {
  @Input() parentName = '';
  myName = 'My007921Component';
}
