// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007934',
  templateUrl: './my.007934.component.html'
})
export class My007934Component {
  @Input() parentName = '';
  myName = 'My007934Component';
}
