// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007895',
  templateUrl: './my.007895.component.html'
})
export class My007895Component {
  @Input() parentName = '';
  myName = 'My007895Component';
}
