// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007907',
  templateUrl: './my.007907.component.html'
})
export class My007907Component {
  @Input() parentName = '';
  myName = 'My007907Component';
}
