// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007964',
  templateUrl: './my.007964.component.html'
})
export class My007964Component {
  @Input() parentName = '';
  myName = 'My007964Component';
}
