// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007958',
  templateUrl: './my.007958.component.html'
})
export class My007958Component {
  @Input() parentName = '';
  myName = 'My007958Component';
}
