// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007881',
  templateUrl: './my.007881.component.html'
})
export class My007881Component {
  @Input() parentName = '';
  myName = 'My007881Component';
}
