// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007928',
  templateUrl: './my.007928.component.html'
})
export class My007928Component {
  @Input() parentName = '';
  myName = 'My007928Component';
}
