// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007896',
  templateUrl: './my.007896.component.html'
})
export class My007896Component {
  @Input() parentName = '';
  myName = 'My007896Component';
}
