// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007911',
  templateUrl: './my.007911.component.html'
})
export class My007911Component {
  @Input() parentName = '';
  myName = 'My007911Component';
}
