// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007892',
  templateUrl: './my.007892.component.html'
})
export class My007892Component {
  @Input() parentName = '';
  myName = 'My007892Component';
}
