// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007903',
  templateUrl: './my.007903.component.html'
})
export class My007903Component {
  @Input() parentName = '';
  myName = 'My007903Component';
}
