// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007889',
  templateUrl: './my.007889.component.html'
})
export class My007889Component {
  @Input() parentName = '';
  myName = 'My007889Component';
}
