// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007891',
  templateUrl: './my.007891.component.html'
})
export class My007891Component {
  @Input() parentName = '';
  myName = 'My007891Component';
}
