// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007904',
  templateUrl: './my.007904.component.html'
})
export class My007904Component {
  @Input() parentName = '';
  myName = 'My007904Component';
}
