// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002585',
  templateUrl: './my.002585.component.html'
})
export class My002585Component {
  @Input() parentName = '';
  myName = 'My002585Component';
}
