// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002596',
  templateUrl: './my.002596.component.html'
})
export class My002596Component {
  @Input() parentName = '';
  myName = 'My002596Component';
}
