// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002602',
  templateUrl: './my.002602.component.html'
})
export class My002602Component {
  @Input() parentName = '';
  myName = 'My002602Component';
}
