// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002606',
  templateUrl: './my.002606.component.html'
})
export class My002606Component {
  @Input() parentName = '';
  myName = 'My002606Component';
}
