// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002604',
  templateUrl: './my.002604.component.html'
})
export class My002604Component {
  @Input() parentName = '';
  myName = 'My002604Component';
}
