// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002552',
  templateUrl: './my.002552.component.html'
})
export class My002552Component {
  @Input() parentName = '';
  myName = 'My002552Component';
}
