// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002615',
  templateUrl: './my.002615.component.html'
})
export class My002615Component {
  @Input() parentName = '';
  myName = 'My002615Component';
}
