// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002622',
  templateUrl: './my.002622.component.html'
})
export class My002622Component {
  @Input() parentName = '';
  myName = 'My002622Component';
}
