// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002609',
  templateUrl: './my.002609.component.html'
})
export class My002609Component {
  @Input() parentName = '';
  myName = 'My002609Component';
}
