// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002575',
  templateUrl: './my.002575.component.html'
})
export class My002575Component {
  @Input() parentName = '';
  myName = 'My002575Component';
}
