// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002527',
  templateUrl: './my.002527.component.html'
})
export class My002527Component {
  @Input() parentName = '';
  myName = 'My002527Component';
}
