// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002591',
  templateUrl: './my.002591.component.html'
})
export class My002591Component {
  @Input() parentName = '';
  myName = 'My002591Component';
}
