// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002541',
  templateUrl: './my.002541.component.html'
})
export class My002541Component {
  @Input() parentName = '';
  myName = 'My002541Component';
}
