// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002586',
  templateUrl: './my.002586.component.html'
})
export class My002586Component {
  @Input() parentName = '';
  myName = 'My002586Component';
}
