// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002595',
  templateUrl: './my.002595.component.html'
})
export class My002595Component {
  @Input() parentName = '';
  myName = 'My002595Component';
}
