// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002576',
  templateUrl: './my.002576.component.html'
})
export class My002576Component {
  @Input() parentName = '';
  myName = 'My002576Component';
}
