// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002564',
  templateUrl: './my.002564.component.html'
})
export class My002564Component {
  @Input() parentName = '';
  myName = 'My002564Component';
}
