// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My008888Component } from './my.008888.component';
import { My008889Component } from './my.008889.component';
import { My008890Component } from './my.008890.component';
import { My008891Component } from './my.008891.component';
import { My008892Component } from './my.008892.component';
import { My008893Component } from './my.008893.component';
import { My008894Component } from './my.008894.component';
import { My008895Component } from './my.008895.component';
import { My008896Component } from './my.008896.component';
import { My008897Component } from './my.008897.component';
import { My008898Component } from './my.008898.component';
import { My008899Component } from './my.008899.component';
import { My008900Component } from './my.008900.component';
import { My008901Component } from './my.008901.component';
import { My008902Component } from './my.008902.component';
import { My008903Component } from './my.008903.component';
import { My008904Component } from './my.008904.component';
import { My008905Component } from './my.008905.component';
import { My008906Component } from './my.008906.component';
import { My008907Component } from './my.008907.component';
import { My008908Component } from './my.008908.component';
import { My008909Component } from './my.008909.component';
import { My008910Component } from './my.008910.component';
import { My008911Component } from './my.008911.component';
import { My008912Component } from './my.008912.component';
import { My008913Component } from './my.008913.component';
import { My008914Component } from './my.008914.component';
import { My008915Component } from './my.008915.component';
import { My008916Component } from './my.008916.component';
import { My008917Component } from './my.008917.component';
import { My008918Component } from './my.008918.component';
import { My008919Component } from './my.008919.component';
import { My008920Component } from './my.008920.component';
import { My008921Component } from './my.008921.component';
import { My008922Component } from './my.008922.component';
import { My008923Component } from './my.008923.component';
import { My008924Component } from './my.008924.component';
import { My008925Component } from './my.008925.component';
import { My008926Component } from './my.008926.component';
import { My008927Component } from './my.008927.component';
import { My008928Component } from './my.008928.component';
import { My008929Component } from './my.008929.component';
import { My008930Component } from './my.008930.component';
import { My008931Component } from './my.008931.component';
import { My008932Component } from './my.008932.component';
import { My008933Component } from './my.008933.component';
import { My008934Component } from './my.008934.component';
import { My008935Component } from './my.008935.component';
import { My008936Component } from './my.008936.component';
import { My008937Component } from './my.008937.component';
import { My008938Component } from './my.008938.component';
import { My008939Component } from './my.008939.component';
import { My008940Component } from './my.008940.component';
import { My008941Component } from './my.008941.component';
import { My008942Component } from './my.008942.component';
import { My008943Component } from './my.008943.component';
import { My008944Component } from './my.008944.component';
import { My008945Component } from './my.008945.component';
import { My008946Component } from './my.008946.component';
import { My008947Component } from './my.008947.component';
import { My008948Component } from './my.008948.component';
import { My008949Component } from './my.008949.component';
import { My008950Component } from './my.008950.component';
import { My008951Component } from './my.008951.component';
import { My008952Component } from './my.008952.component';
import { My008953Component } from './my.008953.component';
import { My008954Component } from './my.008954.component';
import { My008955Component } from './my.008955.component';
import { My008956Component } from './my.008956.component';
import { My008957Component } from './my.008957.component';
import { My008958Component } from './my.008958.component';
import { My008959Component } from './my.008959.component';
import { My008960Component } from './my.008960.component';
import { My008961Component } from './my.008961.component';
import { My008962Component } from './my.008962.component';
import { My008963Component } from './my.008963.component';
import { My008964Component } from './my.008964.component';
import { My008965Component } from './my.008965.component';
import { My008966Component } from './my.008966.component';
import { My008967Component } from './my.008967.component';
import { My008968Component } from './my.008968.component';
import { My008969Component } from './my.008969.component';
import { My008970Component } from './my.008970.component';
import { My008971Component } from './my.008971.component';
import { My008972Component } from './my.008972.component';
import { My008973Component } from './my.008973.component';
import { My008974Component } from './my.008974.component';
import { My008975Component } from './my.008975.component';
import { My008976Component } from './my.008976.component';
import { My008977Component } from './my.008977.component';
import { My008978Component } from './my.008978.component';
import { My008979Component } from './my.008979.component';
import { My008980Component } from './my.008980.component';
import { My008981Component } from './my.008981.component';
import { My008982Component } from './my.008982.component';
import { My008983Component } from './my.008983.component';
import { My008984Component } from './my.008984.component';
import { My008985Component } from './my.008985.component';
import { My008986Component } from './my.008986.component';
import { My008987Component } from './my.008987.component';
import { My008988Component } from './my.008988.component';

@NgModule({
  declarations: [
    My008888Component,
    My008889Component,
    My008890Component,
    My008891Component,
    My008892Component,
    My008893Component,
    My008894Component,
    My008895Component,
    My008896Component,
    My008897Component,
    My008898Component,
    My008899Component,
    My008900Component,
    My008901Component,
    My008902Component,
    My008903Component,
    My008904Component,
    My008905Component,
    My008906Component,
    My008907Component,
    My008908Component,
    My008909Component,
    My008910Component,
    My008911Component,
    My008912Component,
    My008913Component,
    My008914Component,
    My008915Component,
    My008916Component,
    My008917Component,
    My008918Component,
    My008919Component,
    My008920Component,
    My008921Component,
    My008922Component,
    My008923Component,
    My008924Component,
    My008925Component,
    My008926Component,
    My008927Component,
    My008928Component,
    My008929Component,
    My008930Component,
    My008931Component,
    My008932Component,
    My008933Component,
    My008934Component,
    My008935Component,
    My008936Component,
    My008937Component,
    My008938Component,
    My008939Component,
    My008940Component,
    My008941Component,
    My008942Component,
    My008943Component,
    My008944Component,
    My008945Component,
    My008946Component,
    My008947Component,
    My008948Component,
    My008949Component,
    My008950Component,
    My008951Component,
    My008952Component,
    My008953Component,
    My008954Component,
    My008955Component,
    My008956Component,
    My008957Component,
    My008958Component,
    My008959Component,
    My008960Component,
    My008961Component,
    My008962Component,
    My008963Component,
    My008964Component,
    My008965Component,
    My008966Component,
    My008967Component,
    My008968Component,
    My008969Component,
    My008970Component,
    My008971Component,
    My008972Component,
    My008973Component,
    My008974Component,
    My008975Component,
    My008976Component,
    My008977Component,
    My008978Component,
    My008979Component,
    My008980Component,
    My008981Component,
    My008982Component,
    My008983Component,
    My008984Component,
    My008985Component,
    My008986Component,
    My008987Component,
    My008988Component,
  ],
  imports: [CommonModule],
  exports: [
    My008888Component,
  ]
})
export class Module000088 { }
