// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008967',
  templateUrl: './my.008967.component.html'
})
export class My008967Component {
  @Input() parentName = '';
  myName = 'My008967Component';
}
