// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008970',
  templateUrl: './my.008970.component.html'
})
export class My008970Component {
  @Input() parentName = '';
  myName = 'My008970Component';
}
