// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008982',
  templateUrl: './my.008982.component.html'
})
export class My008982Component {
  @Input() parentName = '';
  myName = 'My008982Component';
}
