// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008937',
  templateUrl: './my.008937.component.html'
})
export class My008937Component {
  @Input() parentName = '';
  myName = 'My008937Component';
}
