// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008981',
  templateUrl: './my.008981.component.html'
})
export class My008981Component {
  @Input() parentName = '';
  myName = 'My008981Component';
}
