// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008977',
  templateUrl: './my.008977.component.html'
})
export class My008977Component {
  @Input() parentName = '';
  myName = 'My008977Component';
}
