// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008960',
  templateUrl: './my.008960.component.html'
})
export class My008960Component {
  @Input() parentName = '';
  myName = 'My008960Component';
}
