// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008988',
  templateUrl: './my.008988.component.html'
})
export class My008988Component {
  @Input() parentName = '';
  myName = 'My008988Component';
}
