// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008952',
  templateUrl: './my.008952.component.html'
})
export class My008952Component {
  @Input() parentName = '';
  myName = 'My008952Component';
}
