// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008895',
  templateUrl: './my.008895.component.html'
})
export class My008895Component {
  @Input() parentName = '';
  myName = 'My008895Component';
}
