// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008901',
  templateUrl: './my.008901.component.html'
})
export class My008901Component {
  @Input() parentName = '';
  myName = 'My008901Component';
}
