// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008894',
  templateUrl: './my.008894.component.html'
})
export class My008894Component {
  @Input() parentName = '';
  myName = 'My008894Component';
}
