// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008903',
  templateUrl: './my.008903.component.html'
})
export class My008903Component {
  @Input() parentName = '';
  myName = 'My008903Component';
}
