// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009070',
  templateUrl: './my.009070.component.html'
})
export class My009070Component {
  @Input() parentName = '';
  myName = 'My009070Component';
}
