// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009071',
  templateUrl: './my.009071.component.html'
})
export class My009071Component {
  @Input() parentName = '';
  myName = 'My009071Component';
}
