// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009065',
  templateUrl: './my.009065.component.html'
})
export class My009065Component {
  @Input() parentName = '';
  myName = 'My009065Component';
}
