// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009085',
  templateUrl: './my.009085.component.html'
})
export class My009085Component {
  @Input() parentName = '';
  myName = 'My009085Component';
}
