// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009078',
  templateUrl: './my.009078.component.html'
})
export class My009078Component {
  @Input() parentName = '';
  myName = 'My009078Component';
}
