// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009044',
  templateUrl: './my.009044.component.html'
})
export class My009044Component {
  @Input() parentName = '';
  myName = 'My009044Component';
}
