// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009028',
  templateUrl: './my.009028.component.html'
})
export class My009028Component {
  @Input() parentName = '';
  myName = 'My009028Component';
}
