// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009022',
  templateUrl: './my.009022.component.html'
})
export class My009022Component {
  @Input() parentName = '';
  myName = 'My009022Component';
}
