// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009062',
  templateUrl: './my.009062.component.html'
})
export class My009062Component {
  @Input() parentName = '';
  myName = 'My009062Component';
}
