// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009077',
  templateUrl: './my.009077.component.html'
})
export class My009077Component {
  @Input() parentName = '';
  myName = 'My009077Component';
}
