// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009046',
  templateUrl: './my.009046.component.html'
})
export class My009046Component {
  @Input() parentName = '';
  myName = 'My009046Component';
}
