// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009019',
  templateUrl: './my.009019.component.html'
})
export class My009019Component {
  @Input() parentName = '';
  myName = 'My009019Component';
}
