// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009086',
  templateUrl: './my.009086.component.html'
})
export class My009086Component {
  @Input() parentName = '';
  myName = 'My009086Component';
}
