// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003262',
  templateUrl: './my.003262.component.html'
})
export class My003262Component {
  @Input() parentName = '';
  myName = 'My003262Component';
}
