// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003272',
  templateUrl: './my.003272.component.html'
})
export class My003272Component {
  @Input() parentName = '';
  myName = 'My003272Component';
}
