// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003267',
  templateUrl: './my.003267.component.html'
})
export class My003267Component {
  @Input() parentName = '';
  myName = 'My003267Component';
}
