// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003276',
  templateUrl: './my.003276.component.html'
})
export class My003276Component {
  @Input() parentName = '';
  myName = 'My003276Component';
}
