// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003302',
  templateUrl: './my.003302.component.html'
})
export class My003302Component {
  @Input() parentName = '';
  myName = 'My003302Component';
}
