// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003315',
  templateUrl: './my.003315.component.html'
})
export class My003315Component {
  @Input() parentName = '';
  myName = 'My003315Component';
}
