// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003287',
  templateUrl: './my.003287.component.html'
})
export class My003287Component {
  @Input() parentName = '';
  myName = 'My003287Component';
}
