// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003256',
  templateUrl: './my.003256.component.html'
})
export class My003256Component {
  @Input() parentName = '';
  myName = 'My003256Component';
}
