// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003298',
  templateUrl: './my.003298.component.html'
})
export class My003298Component {
  @Input() parentName = '';
  myName = 'My003298Component';
}
