// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003299',
  templateUrl: './my.003299.component.html'
})
export class My003299Component {
  @Input() parentName = '';
  myName = 'My003299Component';
}
