// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006667',
  templateUrl: './my.006667.component.html'
})
export class My006667Component {
  @Input() parentName = '';
  myName = 'My006667Component';
}
