// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006756',
  templateUrl: './my.006756.component.html'
})
export class My006756Component {
  @Input() parentName = '';
  myName = 'My006756Component';
}
