// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006742',
  templateUrl: './my.006742.component.html'
})
export class My006742Component {
  @Input() parentName = '';
  myName = 'My006742Component';
}
