// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006702',
  templateUrl: './my.006702.component.html'
})
export class My006702Component {
  @Input() parentName = '';
  myName = 'My006702Component';
}
