// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006731',
  templateUrl: './my.006731.component.html'
})
export class My006731Component {
  @Input() parentName = '';
  myName = 'My006731Component';
}
