// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006672',
  templateUrl: './my.006672.component.html'
})
export class My006672Component {
  @Input() parentName = '';
  myName = 'My006672Component';
}
