// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006747',
  templateUrl: './my.006747.component.html'
})
export class My006747Component {
  @Input() parentName = '';
  myName = 'My006747Component';
}
