// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006685',
  templateUrl: './my.006685.component.html'
})
export class My006685Component {
  @Input() parentName = '';
  myName = 'My006685Component';
}
