// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006721',
  templateUrl: './my.006721.component.html'
})
export class My006721Component {
  @Input() parentName = '';
  myName = 'My006721Component';
}
