// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006675',
  templateUrl: './my.006675.component.html'
})
export class My006675Component {
  @Input() parentName = '';
  myName = 'My006675Component';
}
