// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006679',
  templateUrl: './my.006679.component.html'
})
export class My006679Component {
  @Input() parentName = '';
  myName = 'My006679Component';
}
