// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006677',
  templateUrl: './my.006677.component.html'
})
export class My006677Component {
  @Input() parentName = '';
  myName = 'My006677Component';
}
