// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006681',
  templateUrl: './my.006681.component.html'
})
export class My006681Component {
  @Input() parentName = '';
  myName = 'My006681Component';
}
