// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006743',
  templateUrl: './my.006743.component.html'
})
export class My006743Component {
  @Input() parentName = '';
  myName = 'My006743Component';
}
