// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006690',
  templateUrl: './my.006690.component.html'
})
export class My006690Component {
  @Input() parentName = '';
  myName = 'My006690Component';
}
