// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006755',
  templateUrl: './my.006755.component.html'
})
export class My006755Component {
  @Input() parentName = '';
  myName = 'My006755Component';
}
