// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006720',
  templateUrl: './my.006720.component.html'
})
export class My006720Component {
  @Input() parentName = '';
  myName = 'My006720Component';
}
