// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006714',
  templateUrl: './my.006714.component.html'
})
export class My006714Component {
  @Input() parentName = '';
  myName = 'My006714Component';
}
