// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006671',
  templateUrl: './my.006671.component.html'
})
export class My006671Component {
  @Input() parentName = '';
  myName = 'My006671Component';
}
