// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002044',
  templateUrl: './my.002044.component.html'
})
export class My002044Component {
  @Input() parentName = '';
  myName = 'My002044Component';
}
