// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002040',
  templateUrl: './my.002040.component.html'
})
export class My002040Component {
  @Input() parentName = '';
  myName = 'My002040Component';
}
