// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002026',
  templateUrl: './my.002026.component.html'
})
export class My002026Component {
  @Input() parentName = '';
  myName = 'My002026Component';
}
