// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002073',
  templateUrl: './my.002073.component.html'
})
export class My002073Component {
  @Input() parentName = '';
  myName = 'My002073Component';
}
