// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002102',
  templateUrl: './my.002102.component.html'
})
export class My002102Component {
  @Input() parentName = '';
  myName = 'My002102Component';
}
