// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002087',
  templateUrl: './my.002087.component.html'
})
export class My002087Component {
  @Input() parentName = '';
  myName = 'My002087Component';
}
