// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002085',
  templateUrl: './my.002085.component.html'
})
export class My002085Component {
  @Input() parentName = '';
  myName = 'My002085Component';
}
