// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002096',
  templateUrl: './my.002096.component.html'
})
export class My002096Component {
  @Input() parentName = '';
  myName = 'My002096Component';
}
