// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002069',
  templateUrl: './my.002069.component.html'
})
export class My002069Component {
  @Input() parentName = '';
  myName = 'My002069Component';
}
