// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002107',
  templateUrl: './my.002107.component.html'
})
export class My002107Component {
  @Input() parentName = '';
  myName = 'My002107Component';
}
