// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002028',
  templateUrl: './my.002028.component.html'
})
export class My002028Component {
  @Input() parentName = '';
  myName = 'My002028Component';
}
