// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002074',
  templateUrl: './my.002074.component.html'
})
export class My002074Component {
  @Input() parentName = '';
  myName = 'My002074Component';
}
