// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002038',
  templateUrl: './my.002038.component.html'
})
export class My002038Component {
  @Input() parentName = '';
  myName = 'My002038Component';
}
