// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002079',
  templateUrl: './my.002079.component.html'
})
export class My002079Component {
  @Input() parentName = '';
  myName = 'My002079Component';
}
