// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006623',
  templateUrl: './my.006623.component.html'
})
export class My006623Component {
  @Input() parentName = '';
  myName = 'My006623Component';
}
