// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006642',
  templateUrl: './my.006642.component.html'
})
export class My006642Component {
  @Input() parentName = '';
  myName = 'My006642Component';
}
