// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006619',
  templateUrl: './my.006619.component.html'
})
export class My006619Component {
  @Input() parentName = '';
  myName = 'My006619Component';
}
