// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006569',
  templateUrl: './my.006569.component.html'
})
export class My006569Component {
  @Input() parentName = '';
  myName = 'My006569Component';
}
