// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006617',
  templateUrl: './my.006617.component.html'
})
export class My006617Component {
  @Input() parentName = '';
  myName = 'My006617Component';
}
