// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006636',
  templateUrl: './my.006636.component.html'
})
export class My006636Component {
  @Input() parentName = '';
  myName = 'My006636Component';
}
