// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006662',
  templateUrl: './my.006662.component.html'
})
export class My006662Component {
  @Input() parentName = '';
  myName = 'My006662Component';
}
