// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006599',
  templateUrl: './my.006599.component.html'
})
export class My006599Component {
  @Input() parentName = '';
  myName = 'My006599Component';
}
