// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006576',
  templateUrl: './my.006576.component.html'
})
export class My006576Component {
  @Input() parentName = '';
  myName = 'My006576Component';
}
