// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006581',
  templateUrl: './my.006581.component.html'
})
export class My006581Component {
  @Input() parentName = '';
  myName = 'My006581Component';
}
