// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006571',
  templateUrl: './my.006571.component.html'
})
export class My006571Component {
  @Input() parentName = '';
  myName = 'My006571Component';
}
