// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006622',
  templateUrl: './my.006622.component.html'
})
export class My006622Component {
  @Input() parentName = '';
  myName = 'My006622Component';
}
