// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004810',
  templateUrl: './my.004810.component.html'
})
export class My004810Component {
  @Input() parentName = '';
  myName = 'My004810Component';
}
