// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004836',
  templateUrl: './my.004836.component.html'
})
export class My004836Component {
  @Input() parentName = '';
  myName = 'My004836Component';
}
