// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004824',
  templateUrl: './my.004824.component.html'
})
export class My004824Component {
  @Input() parentName = '';
  myName = 'My004824Component';
}
