// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004813',
  templateUrl: './my.004813.component.html'
})
export class My004813Component {
  @Input() parentName = '';
  myName = 'My004813Component';
}
