// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004832',
  templateUrl: './my.004832.component.html'
})
export class My004832Component {
  @Input() parentName = '';
  myName = 'My004832Component';
}
