// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004814',
  templateUrl: './my.004814.component.html'
})
export class My004814Component {
  @Input() parentName = '';
  myName = 'My004814Component';
}
