// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004765',
  templateUrl: './my.004765.component.html'
})
export class My004765Component {
  @Input() parentName = '';
  myName = 'My004765Component';
}
