// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004846',
  templateUrl: './my.004846.component.html'
})
export class My004846Component {
  @Input() parentName = '';
  myName = 'My004846Component';
}
