// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004750',
  templateUrl: './my.004750.component.html'
})
export class My004750Component {
  @Input() parentName = '';
  myName = 'My004750Component';
}
