// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004835',
  templateUrl: './my.004835.component.html'
})
export class My004835Component {
  @Input() parentName = '';
  myName = 'My004835Component';
}
