// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004762',
  templateUrl: './my.004762.component.html'
})
export class My004762Component {
  @Input() parentName = '';
  myName = 'My004762Component';
}
