// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004822',
  templateUrl: './my.004822.component.html'
})
export class My004822Component {
  @Input() parentName = '';
  myName = 'My004822Component';
}
