// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004766',
  templateUrl: './my.004766.component.html'
})
export class My004766Component {
  @Input() parentName = '';
  myName = 'My004766Component';
}
