// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004794',
  templateUrl: './my.004794.component.html'
})
export class My004794Component {
  @Input() parentName = '';
  myName = 'My004794Component';
}
