// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004768',
  templateUrl: './my.004768.component.html'
})
export class My004768Component {
  @Input() parentName = '';
  myName = 'My004768Component';
}
