// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004753',
  templateUrl: './my.004753.component.html'
})
export class My004753Component {
  @Input() parentName = '';
  myName = 'My004753Component';
}
