// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009463',
  templateUrl: './my.009463.component.html'
})
export class My009463Component {
  @Input() parentName = '';
  myName = 'My009463Component';
}
