// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009487',
  templateUrl: './my.009487.component.html'
})
export class My009487Component {
  @Input() parentName = '';
  myName = 'My009487Component';
}
