// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009413',
  templateUrl: './my.009413.component.html'
})
export class My009413Component {
  @Input() parentName = '';
  myName = 'My009413Component';
}
