// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009480',
  templateUrl: './my.009480.component.html'
})
export class My009480Component {
  @Input() parentName = '';
  myName = 'My009480Component';
}
