// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009426',
  templateUrl: './my.009426.component.html'
})
export class My009426Component {
  @Input() parentName = '';
  myName = 'My009426Component';
}
