// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009433',
  templateUrl: './my.009433.component.html'
})
export class My009433Component {
  @Input() parentName = '';
  myName = 'My009433Component';
}
