// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009489',
  templateUrl: './my.009489.component.html'
})
export class My009489Component {
  @Input() parentName = '';
  myName = 'My009489Component';
}
