// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009412',
  templateUrl: './my.009412.component.html'
})
export class My009412Component {
  @Input() parentName = '';
  myName = 'My009412Component';
}
