// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009425',
  templateUrl: './my.009425.component.html'
})
export class My009425Component {
  @Input() parentName = '';
  myName = 'My009425Component';
}
