// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009479',
  templateUrl: './my.009479.component.html'
})
export class My009479Component {
  @Input() parentName = '';
  myName = 'My009479Component';
}
