// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009483',
  templateUrl: './my.009483.component.html'
})
export class My009483Component {
  @Input() parentName = '';
  myName = 'My009483Component';
}
