// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009404',
  templateUrl: './my.009404.component.html'
})
export class My009404Component {
  @Input() parentName = '';
  myName = 'My009404Component';
}
