// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009434',
  templateUrl: './my.009434.component.html'
})
export class My009434Component {
  @Input() parentName = '';
  myName = 'My009434Component';
}
