// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009459',
  templateUrl: './my.009459.component.html'
})
export class My009459Component {
  @Input() parentName = '';
  myName = 'My009459Component';
}
