// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009471',
  templateUrl: './my.009471.component.html'
})
export class My009471Component {
  @Input() parentName = '';
  myName = 'My009471Component';
}
