// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My005252Component } from './my.005252.component';
import { My005253Component } from './my.005253.component';
import { My005254Component } from './my.005254.component';
import { My005255Component } from './my.005255.component';
import { My005256Component } from './my.005256.component';
import { My005257Component } from './my.005257.component';
import { My005258Component } from './my.005258.component';
import { My005259Component } from './my.005259.component';
import { My005260Component } from './my.005260.component';
import { My005261Component } from './my.005261.component';
import { My005262Component } from './my.005262.component';
import { My005263Component } from './my.005263.component';
import { My005264Component } from './my.005264.component';
import { My005265Component } from './my.005265.component';
import { My005266Component } from './my.005266.component';
import { My005267Component } from './my.005267.component';
import { My005268Component } from './my.005268.component';
import { My005269Component } from './my.005269.component';
import { My005270Component } from './my.005270.component';
import { My005271Component } from './my.005271.component';
import { My005272Component } from './my.005272.component';
import { My005273Component } from './my.005273.component';
import { My005274Component } from './my.005274.component';
import { My005275Component } from './my.005275.component';
import { My005276Component } from './my.005276.component';
import { My005277Component } from './my.005277.component';
import { My005278Component } from './my.005278.component';
import { My005279Component } from './my.005279.component';
import { My005280Component } from './my.005280.component';
import { My005281Component } from './my.005281.component';
import { My005282Component } from './my.005282.component';
import { My005283Component } from './my.005283.component';
import { My005284Component } from './my.005284.component';
import { My005285Component } from './my.005285.component';
import { My005286Component } from './my.005286.component';
import { My005287Component } from './my.005287.component';
import { My005288Component } from './my.005288.component';
import { My005289Component } from './my.005289.component';
import { My005290Component } from './my.005290.component';
import { My005291Component } from './my.005291.component';
import { My005292Component } from './my.005292.component';
import { My005293Component } from './my.005293.component';
import { My005294Component } from './my.005294.component';
import { My005295Component } from './my.005295.component';
import { My005296Component } from './my.005296.component';
import { My005297Component } from './my.005297.component';
import { My005298Component } from './my.005298.component';
import { My005299Component } from './my.005299.component';
import { My005300Component } from './my.005300.component';
import { My005301Component } from './my.005301.component';
import { My005302Component } from './my.005302.component';
import { My005303Component } from './my.005303.component';
import { My005304Component } from './my.005304.component';
import { My005305Component } from './my.005305.component';
import { My005306Component } from './my.005306.component';
import { My005307Component } from './my.005307.component';
import { My005308Component } from './my.005308.component';
import { My005309Component } from './my.005309.component';
import { My005310Component } from './my.005310.component';
import { My005311Component } from './my.005311.component';
import { My005312Component } from './my.005312.component';
import { My005313Component } from './my.005313.component';
import { My005314Component } from './my.005314.component';
import { My005315Component } from './my.005315.component';
import { My005316Component } from './my.005316.component';
import { My005317Component } from './my.005317.component';
import { My005318Component } from './my.005318.component';
import { My005319Component } from './my.005319.component';
import { My005320Component } from './my.005320.component';
import { My005321Component } from './my.005321.component';
import { My005322Component } from './my.005322.component';
import { My005323Component } from './my.005323.component';
import { My005324Component } from './my.005324.component';
import { My005325Component } from './my.005325.component';
import { My005326Component } from './my.005326.component';
import { My005327Component } from './my.005327.component';
import { My005328Component } from './my.005328.component';
import { My005329Component } from './my.005329.component';
import { My005330Component } from './my.005330.component';
import { My005331Component } from './my.005331.component';
import { My005332Component } from './my.005332.component';
import { My005333Component } from './my.005333.component';
import { My005334Component } from './my.005334.component';
import { My005335Component } from './my.005335.component';
import { My005336Component } from './my.005336.component';
import { My005337Component } from './my.005337.component';
import { My005338Component } from './my.005338.component';
import { My005339Component } from './my.005339.component';
import { My005340Component } from './my.005340.component';
import { My005341Component } from './my.005341.component';
import { My005342Component } from './my.005342.component';
import { My005343Component } from './my.005343.component';
import { My005344Component } from './my.005344.component';
import { My005345Component } from './my.005345.component';
import { My005346Component } from './my.005346.component';
import { My005347Component } from './my.005347.component';
import { My005348Component } from './my.005348.component';
import { My005349Component } from './my.005349.component';
import { My005350Component } from './my.005350.component';
import { My005351Component } from './my.005351.component';
import { My005352Component } from './my.005352.component';

@NgModule({
  declarations: [
    My005252Component,
    My005253Component,
    My005254Component,
    My005255Component,
    My005256Component,
    My005257Component,
    My005258Component,
    My005259Component,
    My005260Component,
    My005261Component,
    My005262Component,
    My005263Component,
    My005264Component,
    My005265Component,
    My005266Component,
    My005267Component,
    My005268Component,
    My005269Component,
    My005270Component,
    My005271Component,
    My005272Component,
    My005273Component,
    My005274Component,
    My005275Component,
    My005276Component,
    My005277Component,
    My005278Component,
    My005279Component,
    My005280Component,
    My005281Component,
    My005282Component,
    My005283Component,
    My005284Component,
    My005285Component,
    My005286Component,
    My005287Component,
    My005288Component,
    My005289Component,
    My005290Component,
    My005291Component,
    My005292Component,
    My005293Component,
    My005294Component,
    My005295Component,
    My005296Component,
    My005297Component,
    My005298Component,
    My005299Component,
    My005300Component,
    My005301Component,
    My005302Component,
    My005303Component,
    My005304Component,
    My005305Component,
    My005306Component,
    My005307Component,
    My005308Component,
    My005309Component,
    My005310Component,
    My005311Component,
    My005312Component,
    My005313Component,
    My005314Component,
    My005315Component,
    My005316Component,
    My005317Component,
    My005318Component,
    My005319Component,
    My005320Component,
    My005321Component,
    My005322Component,
    My005323Component,
    My005324Component,
    My005325Component,
    My005326Component,
    My005327Component,
    My005328Component,
    My005329Component,
    My005330Component,
    My005331Component,
    My005332Component,
    My005333Component,
    My005334Component,
    My005335Component,
    My005336Component,
    My005337Component,
    My005338Component,
    My005339Component,
    My005340Component,
    My005341Component,
    My005342Component,
    My005343Component,
    My005344Component,
    My005345Component,
    My005346Component,
    My005347Component,
    My005348Component,
    My005349Component,
    My005350Component,
    My005351Component,
    My005352Component,
  ],
  imports: [CommonModule],
  exports: [
    My005252Component,
  ]
})
export class Module000052 { }
