// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005259',
  templateUrl: './my.005259.component.html'
})
export class My005259Component {
  @Input() parentName = '';
  myName = 'My005259Component';
}
