// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005283',
  templateUrl: './my.005283.component.html'
})
export class My005283Component {
  @Input() parentName = '';
  myName = 'My005283Component';
}
