// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005322',
  templateUrl: './my.005322.component.html'
})
export class My005322Component {
  @Input() parentName = '';
  myName = 'My005322Component';
}
