// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005265',
  templateUrl: './my.005265.component.html'
})
export class My005265Component {
  @Input() parentName = '';
  myName = 'My005265Component';
}
