// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005257',
  templateUrl: './my.005257.component.html'
})
export class My005257Component {
  @Input() parentName = '';
  myName = 'My005257Component';
}
