// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005335',
  templateUrl: './my.005335.component.html'
})
export class My005335Component {
  @Input() parentName = '';
  myName = 'My005335Component';
}
