// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005267',
  templateUrl: './my.005267.component.html'
})
export class My005267Component {
  @Input() parentName = '';
  myName = 'My005267Component';
}
