// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005345',
  templateUrl: './my.005345.component.html'
})
export class My005345Component {
  @Input() parentName = '';
  myName = 'My005345Component';
}
