// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005325',
  templateUrl: './my.005325.component.html'
})
export class My005325Component {
  @Input() parentName = '';
  myName = 'My005325Component';
}
