// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005343',
  templateUrl: './my.005343.component.html'
})
export class My005343Component {
  @Input() parentName = '';
  myName = 'My005343Component';
}
