// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005255',
  templateUrl: './my.005255.component.html'
})
export class My005255Component {
  @Input() parentName = '';
  myName = 'My005255Component';
}
