// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005348',
  templateUrl: './my.005348.component.html'
})
export class My005348Component {
  @Input() parentName = '';
  myName = 'My005348Component';
}
