// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005276',
  templateUrl: './my.005276.component.html'
})
export class My005276Component {
  @Input() parentName = '';
  myName = 'My005276Component';
}
