// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005289',
  templateUrl: './my.005289.component.html'
})
export class My005289Component {
  @Input() parentName = '';
  myName = 'My005289Component';
}
