// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005338',
  templateUrl: './my.005338.component.html'
})
export class My005338Component {
  @Input() parentName = '';
  myName = 'My005338Component';
}
