// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005321',
  templateUrl: './my.005321.component.html'
})
export class My005321Component {
  @Input() parentName = '';
  myName = 'My005321Component';
}
