// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005330',
  templateUrl: './my.005330.component.html'
})
export class My005330Component {
  @Input() parentName = '';
  myName = 'My005330Component';
}
