// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008358',
  templateUrl: './my.008358.component.html'
})
export class My008358Component {
  @Input() parentName = '';
  myName = 'My008358Component';
}
