// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008368',
  templateUrl: './my.008368.component.html'
})
export class My008368Component {
  @Input() parentName = '';
  myName = 'My008368Component';
}
