// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008365',
  templateUrl: './my.008365.component.html'
})
export class My008365Component {
  @Input() parentName = '';
  myName = 'My008365Component';
}
