// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008345',
  templateUrl: './my.008345.component.html'
})
export class My008345Component {
  @Input() parentName = '';
  myName = 'My008345Component';
}
