// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008296',
  templateUrl: './my.008296.component.html'
})
export class My008296Component {
  @Input() parentName = '';
  myName = 'My008296Component';
}
