// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008322',
  templateUrl: './my.008322.component.html'
})
export class My008322Component {
  @Input() parentName = '';
  myName = 'My008322Component';
}
