// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008342',
  templateUrl: './my.008342.component.html'
})
export class My008342Component {
  @Input() parentName = '';
  myName = 'My008342Component';
}
