// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008359',
  templateUrl: './my.008359.component.html'
})
export class My008359Component {
  @Input() parentName = '';
  myName = 'My008359Component';
}
