// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008333',
  templateUrl: './my.008333.component.html'
})
export class My008333Component {
  @Input() parentName = '';
  myName = 'My008333Component';
}
