// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008336',
  templateUrl: './my.008336.component.html'
})
export class My008336Component {
  @Input() parentName = '';
  myName = 'My008336Component';
}
