// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007791',
  templateUrl: './my.007791.component.html'
})
export class My007791Component {
  @Input() parentName = '';
  myName = 'My007791Component';
}
