// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007859',
  templateUrl: './my.007859.component.html'
})
export class My007859Component {
  @Input() parentName = '';
  myName = 'My007859Component';
}
