// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007793',
  templateUrl: './my.007793.component.html'
})
export class My007793Component {
  @Input() parentName = '';
  myName = 'My007793Component';
}
