// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007872',
  templateUrl: './my.007872.component.html'
})
export class My007872Component {
  @Input() parentName = '';
  myName = 'My007872Component';
}
