// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007808',
  templateUrl: './my.007808.component.html'
})
export class My007808Component {
  @Input() parentName = '';
  myName = 'My007808Component';
}
