// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007812',
  templateUrl: './my.007812.component.html'
})
export class My007812Component {
  @Input() parentName = '';
  myName = 'My007812Component';
}
