// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007830',
  templateUrl: './my.007830.component.html'
})
export class My007830Component {
  @Input() parentName = '';
  myName = 'My007830Component';
}
