// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007792',
  templateUrl: './my.007792.component.html'
})
export class My007792Component {
  @Input() parentName = '';
  myName = 'My007792Component';
}
