// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007849',
  templateUrl: './my.007849.component.html'
})
export class My007849Component {
  @Input() parentName = '';
  myName = 'My007849Component';
}
