// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007869',
  templateUrl: './my.007869.component.html'
})
export class My007869Component {
  @Input() parentName = '';
  myName = 'My007869Component';
}
