// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007846',
  templateUrl: './my.007846.component.html'
})
export class My007846Component {
  @Input() parentName = '';
  myName = 'My007846Component';
}
