// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007798',
  templateUrl: './my.007798.component.html'
})
export class My007798Component {
  @Input() parentName = '';
  myName = 'My007798Component';
}
