// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007839',
  templateUrl: './my.007839.component.html'
})
export class My007839Component {
  @Input() parentName = '';
  myName = 'My007839Component';
}
