// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007828',
  templateUrl: './my.007828.component.html'
})
export class My007828Component {
  @Input() parentName = '';
  myName = 'My007828Component';
}
