// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007841',
  templateUrl: './my.007841.component.html'
})
export class My007841Component {
  @Input() parentName = '';
  myName = 'My007841Component';
}
