// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007820',
  templateUrl: './my.007820.component.html'
})
export class My007820Component {
  @Input() parentName = '';
  myName = 'My007820Component';
}
