// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007786',
  templateUrl: './my.007786.component.html'
})
export class My007786Component {
  @Input() parentName = '';
  myName = 'My007786Component';
}
