// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007877',
  templateUrl: './my.007877.component.html'
})
export class My007877Component {
  @Input() parentName = '';
  myName = 'My007877Component';
}
