// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007852',
  templateUrl: './my.007852.component.html'
})
export class My007852Component {
  @Input() parentName = '';
  myName = 'My007852Component';
}
