// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003650',
  templateUrl: './my.003650.component.html'
})
export class My003650Component {
  @Input() parentName = '';
  myName = 'My003650Component';
}
