// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003707',
  templateUrl: './my.003707.component.html'
})
export class My003707Component {
  @Input() parentName = '';
  myName = 'My003707Component';
}
