// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003705',
  templateUrl: './my.003705.component.html'
})
export class My003705Component {
  @Input() parentName = '';
  myName = 'My003705Component';
}
