// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003717',
  templateUrl: './my.003717.component.html'
})
export class My003717Component {
  @Input() parentName = '';
  myName = 'My003717Component';
}
