// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003664',
  templateUrl: './my.003664.component.html'
})
export class My003664Component {
  @Input() parentName = '';
  myName = 'My003664Component';
}
