// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003687',
  templateUrl: './my.003687.component.html'
})
export class My003687Component {
  @Input() parentName = '';
  myName = 'My003687Component';
}
