// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003636',
  templateUrl: './my.003636.component.html'
})
export class My003636Component {
  @Input() parentName = '';
  myName = 'My003636Component';
}
