// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003693',
  templateUrl: './my.003693.component.html'
})
export class My003693Component {
  @Input() parentName = '';
  myName = 'My003693Component';
}
