// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003649',
  templateUrl: './my.003649.component.html'
})
export class My003649Component {
  @Input() parentName = '';
  myName = 'My003649Component';
}
