// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003712',
  templateUrl: './my.003712.component.html'
})
export class My003712Component {
  @Input() parentName = '';
  myName = 'My003712Component';
}
