// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003666',
  templateUrl: './my.003666.component.html'
})
export class My003666Component {
  @Input() parentName = '';
  myName = 'My003666Component';
}
