// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003671',
  templateUrl: './my.003671.component.html'
})
export class My003671Component {
  @Input() parentName = '';
  myName = 'My003671Component';
}
