// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003729',
  templateUrl: './my.003729.component.html'
})
export class My003729Component {
  @Input() parentName = '';
  myName = 'My003729Component';
}
