// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003644',
  templateUrl: './my.003644.component.html'
})
export class My003644Component {
  @Input() parentName = '';
  myName = 'My003644Component';
}
