// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003686',
  templateUrl: './my.003686.component.html'
})
export class My003686Component {
  @Input() parentName = '';
  myName = 'My003686Component';
}
