// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003669',
  templateUrl: './my.003669.component.html'
})
export class My003669Component {
  @Input() parentName = '';
  myName = 'My003669Component';
}
