// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003708',
  templateUrl: './my.003708.component.html'
})
export class My003708Component {
  @Input() parentName = '';
  myName = 'My003708Component';
}
