// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003704',
  templateUrl: './my.003704.component.html'
})
export class My003704Component {
  @Input() parentName = '';
  myName = 'My003704Component';
}
