// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004935',
  templateUrl: './my.004935.component.html'
})
export class My004935Component {
  @Input() parentName = '';
  myName = 'My004935Component';
}
