// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004937',
  templateUrl: './my.004937.component.html'
})
export class My004937Component {
  @Input() parentName = '';
  myName = 'My004937Component';
}
