// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004880',
  templateUrl: './my.004880.component.html'
})
export class My004880Component {
  @Input() parentName = '';
  myName = 'My004880Component';
}
