// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004902',
  templateUrl: './my.004902.component.html'
})
export class My004902Component {
  @Input() parentName = '';
  myName = 'My004902Component';
}
