// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004920',
  templateUrl: './my.004920.component.html'
})
export class My004920Component {
  @Input() parentName = '';
  myName = 'My004920Component';
}
