// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004945',
  templateUrl: './my.004945.component.html'
})
export class My004945Component {
  @Input() parentName = '';
  myName = 'My004945Component';
}
