// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004853',
  templateUrl: './my.004853.component.html'
})
export class My004853Component {
  @Input() parentName = '';
  myName = 'My004853Component';
}
