// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004923',
  templateUrl: './my.004923.component.html'
})
export class My004923Component {
  @Input() parentName = '';
  myName = 'My004923Component';
}
