// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004927',
  templateUrl: './my.004927.component.html'
})
export class My004927Component {
  @Input() parentName = '';
  myName = 'My004927Component';
}
