// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004933',
  templateUrl: './my.004933.component.html'
})
export class My004933Component {
  @Input() parentName = '';
  myName = 'My004933Component';
}
