// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004916',
  templateUrl: './my.004916.component.html'
})
export class My004916Component {
  @Input() parentName = '';
  myName = 'My004916Component';
}
