// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004940',
  templateUrl: './my.004940.component.html'
})
export class My004940Component {
  @Input() parentName = '';
  myName = 'My004940Component';
}
