// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004848',
  templateUrl: './my.004848.component.html'
})
export class My004848Component {
  @Input() parentName = '';
  myName = 'My004848Component';
}
