// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004897',
  templateUrl: './my.004897.component.html'
})
export class My004897Component {
  @Input() parentName = '';
  myName = 'My004897Component';
}
