// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004882',
  templateUrl: './my.004882.component.html'
})
export class My004882Component {
  @Input() parentName = '';
  myName = 'My004882Component';
}
