// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004855',
  templateUrl: './my.004855.component.html'
})
export class My004855Component {
  @Input() parentName = '';
  myName = 'My004855Component';
}
