// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004879',
  templateUrl: './my.004879.component.html'
})
export class My004879Component {
  @Input() parentName = '';
  myName = 'My004879Component';
}
