// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004869',
  templateUrl: './my.004869.component.html'
})
export class My004869Component {
  @Input() parentName = '';
  myName = 'My004869Component';
}
