// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005629',
  templateUrl: './my.005629.component.html'
})
export class My005629Component {
  @Input() parentName = '';
  myName = 'My005629Component';
}
