// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005594',
  templateUrl: './my.005594.component.html'
})
export class My005594Component {
  @Input() parentName = '';
  myName = 'My005594Component';
}
