// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005635',
  templateUrl: './my.005635.component.html'
})
export class My005635Component {
  @Input() parentName = '';
  myName = 'My005635Component';
}
