// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005630',
  templateUrl: './my.005630.component.html'
})
export class My005630Component {
  @Input() parentName = '';
  myName = 'My005630Component';
}
