// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005633',
  templateUrl: './my.005633.component.html'
})
export class My005633Component {
  @Input() parentName = '';
  myName = 'My005633Component';
}
