// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005555',
  templateUrl: './my.005555.component.html'
})
export class My005555Component {
  @Input() parentName = '';
  myName = 'My005555Component';
}
