// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005560',
  templateUrl: './my.005560.component.html'
})
export class My005560Component {
  @Input() parentName = '';
  myName = 'My005560Component';
}
