// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005614',
  templateUrl: './my.005614.component.html'
})
export class My005614Component {
  @Input() parentName = '';
  myName = 'My005614Component';
}
