// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005601',
  templateUrl: './my.005601.component.html'
})
export class My005601Component {
  @Input() parentName = '';
  myName = 'My005601Component';
}
