// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005649',
  templateUrl: './my.005649.component.html'
})
export class My005649Component {
  @Input() parentName = '';
  myName = 'My005649Component';
}
