// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005643',
  templateUrl: './my.005643.component.html'
})
export class My005643Component {
  @Input() parentName = '';
  myName = 'My005643Component';
}
