// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005608',
  templateUrl: './my.005608.component.html'
})
export class My005608Component {
  @Input() parentName = '';
  myName = 'My005608Component';
}
