// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005620',
  templateUrl: './my.005620.component.html'
})
export class My005620Component {
  @Input() parentName = '';
  myName = 'My005620Component';
}
