// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005623',
  templateUrl: './my.005623.component.html'
})
export class My005623Component {
  @Input() parentName = '';
  myName = 'My005623Component';
}
