// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006375',
  templateUrl: './my.006375.component.html'
})
export class My006375Component {
  @Input() parentName = '';
  myName = 'My006375Component';
}
