// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006461',
  templateUrl: './my.006461.component.html'
})
export class My006461Component {
  @Input() parentName = '';
  myName = 'My006461Component';
}
