// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006415',
  templateUrl: './my.006415.component.html'
})
export class My006415Component {
  @Input() parentName = '';
  myName = 'My006415Component';
}
