// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006447',
  templateUrl: './my.006447.component.html'
})
export class My006447Component {
  @Input() parentName = '';
  myName = 'My006447Component';
}
