// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006450',
  templateUrl: './my.006450.component.html'
})
export class My006450Component {
  @Input() parentName = '';
  myName = 'My006450Component';
}
