// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006382',
  templateUrl: './my.006382.component.html'
})
export class My006382Component {
  @Input() parentName = '';
  myName = 'My006382Component';
}
