// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006388',
  templateUrl: './my.006388.component.html'
})
export class My006388Component {
  @Input() parentName = '';
  myName = 'My006388Component';
}
