// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006404',
  templateUrl: './my.006404.component.html'
})
export class My006404Component {
  @Input() parentName = '';
  myName = 'My006404Component';
}
