// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006455',
  templateUrl: './my.006455.component.html'
})
export class My006455Component {
  @Input() parentName = '';
  myName = 'My006455Component';
}
