// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006385',
  templateUrl: './my.006385.component.html'
})
export class My006385Component {
  @Input() parentName = '';
  myName = 'My006385Component';
}
