// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006383',
  templateUrl: './my.006383.component.html'
})
export class My006383Component {
  @Input() parentName = '';
  myName = 'My006383Component';
}
