// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006374',
  templateUrl: './my.006374.component.html'
})
export class My006374Component {
  @Input() parentName = '';
  myName = 'My006374Component';
}
