// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006458',
  templateUrl: './my.006458.component.html'
})
export class My006458Component {
  @Input() parentName = '';
  myName = 'My006458Component';
}
