// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009804',
  templateUrl: './my.009804.component.html'
})
export class My009804Component {
  @Input() parentName = '';
  myName = 'My009804Component';
}
