// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009798',
  templateUrl: './my.009798.component.html'
})
export class My009798Component {
  @Input() parentName = '';
  myName = 'My009798Component';
}
