// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009847',
  templateUrl: './my.009847.component.html'
})
export class My009847Component {
  @Input() parentName = '';
  myName = 'My009847Component';
}
