// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009815',
  templateUrl: './my.009815.component.html'
})
export class My009815Component {
  @Input() parentName = '';
  myName = 'My009815Component';
}
