// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009807',
  templateUrl: './my.009807.component.html'
})
export class My009807Component {
  @Input() parentName = '';
  myName = 'My009807Component';
}
