// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009805',
  templateUrl: './my.009805.component.html'
})
export class My009805Component {
  @Input() parentName = '';
  myName = 'My009805Component';
}
