// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009852',
  templateUrl: './my.009852.component.html'
})
export class My009852Component {
  @Input() parentName = '';
  myName = 'My009852Component';
}
