// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009845',
  templateUrl: './my.009845.component.html'
})
export class My009845Component {
  @Input() parentName = '';
  myName = 'My009845Component';
}
