// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009811',
  templateUrl: './my.009811.component.html'
})
export class My009811Component {
  @Input() parentName = '';
  myName = 'My009811Component';
}
