// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009870',
  templateUrl: './my.009870.component.html'
})
export class My009870Component {
  @Input() parentName = '';
  myName = 'My009870Component';
}
