// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009888',
  templateUrl: './my.009888.component.html'
})
export class My009888Component {
  @Input() parentName = '';
  myName = 'My009888Component';
}
