// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009879',
  templateUrl: './my.009879.component.html'
})
export class My009879Component {
  @Input() parentName = '';
  myName = 'My009879Component';
}
