// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009823',
  templateUrl: './my.009823.component.html'
})
export class My009823Component {
  @Input() parentName = '';
  myName = 'My009823Component';
}
