// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009891',
  templateUrl: './my.009891.component.html'
})
export class My009891Component {
  @Input() parentName = '';
  myName = 'My009891Component';
}
