// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009824',
  templateUrl: './my.009824.component.html'
})
export class My009824Component {
  @Input() parentName = '';
  myName = 'My009824Component';
}
