// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009831',
  templateUrl: './my.009831.component.html'
})
export class My009831Component {
  @Input() parentName = '';
  myName = 'My009831Component';
}
