// Code generated by angular-stress-test
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent } from './app.component';
import { Module000000 } from './Module000000/Module000000.module';
import { Module000001 } from './Module000001/Module000001.module';
import { Module000002 } from './Module000002/Module000002.module';
import { Module000003 } from './Module000003/Module000003.module';
import { Module000004 } from './Module000004/Module000004.module';
import { Module000005 } from './Module000005/Module000005.module';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    BrowserModule,
    Module000000,
    Module000001,
    Module000002,
    Module000003,
    Module000004,
    Module000005,
],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
