// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008462',
  templateUrl: './my.008462.component.html'
})
export class My008462Component {
  @Input() parentName = '';
  myName = 'My008462Component';
}
