// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008404',
  templateUrl: './my.008404.component.html'
})
export class My008404Component {
  @Input() parentName = '';
  myName = 'My008404Component';
}
