// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008384',
  templateUrl: './my.008384.component.html'
})
export class My008384Component {
  @Input() parentName = '';
  myName = 'My008384Component';
}
