// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008392',
  templateUrl: './my.008392.component.html'
})
export class My008392Component {
  @Input() parentName = '';
  myName = 'My008392Component';
}
