// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008391',
  templateUrl: './my.008391.component.html'
})
export class My008391Component {
  @Input() parentName = '';
  myName = 'My008391Component';
}
