// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008394',
  templateUrl: './my.008394.component.html'
})
export class My008394Component {
  @Input() parentName = '';
  myName = 'My008394Component';
}
