// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008411',
  templateUrl: './my.008411.component.html'
})
export class My008411Component {
  @Input() parentName = '';
  myName = 'My008411Component';
}
