// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008483',
  templateUrl: './my.008483.component.html'
})
export class My008483Component {
  @Input() parentName = '';
  myName = 'My008483Component';
}
