// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008383',
  templateUrl: './my.008383.component.html'
})
export class My008383Component {
  @Input() parentName = '';
  myName = 'My008383Component';
}
