// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008424',
  templateUrl: './my.008424.component.html'
})
export class My008424Component {
  @Input() parentName = '';
  myName = 'My008424Component';
}
