// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008459',
  templateUrl: './my.008459.component.html'
})
export class My008459Component {
  @Input() parentName = '';
  myName = 'My008459Component';
}
