// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008442',
  templateUrl: './my.008442.component.html'
})
export class My008442Component {
  @Input() parentName = '';
  myName = 'My008442Component';
}
