// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003816',
  templateUrl: './my.003816.component.html'
})
export class My003816Component {
  @Input() parentName = '';
  myName = 'My003816Component';
}
