// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003796',
  templateUrl: './my.003796.component.html'
})
export class My003796Component {
  @Input() parentName = '';
  myName = 'My003796Component';
}
