// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003772',
  templateUrl: './my.003772.component.html'
})
export class My003772Component {
  @Input() parentName = '';
  myName = 'My003772Component';
}
