// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003818',
  templateUrl: './my.003818.component.html'
})
export class My003818Component {
  @Input() parentName = '';
  myName = 'My003818Component';
}
