// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003810',
  templateUrl: './my.003810.component.html'
})
export class My003810Component {
  @Input() parentName = '';
  myName = 'My003810Component';
}
