// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003753',
  templateUrl: './my.003753.component.html'
})
export class My003753Component {
  @Input() parentName = '';
  myName = 'My003753Component';
}
