// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003795',
  templateUrl: './my.003795.component.html'
})
export class My003795Component {
  @Input() parentName = '';
  myName = 'My003795Component';
}
