// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003832',
  templateUrl: './my.003832.component.html'
})
export class My003832Component {
  @Input() parentName = '';
  myName = 'My003832Component';
}
