// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003806',
  templateUrl: './my.003806.component.html'
})
export class My003806Component {
  @Input() parentName = '';
  myName = 'My003806Component';
}
