// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003826',
  templateUrl: './my.003826.component.html'
})
export class My003826Component {
  @Input() parentName = '';
  myName = 'My003826Component';
}
