// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003793',
  templateUrl: './my.003793.component.html'
})
export class My003793Component {
  @Input() parentName = '';
  myName = 'My003793Component';
}
