// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003780',
  templateUrl: './my.003780.component.html'
})
export class My003780Component {
  @Input() parentName = '';
  myName = 'My003780Component';
}
