// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003765',
  templateUrl: './my.003765.component.html'
})
export class My003765Component {
  @Input() parentName = '';
  myName = 'My003765Component';
}
