// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003828',
  templateUrl: './my.003828.component.html'
})
export class My003828Component {
  @Input() parentName = '';
  myName = 'My003828Component';
}
