// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003783',
  templateUrl: './my.003783.component.html'
})
export class My003783Component {
  @Input() parentName = '';
  myName = 'My003783Component';
}
