// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003787',
  templateUrl: './my.003787.component.html'
})
export class My003787Component {
  @Input() parentName = '';
  myName = 'My003787Component';
}
