// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003817',
  templateUrl: './my.003817.component.html'
})
export class My003817Component {
  @Input() parentName = '';
  myName = 'My003817Component';
}
