// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006497',
  templateUrl: './my.006497.component.html'
})
export class My006497Component {
  @Input() parentName = '';
  myName = 'My006497Component';
}
