// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006508',
  templateUrl: './my.006508.component.html'
})
export class My006508Component {
  @Input() parentName = '';
  myName = 'My006508Component';
}
