// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006513',
  templateUrl: './my.006513.component.html'
})
export class My006513Component {
  @Input() parentName = '';
  myName = 'My006513Component';
}
