// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006533',
  templateUrl: './my.006533.component.html'
})
export class My006533Component {
  @Input() parentName = '';
  myName = 'My006533Component';
}
