// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006494',
  templateUrl: './my.006494.component.html'
})
export class My006494Component {
  @Input() parentName = '';
  myName = 'My006494Component';
}
