// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006495',
  templateUrl: './my.006495.component.html'
})
export class My006495Component {
  @Input() parentName = '';
  myName = 'My006495Component';
}
