// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006496',
  templateUrl: './my.006496.component.html'
})
export class My006496Component {
  @Input() parentName = '';
  myName = 'My006496Component';
}
