// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006475',
  templateUrl: './my.006475.component.html'
})
export class My006475Component {
  @Input() parentName = '';
  myName = 'My006475Component';
}
