// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006480',
  templateUrl: './my.006480.component.html'
})
export class My006480Component {
  @Input() parentName = '';
  myName = 'My006480Component';
}
