// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006515',
  templateUrl: './my.006515.component.html'
})
export class My006515Component {
  @Input() parentName = '';
  myName = 'My006515Component';
}
