// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006511',
  templateUrl: './my.006511.component.html'
})
export class My006511Component {
  @Input() parentName = '';
  myName = 'My006511Component';
}
