// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006467',
  templateUrl: './my.006467.component.html'
})
export class My006467Component {
  @Input() parentName = '';
  myName = 'My006467Component';
}
