// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006492',
  templateUrl: './my.006492.component.html'
})
export class My006492Component {
  @Input() parentName = '';
  myName = 'My006492Component';
}
