// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006531',
  templateUrl: './my.006531.component.html'
})
export class My006531Component {
  @Input() parentName = '';
  myName = 'My006531Component';
}
