// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002733',
  templateUrl: './my.002733.component.html'
})
export class My002733Component {
  @Input() parentName = '';
  myName = 'My002733Component';
}
