// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002777',
  templateUrl: './my.002777.component.html'
})
export class My002777Component {
  @Input() parentName = '';
  myName = 'My002777Component';
}
