// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002745',
  templateUrl: './my.002745.component.html'
})
export class My002745Component {
  @Input() parentName = '';
  myName = 'My002745Component';
}
