// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002767',
  templateUrl: './my.002767.component.html'
})
export class My002767Component {
  @Input() parentName = '';
  myName = 'My002767Component';
}
