// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002735',
  templateUrl: './my.002735.component.html'
})
export class My002735Component {
  @Input() parentName = '';
  myName = 'My002735Component';
}
