// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002823',
  templateUrl: './my.002823.component.html'
})
export class My002823Component {
  @Input() parentName = '';
  myName = 'My002823Component';
}
