// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002734',
  templateUrl: './my.002734.component.html'
})
export class My002734Component {
  @Input() parentName = '';
  myName = 'My002734Component';
}
