// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002736',
  templateUrl: './my.002736.component.html'
})
export class My002736Component {
  @Input() parentName = '';
  myName = 'My002736Component';
}
