// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002814',
  templateUrl: './my.002814.component.html'
})
export class My002814Component {
  @Input() parentName = '';
  myName = 'My002814Component';
}
