// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002761',
  templateUrl: './my.002761.component.html'
})
export class My002761Component {
  @Input() parentName = '';
  myName = 'My002761Component';
}
