// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002748',
  templateUrl: './my.002748.component.html'
})
export class My002748Component {
  @Input() parentName = '';
  myName = 'My002748Component';
}
