// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002816',
  templateUrl: './my.002816.component.html'
})
export class My002816Component {
  @Input() parentName = '';
  myName = 'My002816Component';
}
