// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002815',
  templateUrl: './my.002815.component.html'
})
export class My002815Component {
  @Input() parentName = '';
  myName = 'My002815Component';
}
