// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002817',
  templateUrl: './my.002817.component.html'
})
export class My002817Component {
  @Input() parentName = '';
  myName = 'My002817Component';
}
