// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002813',
  templateUrl: './my.002813.component.html'
})
export class My002813Component {
  @Input() parentName = '';
  myName = 'My002813Component';
}
