// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002763',
  templateUrl: './my.002763.component.html'
})
export class My002763Component {
  @Input() parentName = '';
  myName = 'My002763Component';
}
