// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002751',
  templateUrl: './my.002751.component.html'
})
export class My002751Component {
  @Input() parentName = '';
  myName = 'My002751Component';
}
