// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003995',
  templateUrl: './my.003995.component.html'
})
export class My003995Component {
  @Input() parentName = '';
  myName = 'My003995Component';
}
