// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003941',
  templateUrl: './my.003941.component.html'
})
export class My003941Component {
  @Input() parentName = '';
  myName = 'My003941Component';
}
