// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003963',
  templateUrl: './my.003963.component.html'
})
export class My003963Component {
  @Input() parentName = '';
  myName = 'My003963Component';
}
