// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003981',
  templateUrl: './my.003981.component.html'
})
export class My003981Component {
  @Input() parentName = '';
  myName = 'My003981Component';
}
