// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003954',
  templateUrl: './my.003954.component.html'
})
export class My003954Component {
  @Input() parentName = '';
  myName = 'My003954Component';
}
