// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004028',
  templateUrl: './my.004028.component.html'
})
export class My004028Component {
  @Input() parentName = '';
  myName = 'My004028Component';
}
