// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004005',
  templateUrl: './my.004005.component.html'
})
export class My004005Component {
  @Input() parentName = '';
  myName = 'My004005Component';
}
