// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004013',
  templateUrl: './my.004013.component.html'
})
export class My004013Component {
  @Input() parentName = '';
  myName = 'My004013Component';
}
