// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004024',
  templateUrl: './my.004024.component.html'
})
export class My004024Component {
  @Input() parentName = '';
  myName = 'My004024Component';
}
