// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004023',
  templateUrl: './my.004023.component.html'
})
export class My004023Component {
  @Input() parentName = '';
  myName = 'My004023Component';
}
