// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003957',
  templateUrl: './my.003957.component.html'
})
export class My003957Component {
  @Input() parentName = '';
  myName = 'My003957Component';
}
