// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003943',
  templateUrl: './my.003943.component.html'
})
export class My003943Component {
  @Input() parentName = '';
  myName = 'My003943Component';
}
