// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003946',
  templateUrl: './my.003946.component.html'
})
export class My003946Component {
  @Input() parentName = '';
  myName = 'My003946Component';
}
