// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003955',
  templateUrl: './my.003955.component.html'
})
export class My003955Component {
  @Input() parentName = '';
  myName = 'My003955Component';
}
