// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003985',
  templateUrl: './my.003985.component.html'
})
export class My003985Component {
  @Input() parentName = '';
  myName = 'My003985Component';
}
