// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003973',
  templateUrl: './my.003973.component.html'
})
export class My003973Component {
  @Input() parentName = '';
  myName = 'My003973Component';
}
