// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003960',
  templateUrl: './my.003960.component.html'
})
export class My003960Component {
  @Input() parentName = '';
  myName = 'My003960Component';
}
