// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003999',
  templateUrl: './my.003999.component.html'
})
export class My003999Component {
  @Input() parentName = '';
  myName = 'My003999Component';
}
