// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003996',
  templateUrl: './my.003996.component.html'
})
export class My003996Component {
  @Input() parentName = '';
  myName = 'My003996Component';
}
