// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004017',
  templateUrl: './my.004017.component.html'
})
export class My004017Component {
  @Input() parentName = '';
  myName = 'My004017Component';
}
