// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004034',
  templateUrl: './my.004034.component.html'
})
export class My004034Component {
  @Input() parentName = '';
  myName = 'My004034Component';
}
