// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002832',
  templateUrl: './my.002832.component.html'
})
export class My002832Component {
  @Input() parentName = '';
  myName = 'My002832Component';
}
