// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002903',
  templateUrl: './my.002903.component.html'
})
export class My002903Component {
  @Input() parentName = '';
  myName = 'My002903Component';
}
