// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002869',
  templateUrl: './my.002869.component.html'
})
export class My002869Component {
  @Input() parentName = '';
  myName = 'My002869Component';
}
