// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002843',
  templateUrl: './my.002843.component.html'
})
export class My002843Component {
  @Input() parentName = '';
  myName = 'My002843Component';
}
