// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002880',
  templateUrl: './my.002880.component.html'
})
export class My002880Component {
  @Input() parentName = '';
  myName = 'My002880Component';
}
