// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002871',
  templateUrl: './my.002871.component.html'
})
export class My002871Component {
  @Input() parentName = '';
  myName = 'My002871Component';
}
