// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002924',
  templateUrl: './my.002924.component.html'
})
export class My002924Component {
  @Input() parentName = '';
  myName = 'My002924Component';
}
