// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002854',
  templateUrl: './my.002854.component.html'
})
export class My002854Component {
  @Input() parentName = '';
  myName = 'My002854Component';
}
