// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002912',
  templateUrl: './my.002912.component.html'
})
export class My002912Component {
  @Input() parentName = '';
  myName = 'My002912Component';
}
