// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002896',
  templateUrl: './my.002896.component.html'
})
export class My002896Component {
  @Input() parentName = '';
  myName = 'My002896Component';
}
