// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004063',
  templateUrl: './my.004063.component.html'
})
export class My004063Component {
  @Input() parentName = '';
  myName = 'My004063Component';
}
