// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004079',
  templateUrl: './my.004079.component.html'
})
export class My004079Component {
  @Input() parentName = '';
  myName = 'My004079Component';
}
