// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004054',
  templateUrl: './my.004054.component.html'
})
export class My004054Component {
  @Input() parentName = '';
  myName = 'My004054Component';
}
