// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004092',
  templateUrl: './my.004092.component.html'
})
export class My004092Component {
  @Input() parentName = '';
  myName = 'My004092Component';
}
