// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004065',
  templateUrl: './my.004065.component.html'
})
export class My004065Component {
  @Input() parentName = '';
  myName = 'My004065Component';
}
