// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004123',
  templateUrl: './my.004123.component.html'
})
export class My004123Component {
  @Input() parentName = '';
  myName = 'My004123Component';
}
