// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004080',
  templateUrl: './my.004080.component.html'
})
export class My004080Component {
  @Input() parentName = '';
  myName = 'My004080Component';
}
