// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004049',
  templateUrl: './my.004049.component.html'
})
export class My004049Component {
  @Input() parentName = '';
  myName = 'My004049Component';
}
