// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004137',
  templateUrl: './my.004137.component.html'
})
export class My004137Component {
  @Input() parentName = '';
  myName = 'My004137Component';
}
