// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004135',
  templateUrl: './my.004135.component.html'
})
export class My004135Component {
  @Input() parentName = '';
  myName = 'My004135Component';
}
