// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004066',
  templateUrl: './my.004066.component.html'
})
export class My004066Component {
  @Input() parentName = '';
  myName = 'My004066Component';
}
