// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004112',
  templateUrl: './my.004112.component.html'
})
export class My004112Component {
  @Input() parentName = '';
  myName = 'My004112Component';
}
