// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004072',
  templateUrl: './my.004072.component.html'
})
export class My004072Component {
  @Input() parentName = '';
  myName = 'My004072Component';
}
