// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004057',
  templateUrl: './my.004057.component.html'
})
export class My004057Component {
  @Input() parentName = '';
  myName = 'My004057Component';
}
