// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004082',
  templateUrl: './my.004082.component.html'
})
export class My004082Component {
  @Input() parentName = '';
  myName = 'My004082Component';
}
