// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004095',
  templateUrl: './my.004095.component.html'
})
export class My004095Component {
  @Input() parentName = '';
  myName = 'My004095Component';
}
