// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004133',
  templateUrl: './my.004133.component.html'
})
export class My004133Component {
  @Input() parentName = '';
  myName = 'My004133Component';
}
