// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004044',
  templateUrl: './my.004044.component.html'
})
export class My004044Component {
  @Input() parentName = '';
  myName = 'My004044Component';
}
