// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004069',
  templateUrl: './my.004069.component.html'
})
export class My004069Component {
  @Input() parentName = '';
  myName = 'My004069Component';
}
