// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-004114',
  templateUrl: './my.004114.component.html'
})
export class My004114Component {
  @Input() parentName = '';
  myName = 'My004114Component';
}
