// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005389',
  templateUrl: './my.005389.component.html'
})
export class My005389Component {
  @Input() parentName = '';
  myName = 'My005389Component';
}
