// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005358',
  templateUrl: './my.005358.component.html'
})
export class My005358Component {
  @Input() parentName = '';
  myName = 'My005358Component';
}
