// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005419',
  templateUrl: './my.005419.component.html'
})
export class My005419Component {
  @Input() parentName = '';
  myName = 'My005419Component';
}
