// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005376',
  templateUrl: './my.005376.component.html'
})
export class My005376Component {
  @Input() parentName = '';
  myName = 'My005376Component';
}
