// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005447',
  templateUrl: './my.005447.component.html'
})
export class My005447Component {
  @Input() parentName = '';
  myName = 'My005447Component';
}
