// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005381',
  templateUrl: './my.005381.component.html'
})
export class My005381Component {
  @Input() parentName = '';
  myName = 'My005381Component';
}
