// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005379',
  templateUrl: './my.005379.component.html'
})
export class My005379Component {
  @Input() parentName = '';
  myName = 'My005379Component';
}
