// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005395',
  templateUrl: './my.005395.component.html'
})
export class My005395Component {
  @Input() parentName = '';
  myName = 'My005395Component';
}
