// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005410',
  templateUrl: './my.005410.component.html'
})
export class My005410Component {
  @Input() parentName = '';
  myName = 'My005410Component';
}
