// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005429',
  templateUrl: './my.005429.component.html'
})
export class My005429Component {
  @Input() parentName = '';
  myName = 'My005429Component';
}
