// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005384',
  templateUrl: './my.005384.component.html'
})
export class My005384Component {
  @Input() parentName = '';
  myName = 'My005384Component';
}
