// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005415',
  templateUrl: './my.005415.component.html'
})
export class My005415Component {
  @Input() parentName = '';
  myName = 'My005415Component';
}
