// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005375',
  templateUrl: './my.005375.component.html'
})
export class My005375Component {
  @Input() parentName = '';
  myName = 'My005375Component';
}
