// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005438',
  templateUrl: './my.005438.component.html'
})
export class My005438Component {
  @Input() parentName = '';
  myName = 'My005438Component';
}
