// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008116',
  templateUrl: './my.008116.component.html'
})
export class My008116Component {
  @Input() parentName = '';
  myName = 'My008116Component';
}
