// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008151',
  templateUrl: './my.008151.component.html'
})
export class My008151Component {
  @Input() parentName = '';
  myName = 'My008151Component';
}
