// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008174',
  templateUrl: './my.008174.component.html'
})
export class My008174Component {
  @Input() parentName = '';
  myName = 'My008174Component';
}
