// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008129',
  templateUrl: './my.008129.component.html'
})
export class My008129Component {
  @Input() parentName = '';
  myName = 'My008129Component';
}
