// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008148',
  templateUrl: './my.008148.component.html'
})
export class My008148Component {
  @Input() parentName = '';
  myName = 'My008148Component';
}
