// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008119',
  templateUrl: './my.008119.component.html'
})
export class My008119Component {
  @Input() parentName = '';
  myName = 'My008119Component';
}
