// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008120',
  templateUrl: './my.008120.component.html'
})
export class My008120Component {
  @Input() parentName = '';
  myName = 'My008120Component';
}
