// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008086',
  templateUrl: './my.008086.component.html'
})
export class My008086Component {
  @Input() parentName = '';
  myName = 'My008086Component';
}
