// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008135',
  templateUrl: './my.008135.component.html'
})
export class My008135Component {
  @Input() parentName = '';
  myName = 'My008135Component';
}
