// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008095',
  templateUrl: './my.008095.component.html'
})
export class My008095Component {
  @Input() parentName = '';
  myName = 'My008095Component';
}
