// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002017',
  templateUrl: './my.002017.component.html'
})
export class My002017Component {
  @Input() parentName = '';
  myName = 'My002017Component';
}
