// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002019',
  templateUrl: './my.002019.component.html'
})
export class My002019Component {
  @Input() parentName = '';
  myName = 'My002019Component';
}
