// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003597',
  templateUrl: './my.003597.component.html'
})
export class My003597Component {
  @Input() parentName = '';
  myName = 'My003597Component';
}
