// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003598',
  templateUrl: './my.003598.component.html'
})
export class My003598Component {
  @Input() parentName = '';
  myName = 'My003598Component';
}
