// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003615',
  templateUrl: './my.003615.component.html'
})
export class My003615Component {
  @Input() parentName = '';
  myName = 'My003615Component';
}
