// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003610',
  templateUrl: './my.003610.component.html'
})
export class My003610Component {
  @Input() parentName = '';
  myName = 'My003610Component';
}
