// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003567',
  templateUrl: './my.003567.component.html'
})
export class My003567Component {
  @Input() parentName = '';
  myName = 'My003567Component';
}
