// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003551',
  templateUrl: './my.003551.component.html'
})
export class My003551Component {
  @Input() parentName = '';
  myName = 'My003551Component';
}
