// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003555',
  templateUrl: './my.003555.component.html'
})
export class My003555Component {
  @Input() parentName = '';
  myName = 'My003555Component';
}
