// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003559',
  templateUrl: './my.003559.component.html'
})
export class My003559Component {
  @Input() parentName = '';
  myName = 'My003559Component';
}
