// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003558',
  templateUrl: './my.003558.component.html'
})
export class My003558Component {
  @Input() parentName = '';
  myName = 'My003558Component';
}
