// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003542',
  templateUrl: './my.003542.component.html'
})
export class My003542Component {
  @Input() parentName = '';
  myName = 'My003542Component';
}
