// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003562',
  templateUrl: './my.003562.component.html'
})
export class My003562Component {
  @Input() parentName = '';
  myName = 'My003562Component';
}
