// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003604',
  templateUrl: './my.003604.component.html'
})
export class My003604Component {
  @Input() parentName = '';
  myName = 'My003604Component';
}
