// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003583',
  templateUrl: './my.003583.component.html'
})
export class My003583Component {
  @Input() parentName = '';
  myName = 'My003583Component';
}
