// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009373',
  templateUrl: './my.009373.component.html'
})
export class My009373Component {
  @Input() parentName = '';
  myName = 'My009373Component';
}
