// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009338',
  templateUrl: './my.009338.component.html'
})
export class My009338Component {
  @Input() parentName = '';
  myName = 'My009338Component';
}
