// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009386',
  templateUrl: './my.009386.component.html'
})
export class My009386Component {
  @Input() parentName = '';
  myName = 'My009386Component';
}
