// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009334',
  templateUrl: './my.009334.component.html'
})
export class My009334Component {
  @Input() parentName = '';
  myName = 'My009334Component';
}
