// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009343',
  templateUrl: './my.009343.component.html'
})
export class My009343Component {
  @Input() parentName = '';
  myName = 'My009343Component';
}
