// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009368',
  templateUrl: './my.009368.component.html'
})
export class My009368Component {
  @Input() parentName = '';
  myName = 'My009368Component';
}
