// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009347',
  templateUrl: './my.009347.component.html'
})
export class My009347Component {
  @Input() parentName = '';
  myName = 'My009347Component';
}
