// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009309',
  templateUrl: './my.009309.component.html'
})
export class My009309Component {
  @Input() parentName = '';
  myName = 'My009309Component';
}
