// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009346',
  templateUrl: './my.009346.component.html'
})
export class My009346Component {
  @Input() parentName = '';
  myName = 'My009346Component';
}
