// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009293',
  templateUrl: './my.009293.component.html'
})
export class My009293Component {
  @Input() parentName = '';
  myName = 'My009293Component';
}
