// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009357',
  templateUrl: './my.009357.component.html'
})
export class My009357Component {
  @Input() parentName = '';
  myName = 'My009357Component';
}
