// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009380',
  templateUrl: './my.009380.component.html'
})
export class My009380Component {
  @Input() parentName = '';
  myName = 'My009380Component';
}
