// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009371',
  templateUrl: './my.009371.component.html'
})
export class My009371Component {
  @Input() parentName = '';
  myName = 'My009371Component';
}
