// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009333',
  templateUrl: './my.009333.component.html'
})
export class My009333Component {
  @Input() parentName = '';
  myName = 'My009333Component';
}
