// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009340',
  templateUrl: './my.009340.component.html'
})
export class My009340Component {
  @Input() parentName = '';
  myName = 'My009340Component';
}
