// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009316',
  templateUrl: './my.009316.component.html'
})
export class My009316Component {
  @Input() parentName = '';
  myName = 'My009316Component';
}
