// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009356',
  templateUrl: './my.009356.component.html'
})
export class My009356Component {
  @Input() parentName = '';
  myName = 'My009356Component';
}
