// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009364',
  templateUrl: './my.009364.component.html'
})
export class My009364Component {
  @Input() parentName = '';
  myName = 'My009364Component';
}
