// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003223',
  templateUrl: './my.003223.component.html'
})
export class My003223Component {
  @Input() parentName = '';
  myName = 'My003223Component';
}
