// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003188',
  templateUrl: './my.003188.component.html'
})
export class My003188Component {
  @Input() parentName = '';
  myName = 'My003188Component';
}
