// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003142',
  templateUrl: './my.003142.component.html'
})
export class My003142Component {
  @Input() parentName = '';
  myName = 'My003142Component';
}
