// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003219',
  templateUrl: './my.003219.component.html'
})
export class My003219Component {
  @Input() parentName = '';
  myName = 'My003219Component';
}
