// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003159',
  templateUrl: './my.003159.component.html'
})
export class My003159Component {
  @Input() parentName = '';
  myName = 'My003159Component';
}
