// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003168',
  templateUrl: './my.003168.component.html'
})
export class My003168Component {
  @Input() parentName = '';
  myName = 'My003168Component';
}
