// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003218',
  templateUrl: './my.003218.component.html'
})
export class My003218Component {
  @Input() parentName = '';
  myName = 'My003218Component';
}
