// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003135',
  templateUrl: './my.003135.component.html'
})
export class My003135Component {
  @Input() parentName = '';
  myName = 'My003135Component';
}
