// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003214',
  templateUrl: './my.003214.component.html'
})
export class My003214Component {
  @Input() parentName = '';
  myName = 'My003214Component';
}
