// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003171',
  templateUrl: './my.003171.component.html'
})
export class My003171Component {
  @Input() parentName = '';
  myName = 'My003171Component';
}
