// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003139',
  templateUrl: './my.003139.component.html'
})
export class My003139Component {
  @Input() parentName = '';
  myName = 'My003139Component';
}
