// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003196',
  templateUrl: './my.003196.component.html'
})
export class My003196Component {
  @Input() parentName = '';
  myName = 'My003196Component';
}
