// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003216',
  templateUrl: './my.003216.component.html'
})
export class My003216Component {
  @Input() parentName = '';
  myName = 'My003216Component';
}
