// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003191',
  templateUrl: './my.003191.component.html'
})
export class My003191Component {
  @Input() parentName = '';
  myName = 'My003191Component';
}
