// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003210',
  templateUrl: './my.003210.component.html'
})
export class My003210Component {
  @Input() parentName = '';
  myName = 'My003210Component';
}
