// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003158',
  templateUrl: './my.003158.component.html'
})
export class My003158Component {
  @Input() parentName = '';
  myName = 'My003158Component';
}
