// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003145',
  templateUrl: './my.003145.component.html'
})
export class My003145Component {
  @Input() parentName = '';
  myName = 'My003145Component';
}
