// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003186',
  templateUrl: './my.003186.component.html'
})
export class My003186Component {
  @Input() parentName = '';
  myName = 'My003186Component';
}
