// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003206',
  templateUrl: './my.003206.component.html'
})
export class My003206Component {
  @Input() parentName = '';
  myName = 'My003206Component';
}
