// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007287',
  templateUrl: './my.007287.component.html'
})
export class My007287Component {
  @Input() parentName = '';
  myName = 'My007287Component';
}
