// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007333',
  templateUrl: './my.007333.component.html'
})
export class My007333Component {
  @Input() parentName = '';
  myName = 'My007333Component';
}
