// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007356',
  templateUrl: './my.007356.component.html'
})
export class My007356Component {
  @Input() parentName = '';
  myName = 'My007356Component';
}
