// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007289',
  templateUrl: './my.007289.component.html'
})
export class My007289Component {
  @Input() parentName = '';
  myName = 'My007289Component';
}
