// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007325',
  templateUrl: './my.007325.component.html'
})
export class My007325Component {
  @Input() parentName = '';
  myName = 'My007325Component';
}
