// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007360',
  templateUrl: './my.007360.component.html'
})
export class My007360Component {
  @Input() parentName = '';
  myName = 'My007360Component';
}
