// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007306',
  templateUrl: './my.007306.component.html'
})
export class My007306Component {
  @Input() parentName = '';
  myName = 'My007306Component';
}
