// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007348',
  templateUrl: './my.007348.component.html'
})
export class My007348Component {
  @Input() parentName = '';
  myName = 'My007348Component';
}
