// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007369',
  templateUrl: './my.007369.component.html'
})
export class My007369Component {
  @Input() parentName = '';
  myName = 'My007369Component';
}
