// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007353',
  templateUrl: './my.007353.component.html'
})
export class My007353Component {
  @Input() parentName = '';
  myName = 'My007353Component';
}
