// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007286',
  templateUrl: './my.007286.component.html'
})
export class My007286Component {
  @Input() parentName = '';
  myName = 'My007286Component';
}
