// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007309',
  templateUrl: './my.007309.component.html'
})
export class My007309Component {
  @Input() parentName = '';
  myName = 'My007309Component';
}
