// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007362',
  templateUrl: './my.007362.component.html'
})
export class My007362Component {
  @Input() parentName = '';
  myName = 'My007362Component';
}
