// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007320',
  templateUrl: './my.007320.component.html'
})
export class My007320Component {
  @Input() parentName = '';
  myName = 'My007320Component';
}
