// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007336',
  templateUrl: './my.007336.component.html'
})
export class My007336Component {
  @Input() parentName = '';
  myName = 'My007336Component';
}
