// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007355',
  templateUrl: './my.007355.component.html'
})
export class My007355Component {
  @Input() parentName = '';
  myName = 'My007355Component';
}
