// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006276',
  templateUrl: './my.006276.component.html'
})
export class My006276Component {
  @Input() parentName = '';
  myName = 'My006276Component';
}
