// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006270',
  templateUrl: './my.006270.component.html'
})
export class My006270Component {
  @Input() parentName = '';
  myName = 'My006270Component';
}
