// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006326',
  templateUrl: './my.006326.component.html'
})
export class My006326Component {
  @Input() parentName = '';
  myName = 'My006326Component';
}
