// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006358',
  templateUrl: './my.006358.component.html'
})
export class My006358Component {
  @Input() parentName = '';
  myName = 'My006358Component';
}
