// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006292',
  templateUrl: './my.006292.component.html'
})
export class My006292Component {
  @Input() parentName = '';
  myName = 'My006292Component';
}
