// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006301',
  templateUrl: './my.006301.component.html'
})
export class My006301Component {
  @Input() parentName = '';
  myName = 'My006301Component';
}
