// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006340',
  templateUrl: './my.006340.component.html'
})
export class My006340Component {
  @Input() parentName = '';
  myName = 'My006340Component';
}
