// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006323',
  templateUrl: './my.006323.component.html'
})
export class My006323Component {
  @Input() parentName = '';
  myName = 'My006323Component';
}
