// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006308',
  templateUrl: './my.006308.component.html'
})
export class My006308Component {
  @Input() parentName = '';
  myName = 'My006308Component';
}
