// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006318',
  templateUrl: './my.006318.component.html'
})
export class My006318Component {
  @Input() parentName = '';
  myName = 'My006318Component';
}
