// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006324',
  templateUrl: './my.006324.component.html'
})
export class My006324Component {
  @Input() parentName = '';
  myName = 'My006324Component';
}
