// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006268',
  templateUrl: './my.006268.component.html'
})
export class My006268Component {
  @Input() parentName = '';
  myName = 'My006268Component';
}
