// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006281',
  templateUrl: './my.006281.component.html'
})
export class My006281Component {
  @Input() parentName = '';
  myName = 'My006281Component';
}
