// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-006361',
  templateUrl: './my.006361.component.html'
})
export class My006361Component {
  @Input() parentName = '';
  myName = 'My006361Component';
}
