// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002388',
  templateUrl: './my.002388.component.html'
})
export class My002388Component {
  @Input() parentName = '';
  myName = 'My002388Component';
}
