// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002345',
  templateUrl: './my.002345.component.html'
})
export class My002345Component {
  @Input() parentName = '';
  myName = 'My002345Component';
}
