// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002397',
  templateUrl: './my.002397.component.html'
})
export class My002397Component {
  @Input() parentName = '';
  myName = 'My002397Component';
}
