// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002347',
  templateUrl: './my.002347.component.html'
})
export class My002347Component {
  @Input() parentName = '';
  myName = 'My002347Component';
}
