// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002395',
  templateUrl: './my.002395.component.html'
})
export class My002395Component {
  @Input() parentName = '';
  myName = 'My002395Component';
}
