// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002350',
  templateUrl: './my.002350.component.html'
})
export class My002350Component {
  @Input() parentName = '';
  myName = 'My002350Component';
}
