// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002403',
  templateUrl: './my.002403.component.html'
})
export class My002403Component {
  @Input() parentName = '';
  myName = 'My002403Component';
}
