// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002327',
  templateUrl: './my.002327.component.html'
})
export class My002327Component {
  @Input() parentName = '';
  myName = 'My002327Component';
}
