// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002351',
  templateUrl: './my.002351.component.html'
})
export class My002351Component {
  @Input() parentName = '';
  myName = 'My002351Component';
}
