// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002358',
  templateUrl: './my.002358.component.html'
})
export class My002358Component {
  @Input() parentName = '';
  myName = 'My002358Component';
}
