// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002417',
  templateUrl: './my.002417.component.html'
})
export class My002417Component {
  @Input() parentName = '';
  myName = 'My002417Component';
}
