// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002369',
  templateUrl: './my.002369.component.html'
})
export class My002369Component {
  @Input() parentName = '';
  myName = 'My002369Component';
}
