// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002362',
  templateUrl: './my.002362.component.html'
})
export class My002362Component {
  @Input() parentName = '';
  myName = 'My002362Component';
}
