// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001212Component } from './my.001212.component';
import { My001213Component } from './my.001213.component';
import { My001214Component } from './my.001214.component';
import { My001215Component } from './my.001215.component';
import { My001216Component } from './my.001216.component';
import { My001217Component } from './my.001217.component';
import { My001218Component } from './my.001218.component';
import { My001219Component } from './my.001219.component';
import { My001220Component } from './my.001220.component';
import { My001221Component } from './my.001221.component';
import { My001222Component } from './my.001222.component';
import { My001223Component } from './my.001223.component';
import { My001224Component } from './my.001224.component';
import { My001225Component } from './my.001225.component';
import { My001226Component } from './my.001226.component';
import { My001227Component } from './my.001227.component';
import { My001228Component } from './my.001228.component';
import { My001229Component } from './my.001229.component';
import { My001230Component } from './my.001230.component';
import { My001231Component } from './my.001231.component';
import { My001232Component } from './my.001232.component';
import { My001233Component } from './my.001233.component';
import { My001234Component } from './my.001234.component';
import { My001235Component } from './my.001235.component';
import { My001236Component } from './my.001236.component';
import { My001237Component } from './my.001237.component';
import { My001238Component } from './my.001238.component';
import { My001239Component } from './my.001239.component';
import { My001240Component } from './my.001240.component';
import { My001241Component } from './my.001241.component';
import { My001242Component } from './my.001242.component';
import { My001243Component } from './my.001243.component';
import { My001244Component } from './my.001244.component';
import { My001245Component } from './my.001245.component';
import { My001246Component } from './my.001246.component';
import { My001247Component } from './my.001247.component';
import { My001248Component } from './my.001248.component';
import { My001249Component } from './my.001249.component';
import { My001250Component } from './my.001250.component';
import { My001251Component } from './my.001251.component';
import { My001252Component } from './my.001252.component';
import { My001253Component } from './my.001253.component';
import { My001254Component } from './my.001254.component';
import { My001255Component } from './my.001255.component';
import { My001256Component } from './my.001256.component';
import { My001257Component } from './my.001257.component';
import { My001258Component } from './my.001258.component';
import { My001259Component } from './my.001259.component';
import { My001260Component } from './my.001260.component';
import { My001261Component } from './my.001261.component';
import { My001262Component } from './my.001262.component';
import { My001263Component } from './my.001263.component';
import { My001264Component } from './my.001264.component';
import { My001265Component } from './my.001265.component';
import { My001266Component } from './my.001266.component';
import { My001267Component } from './my.001267.component';
import { My001268Component } from './my.001268.component';
import { My001269Component } from './my.001269.component';
import { My001270Component } from './my.001270.component';
import { My001271Component } from './my.001271.component';
import { My001272Component } from './my.001272.component';
import { My001273Component } from './my.001273.component';
import { My001274Component } from './my.001274.component';
import { My001275Component } from './my.001275.component';
import { My001276Component } from './my.001276.component';
import { My001277Component } from './my.001277.component';
import { My001278Component } from './my.001278.component';
import { My001279Component } from './my.001279.component';
import { My001280Component } from './my.001280.component';
import { My001281Component } from './my.001281.component';
import { My001282Component } from './my.001282.component';
import { My001283Component } from './my.001283.component';
import { My001284Component } from './my.001284.component';
import { My001285Component } from './my.001285.component';
import { My001286Component } from './my.001286.component';
import { My001287Component } from './my.001287.component';
import { My001288Component } from './my.001288.component';
import { My001289Component } from './my.001289.component';
import { My001290Component } from './my.001290.component';
import { My001291Component } from './my.001291.component';
import { My001292Component } from './my.001292.component';
import { My001293Component } from './my.001293.component';
import { My001294Component } from './my.001294.component';
import { My001295Component } from './my.001295.component';
import { My001296Component } from './my.001296.component';
import { My001297Component } from './my.001297.component';
import { My001298Component } from './my.001298.component';
import { My001299Component } from './my.001299.component';
import { My001300Component } from './my.001300.component';
import { My001301Component } from './my.001301.component';
import { My001302Component } from './my.001302.component';
import { My001303Component } from './my.001303.component';
import { My001304Component } from './my.001304.component';
import { My001305Component } from './my.001305.component';
import { My001306Component } from './my.001306.component';
import { My001307Component } from './my.001307.component';
import { My001308Component } from './my.001308.component';
import { My001309Component } from './my.001309.component';
import { My001310Component } from './my.001310.component';
import { My001311Component } from './my.001311.component';
import { My001312Component } from './my.001312.component';

@NgModule({
  declarations: [
    My001212Component,
    My001213Component,
    My001214Component,
    My001215Component,
    My001216Component,
    My001217Component,
    My001218Component,
    My001219Component,
    My001220Component,
    My001221Component,
    My001222Component,
    My001223Component,
    My001224Component,
    My001225Component,
    My001226Component,
    My001227Component,
    My001228Component,
    My001229Component,
    My001230Component,
    My001231Component,
    My001232Component,
    My001233Component,
    My001234Component,
    My001235Component,
    My001236Component,
    My001237Component,
    My001238Component,
    My001239Component,
    My001240Component,
    My001241Component,
    My001242Component,
    My001243Component,
    My001244Component,
    My001245Component,
    My001246Component,
    My001247Component,
    My001248Component,
    My001249Component,
    My001250Component,
    My001251Component,
    My001252Component,
    My001253Component,
    My001254Component,
    My001255Component,
    My001256Component,
    My001257Component,
    My001258Component,
    My001259Component,
    My001260Component,
    My001261Component,
    My001262Component,
    My001263Component,
    My001264Component,
    My001265Component,
    My001266Component,
    My001267Component,
    My001268Component,
    My001269Component,
    My001270Component,
    My001271Component,
    My001272Component,
    My001273Component,
    My001274Component,
    My001275Component,
    My001276Component,
    My001277Component,
    My001278Component,
    My001279Component,
    My001280Component,
    My001281Component,
    My001282Component,
    My001283Component,
    My001284Component,
    My001285Component,
    My001286Component,
    My001287Component,
    My001288Component,
    My001289Component,
    My001290Component,
    My001291Component,
    My001292Component,
    My001293Component,
    My001294Component,
    My001295Component,
    My001296Component,
    My001297Component,
    My001298Component,
    My001299Component,
    My001300Component,
    My001301Component,
    My001302Component,
    My001303Component,
    My001304Component,
    My001305Component,
    My001306Component,
    My001307Component,
    My001308Component,
    My001309Component,
    My001310Component,
    My001311Component,
    My001312Component,
  ],
  imports: [CommonModule],
  exports: [
    My001212Component,
  ]
})
export class Module000012 { }
