// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005908',
  templateUrl: './my.005908.component.html'
})
export class My005908Component {
  @Input() parentName = '';
  myName = 'My005908Component';
}
