// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005938',
  templateUrl: './my.005938.component.html'
})
export class My005938Component {
  @Input() parentName = '';
  myName = 'My005938Component';
}
