// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005935',
  templateUrl: './my.005935.component.html'
})
export class My005935Component {
  @Input() parentName = '';
  myName = 'My005935Component';
}
