// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005865',
  templateUrl: './my.005865.component.html'
})
export class My005865Component {
  @Input() parentName = '';
  myName = 'My005865Component';
}
