// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005898',
  templateUrl: './my.005898.component.html'
})
export class My005898Component {
  @Input() parentName = '';
  myName = 'My005898Component';
}
