// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005915',
  templateUrl: './my.005915.component.html'
})
export class My005915Component {
  @Input() parentName = '';
  myName = 'My005915Component';
}
