// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005937',
  templateUrl: './my.005937.component.html'
})
export class My005937Component {
  @Input() parentName = '';
  myName = 'My005937Component';
}
