// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005929',
  templateUrl: './my.005929.component.html'
})
export class My005929Component {
  @Input() parentName = '';
  myName = 'My005929Component';
}
