// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005954',
  templateUrl: './my.005954.component.html'
})
export class My005954Component {
  @Input() parentName = '';
  myName = 'My005954Component';
}
