// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005910',
  templateUrl: './my.005910.component.html'
})
export class My005910Component {
  @Input() parentName = '';
  myName = 'My005910Component';
}
