// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005888',
  templateUrl: './my.005888.component.html'
})
export class My005888Component {
  @Input() parentName = '';
  myName = 'My005888Component';
}
