// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005933',
  templateUrl: './my.005933.component.html'
})
export class My005933Component {
  @Input() parentName = '';
  myName = 'My005933Component';
}
