// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005912',
  templateUrl: './my.005912.component.html'
})
export class My005912Component {
  @Input() parentName = '';
  myName = 'My005912Component';
}
