// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000505Component } from './my.000505.component';
import { My000506Component } from './my.000506.component';
import { My000507Component } from './my.000507.component';
import { My000508Component } from './my.000508.component';
import { My000509Component } from './my.000509.component';
import { My000510Component } from './my.000510.component';
import { My000511Component } from './my.000511.component';
import { My000512Component } from './my.000512.component';
import { My000513Component } from './my.000513.component';
import { My000514Component } from './my.000514.component';
import { My000515Component } from './my.000515.component';
import { My000516Component } from './my.000516.component';
import { My000517Component } from './my.000517.component';
import { My000518Component } from './my.000518.component';
import { My000519Component } from './my.000519.component';
import { My000520Component } from './my.000520.component';
import { My000521Component } from './my.000521.component';
import { My000522Component } from './my.000522.component';
import { My000523Component } from './my.000523.component';
import { My000524Component } from './my.000524.component';
import { My000525Component } from './my.000525.component';
import { My000526Component } from './my.000526.component';
import { My000527Component } from './my.000527.component';
import { My000528Component } from './my.000528.component';
import { My000529Component } from './my.000529.component';
import { My000530Component } from './my.000530.component';
import { My000531Component } from './my.000531.component';
import { My000532Component } from './my.000532.component';
import { My000533Component } from './my.000533.component';
import { My000534Component } from './my.000534.component';
import { My000535Component } from './my.000535.component';
import { My000536Component } from './my.000536.component';
import { My000537Component } from './my.000537.component';
import { My000538Component } from './my.000538.component';
import { My000539Component } from './my.000539.component';
import { My000540Component } from './my.000540.component';
import { My000541Component } from './my.000541.component';
import { My000542Component } from './my.000542.component';
import { My000543Component } from './my.000543.component';
import { My000544Component } from './my.000544.component';
import { My000545Component } from './my.000545.component';
import { My000546Component } from './my.000546.component';
import { My000547Component } from './my.000547.component';
import { My000548Component } from './my.000548.component';
import { My000549Component } from './my.000549.component';
import { My000550Component } from './my.000550.component';
import { My000551Component } from './my.000551.component';
import { My000552Component } from './my.000552.component';
import { My000553Component } from './my.000553.component';
import { My000554Component } from './my.000554.component';
import { My000555Component } from './my.000555.component';
import { My000556Component } from './my.000556.component';
import { My000557Component } from './my.000557.component';
import { My000558Component } from './my.000558.component';
import { My000559Component } from './my.000559.component';
import { My000560Component } from './my.000560.component';
import { My000561Component } from './my.000561.component';
import { My000562Component } from './my.000562.component';
import { My000563Component } from './my.000563.component';
import { My000564Component } from './my.000564.component';
import { My000565Component } from './my.000565.component';
import { My000566Component } from './my.000566.component';
import { My000567Component } from './my.000567.component';
import { My000568Component } from './my.000568.component';
import { My000569Component } from './my.000569.component';
import { My000570Component } from './my.000570.component';
import { My000571Component } from './my.000571.component';
import { My000572Component } from './my.000572.component';
import { My000573Component } from './my.000573.component';
import { My000574Component } from './my.000574.component';
import { My000575Component } from './my.000575.component';
import { My000576Component } from './my.000576.component';
import { My000577Component } from './my.000577.component';
import { My000578Component } from './my.000578.component';
import { My000579Component } from './my.000579.component';
import { My000580Component } from './my.000580.component';
import { My000581Component } from './my.000581.component';
import { My000582Component } from './my.000582.component';
import { My000583Component } from './my.000583.component';
import { My000584Component } from './my.000584.component';
import { My000585Component } from './my.000585.component';
import { My000586Component } from './my.000586.component';
import { My000587Component } from './my.000587.component';
import { My000588Component } from './my.000588.component';
import { My000589Component } from './my.000589.component';
import { My000590Component } from './my.000590.component';
import { My000591Component } from './my.000591.component';
import { My000592Component } from './my.000592.component';
import { My000593Component } from './my.000593.component';
import { My000594Component } from './my.000594.component';
import { My000595Component } from './my.000595.component';
import { My000596Component } from './my.000596.component';
import { My000597Component } from './my.000597.component';
import { My000598Component } from './my.000598.component';
import { My000599Component } from './my.000599.component';
import { My000600Component } from './my.000600.component';
import { My000601Component } from './my.000601.component';
import { My000602Component } from './my.000602.component';
import { My000603Component } from './my.000603.component';
import { My000604Component } from './my.000604.component';
import { My000605Component } from './my.000605.component';

@NgModule({
  declarations: [
    My000505Component,
    My000506Component,
    My000507Component,
    My000508Component,
    My000509Component,
    My000510Component,
    My000511Component,
    My000512Component,
    My000513Component,
    My000514Component,
    My000515Component,
    My000516Component,
    My000517Component,
    My000518Component,
    My000519Component,
    My000520Component,
    My000521Component,
    My000522Component,
    My000523Component,
    My000524Component,
    My000525Component,
    My000526Component,
    My000527Component,
    My000528Component,
    My000529Component,
    My000530Component,
    My000531Component,
    My000532Component,
    My000533Component,
    My000534Component,
    My000535Component,
    My000536Component,
    My000537Component,
    My000538Component,
    My000539Component,
    My000540Component,
    My000541Component,
    My000542Component,
    My000543Component,
    My000544Component,
    My000545Component,
    My000546Component,
    My000547Component,
    My000548Component,
    My000549Component,
    My000550Component,
    My000551Component,
    My000552Component,
    My000553Component,
    My000554Component,
    My000555Component,
    My000556Component,
    My000557Component,
    My000558Component,
    My000559Component,
    My000560Component,
    My000561Component,
    My000562Component,
    My000563Component,
    My000564Component,
    My000565Component,
    My000566Component,
    My000567Component,
    My000568Component,
    My000569Component,
    My000570Component,
    My000571Component,
    My000572Component,
    My000573Component,
    My000574Component,
    My000575Component,
    My000576Component,
    My000577Component,
    My000578Component,
    My000579Component,
    My000580Component,
    My000581Component,
    My000582Component,
    My000583Component,
    My000584Component,
    My000585Component,
    My000586Component,
    My000587Component,
    My000588Component,
    My000589Component,
    My000590Component,
    My000591Component,
    My000592Component,
    My000593Component,
    My000594Component,
    My000595Component,
    My000596Component,
    My000597Component,
    My000598Component,
    My000599Component,
    My000600Component,
    My000601Component,
    My000602Component,
    My000603Component,
    My000604Component,
    My000605Component,
  ],
  imports: [CommonModule],
  exports: [
    My000505Component,
  ]
})
export class Module000005 { }
