// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000042Component } from './my.000042.component';
import { My000043Component } from './my.000043.component';
import { My000044Component } from './my.000044.component';
import { My000045Component } from './my.000045.component';
import { My000046Component } from './my.000046.component';
import { My000047Component } from './my.000047.component';
import { My000048Component } from './my.000048.component';
import { My000049Component } from './my.000049.component';
import { My000050Component } from './my.000050.component';
import { My000051Component } from './my.000051.component';
import { My000052Component } from './my.000052.component';
import { My000053Component } from './my.000053.component';
import { My000054Component } from './my.000054.component';
import { My000055Component } from './my.000055.component';
import { My000056Component } from './my.000056.component';
import { My000057Component } from './my.000057.component';
import { My000058Component } from './my.000058.component';
import { My000059Component } from './my.000059.component';
import { My000060Component } from './my.000060.component';
import { My000061Component } from './my.000061.component';
import { My000062Component } from './my.000062.component';

@NgModule({
  declarations: [
    My000042Component,
    My000043Component,
    My000044Component,
    My000045Component,
    My000046Component,
    My000047Component,
    My000048Component,
    My000049Component,
    My000050Component,
    My000051Component,
    My000052Component,
    My000053Component,
    My000054Component,
    My000055Component,
    My000056Component,
    My000057Component,
    My000058Component,
    My000059Component,
    My000060Component,
    My000061Component,
    My000062Component,
  ],
  imports: [CommonModule],
  exports: [
    My000042Component,
  ]
})
export class Module000002 { }
