// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009180',
  templateUrl: './my.009180.component.html'
})
export class My009180Component {
  @Input() parentName = '';
  myName = 'My009180Component';
}
