// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009152',
  templateUrl: './my.009152.component.html'
})
export class My009152Component {
  @Input() parentName = '';
  myName = 'My009152Component';
}
