// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009122',
  templateUrl: './my.009122.component.html'
})
export class My009122Component {
  @Input() parentName = '';
  myName = 'My009122Component';
}
