// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009155',
  templateUrl: './my.009155.component.html'
})
export class My009155Component {
  @Input() parentName = '';
  myName = 'My009155Component';
}
