// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009141',
  templateUrl: './my.009141.component.html'
})
export class My009141Component {
  @Input() parentName = '';
  myName = 'My009141Component';
}
