// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009093',
  templateUrl: './my.009093.component.html'
})
export class My009093Component {
  @Input() parentName = '';
  myName = 'My009093Component';
}
