// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009095',
  templateUrl: './my.009095.component.html'
})
export class My009095Component {
  @Input() parentName = '';
  myName = 'My009095Component';
}
