// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009146',
  templateUrl: './my.009146.component.html'
})
export class My009146Component {
  @Input() parentName = '';
  myName = 'My009146Component';
}
