// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009924',
  templateUrl: './my.009924.component.html'
})
export class My009924Component {
  @Input() parentName = '';
  myName = 'My009924Component';
}
