// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009911',
  templateUrl: './my.009911.component.html'
})
export class My009911Component {
  @Input() parentName = '';
  myName = 'My009911Component';
}
