// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009900',
  templateUrl: './my.009900.component.html'
})
export class My009900Component {
  @Input() parentName = '';
  myName = 'My009900Component';
}
