// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009917',
  templateUrl: './my.009917.component.html'
})
export class My009917Component {
  @Input() parentName = '';
  myName = 'My009917Component';
}
