// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009938',
  templateUrl: './my.009938.component.html'
})
export class My009938Component {
  @Input() parentName = '';
  myName = 'My009938Component';
}
