// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009982',
  templateUrl: './my.009982.component.html'
})
export class My009982Component {
  @Input() parentName = '';
  myName = 'My009982Component';
}
