// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009985',
  templateUrl: './my.009985.component.html'
})
export class My009985Component {
  @Input() parentName = '';
  myName = 'My009985Component';
}
