// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009945',
  templateUrl: './my.009945.component.html'
})
export class My009945Component {
  @Input() parentName = '';
  myName = 'My009945Component';
}
