// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009898',
  templateUrl: './my.009898.component.html'
})
export class My009898Component {
  @Input() parentName = '';
  myName = 'My009898Component';
}
