// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009919',
  templateUrl: './my.009919.component.html'
})
export class My009919Component {
  @Input() parentName = '';
  myName = 'My009919Component';
}
