// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009968',
  templateUrl: './my.009968.component.html'
})
export class My009968Component {
  @Input() parentName = '';
  myName = 'My009968Component';
}
