// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009901',
  templateUrl: './my.009901.component.html'
})
export class My009901Component {
  @Input() parentName = '';
  myName = 'My009901Component';
}
