// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009986',
  templateUrl: './my.009986.component.html'
})
export class My009986Component {
  @Input() parentName = '';
  myName = 'My009986Component';
}
