// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009942',
  templateUrl: './my.009942.component.html'
})
export class My009942Component {
  @Input() parentName = '';
  myName = 'My009942Component';
}
