// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009908',
  templateUrl: './my.009908.component.html'
})
export class My009908Component {
  @Input() parentName = '';
  myName = 'My009908Component';
}
