// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009971',
  templateUrl: './my.009971.component.html'
})
export class My009971Component {
  @Input() parentName = '';
  myName = 'My009971Component';
}
