// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009988',
  templateUrl: './my.009988.component.html'
})
export class My009988Component {
  @Input() parentName = '';
  myName = 'My009988Component';
}
