// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009906',
  templateUrl: './my.009906.component.html'
})
export class My009906Component {
  @Input() parentName = '';
  myName = 'My009906Component';
}
