// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007155',
  templateUrl: './my.007155.component.html'
})
export class My007155Component {
  @Input() parentName = '';
  myName = 'My007155Component';
}
