// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007121',
  templateUrl: './my.007121.component.html'
})
export class My007121Component {
  @Input() parentName = '';
  myName = 'My007121Component';
}
