// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007091',
  templateUrl: './my.007091.component.html'
})
export class My007091Component {
  @Input() parentName = '';
  myName = 'My007091Component';
}
