// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007150',
  templateUrl: './my.007150.component.html'
})
export class My007150Component {
  @Input() parentName = '';
  myName = 'My007150Component';
}
