// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007071',
  templateUrl: './my.007071.component.html'
})
export class My007071Component {
  @Input() parentName = '';
  myName = 'My007071Component';
}
