// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007080',
  templateUrl: './my.007080.component.html'
})
export class My007080Component {
  @Input() parentName = '';
  myName = 'My007080Component';
}
