// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007169',
  templateUrl: './my.007169.component.html'
})
export class My007169Component {
  @Input() parentName = '';
  myName = 'My007169Component';
}
