// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007105',
  templateUrl: './my.007105.component.html'
})
export class My007105Component {
  @Input() parentName = '';
  myName = 'My007105Component';
}
