// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007159',
  templateUrl: './my.007159.component.html'
})
export class My007159Component {
  @Input() parentName = '';
  myName = 'My007159Component';
}
