// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007098',
  templateUrl: './my.007098.component.html'
})
export class My007098Component {
  @Input() parentName = '';
  myName = 'My007098Component';
}
