// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007108',
  templateUrl: './my.007108.component.html'
})
export class My007108Component {
  @Input() parentName = '';
  myName = 'My007108Component';
}
