// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007165',
  templateUrl: './my.007165.component.html'
})
export class My007165Component {
  @Input() parentName = '';
  myName = 'My007165Component';
}
