// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007136',
  templateUrl: './my.007136.component.html'
})
export class My007136Component {
  @Input() parentName = '';
  myName = 'My007136Component';
}
