// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007132',
  templateUrl: './my.007132.component.html'
})
export class My007132Component {
  @Input() parentName = '';
  myName = 'My007132Component';
}
