// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007979',
  templateUrl: './my.007979.component.html'
})
export class My007979Component {
  @Input() parentName = '';
  myName = 'My007979Component';
}
