// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008040',
  templateUrl: './my.008040.component.html'
})
export class My008040Component {
  @Input() parentName = '';
  myName = 'My008040Component';
}
