// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008051',
  templateUrl: './my.008051.component.html'
})
export class My008051Component {
  @Input() parentName = '';
  myName = 'My008051Component';
}
