// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008008',
  templateUrl: './my.008008.component.html'
})
export class My008008Component {
  @Input() parentName = '';
  myName = 'My008008Component';
}
