// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008006',
  templateUrl: './my.008006.component.html'
})
export class My008006Component {
  @Input() parentName = '';
  myName = 'My008006Component';
}
