// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008014',
  templateUrl: './my.008014.component.html'
})
export class My008014Component {
  @Input() parentName = '';
  myName = 'My008014Component';
}
