// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007996',
  templateUrl: './my.007996.component.html'
})
export class My007996Component {
  @Input() parentName = '';
  myName = 'My007996Component';
}
