// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008066',
  templateUrl: './my.008066.component.html'
})
export class My008066Component {
  @Input() parentName = '';
  myName = 'My008066Component';
}
