// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008043',
  templateUrl: './my.008043.component.html'
})
export class My008043Component {
  @Input() parentName = '';
  myName = 'My008043Component';
}
