// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008056',
  templateUrl: './my.008056.component.html'
})
export class My008056Component {
  @Input() parentName = '';
  myName = 'My008056Component';
}
