// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008030',
  templateUrl: './my.008030.component.html'
})
export class My008030Component {
  @Input() parentName = '';
  myName = 'My008030Component';
}
