// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007993',
  templateUrl: './my.007993.component.html'
})
export class My007993Component {
  @Input() parentName = '';
  myName = 'My007993Component';
}
