// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008044',
  templateUrl: './my.008044.component.html'
})
export class My008044Component {
  @Input() parentName = '';
  myName = 'My008044Component';
}
