// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008061',
  templateUrl: './my.008061.component.html'
})
export class My008061Component {
  @Input() parentName = '';
  myName = 'My008061Component';
}
