// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008017',
  templateUrl: './my.008017.component.html'
})
export class My008017Component {
  @Input() parentName = '';
  myName = 'My008017Component';
}
