// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008054',
  templateUrl: './my.008054.component.html'
})
export class My008054Component {
  @Input() parentName = '';
  myName = 'My008054Component';
}
