// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007994',
  templateUrl: './my.007994.component.html'
})
export class My007994Component {
  @Input() parentName = '';
  myName = 'My007994Component';
}
