// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008060',
  templateUrl: './my.008060.component.html'
})
export class My008060Component {
  @Input() parentName = '';
  myName = 'My008060Component';
}
