// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008035',
  templateUrl: './my.008035.component.html'
})
export class My008035Component {
  @Input() parentName = '';
  myName = 'My008035Component';
}
