// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008070',
  templateUrl: './my.008070.component.html'
})
export class My008070Component {
  @Input() parentName = '';
  myName = 'My008070Component';
}
