// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008023',
  templateUrl: './my.008023.component.html'
})
export class My008023Component {
  @Input() parentName = '';
  myName = 'My008023Component';
}
