// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009247',
  templateUrl: './my.009247.component.html'
})
export class My009247Component {
  @Input() parentName = '';
  myName = 'My009247Component';
}
