// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009217',
  templateUrl: './my.009217.component.html'
})
export class My009217Component {
  @Input() parentName = '';
  myName = 'My009217Component';
}
