// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009284',
  templateUrl: './my.009284.component.html'
})
export class My009284Component {
  @Input() parentName = '';
  myName = 'My009284Component';
}
