// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009226',
  templateUrl: './my.009226.component.html'
})
export class My009226Component {
  @Input() parentName = '';
  myName = 'My009226Component';
}
