// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009232',
  templateUrl: './my.009232.component.html'
})
export class My009232Component {
  @Input() parentName = '';
  myName = 'My009232Component';
}
