// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009285',
  templateUrl: './my.009285.component.html'
})
export class My009285Component {
  @Input() parentName = '';
  myName = 'My009285Component';
}
