// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009199',
  templateUrl: './my.009199.component.html'
})
export class My009199Component {
  @Input() parentName = '';
  myName = 'My009199Component';
}
