// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009282',
  templateUrl: './my.009282.component.html'
})
export class My009282Component {
  @Input() parentName = '';
  myName = 'My009282Component';
}
