// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009283',
  templateUrl: './my.009283.component.html'
})
export class My009283Component {
  @Input() parentName = '';
  myName = 'My009283Component';
}
