// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009268',
  templateUrl: './my.009268.component.html'
})
export class My009268Component {
  @Input() parentName = '';
  myName = 'My009268Component';
}
