// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009198',
  templateUrl: './my.009198.component.html'
})
export class My009198Component {
  @Input() parentName = '';
  myName = 'My009198Component';
}
