// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009257',
  templateUrl: './my.009257.component.html'
})
export class My009257Component {
  @Input() parentName = '';
  myName = 'My009257Component';
}
