// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000357Component } from './my.000357.component';
import { My000358Component } from './my.000358.component';
import { My000359Component } from './my.000359.component';
import { My000360Component } from './my.000360.component';
import { My000361Component } from './my.000361.component';
import { My000362Component } from './my.000362.component';
import { My000363Component } from './my.000363.component';
import { My000364Component } from './my.000364.component';
import { My000365Component } from './my.000365.component';
import { My000366Component } from './my.000366.component';
import { My000367Component } from './my.000367.component';
import { My000368Component } from './my.000368.component';
import { My000369Component } from './my.000369.component';
import { My000370Component } from './my.000370.component';
import { My000371Component } from './my.000371.component';
import { My000372Component } from './my.000372.component';
import { My000373Component } from './my.000373.component';
import { My000374Component } from './my.000374.component';
import { My000375Component } from './my.000375.component';
import { My000376Component } from './my.000376.component';
import { My000377Component } from './my.000377.component';

@NgModule({
  declarations: [
    My000357Component,
    My000358Component,
    My000359Component,
    My000360Component,
    My000361Component,
    My000362Component,
    My000363Component,
    My000364Component,
    My000365Component,
    My000366Component,
    My000367Component,
    My000368Component,
    My000369Component,
    My000370Component,
    My000371Component,
    My000372Component,
    My000373Component,
    My000374Component,
    My000375Component,
    My000376Component,
    My000377Component,
  ],
  imports: [CommonModule],
  exports: [
    My000357Component,
  ]
})
export class Module000017 { }
