// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008248',
  templateUrl: './my.008248.component.html'
})
export class My008248Component {
  @Input() parentName = '';
  myName = 'My008248Component';
}
