// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008264',
  templateUrl: './my.008264.component.html'
})
export class My008264Component {
  @Input() parentName = '';
  myName = 'My008264Component';
}
