// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008280',
  templateUrl: './my.008280.component.html'
})
export class My008280Component {
  @Input() parentName = '';
  myName = 'My008280Component';
}
