// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008204',
  templateUrl: './my.008204.component.html'
})
export class My008204Component {
  @Input() parentName = '';
  myName = 'My008204Component';
}
