// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008193',
  templateUrl: './my.008193.component.html'
})
export class My008193Component {
  @Input() parentName = '';
  myName = 'My008193Component';
}
