// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008247',
  templateUrl: './my.008247.component.html'
})
export class My008247Component {
  @Input() parentName = '';
  myName = 'My008247Component';
}
