// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008250',
  templateUrl: './my.008250.component.html'
})
export class My008250Component {
  @Input() parentName = '';
  myName = 'My008250Component';
}
