// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008195',
  templateUrl: './my.008195.component.html'
})
export class My008195Component {
  @Input() parentName = '';
  myName = 'My008195Component';
}
