// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008190',
  templateUrl: './my.008190.component.html'
})
export class My008190Component {
  @Input() parentName = '';
  myName = 'My008190Component';
}
