// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008205',
  templateUrl: './my.008205.component.html'
})
export class My008205Component {
  @Input() parentName = '';
  myName = 'My008205Component';
}
