// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008197',
  templateUrl: './my.008197.component.html'
})
export class My008197Component {
  @Input() parentName = '';
  myName = 'My008197Component';
}
