// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008221',
  templateUrl: './my.008221.component.html'
})
export class My008221Component {
  @Input() parentName = '';
  myName = 'My008221Component';
}
