// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008243',
  templateUrl: './my.008243.component.html'
})
export class My008243Component {
  @Input() parentName = '';
  myName = 'My008243Component';
}
