// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008182',
  templateUrl: './my.008182.component.html'
})
export class My008182Component {
  @Input() parentName = '';
  myName = 'My008182Component';
}
