// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008229',
  templateUrl: './my.008229.component.html'
})
export class My008229Component {
  @Input() parentName = '';
  myName = 'My008229Component';
}
