// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002271',
  templateUrl: './my.002271.component.html'
})
export class My002271Component {
  @Input() parentName = '';
  myName = 'My002271Component';
}
