// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002322',
  templateUrl: './my.002322.component.html'
})
export class My002322Component {
  @Input() parentName = '';
  myName = 'My002322Component';
}
