// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002251',
  templateUrl: './my.002251.component.html'
})
export class My002251Component {
  @Input() parentName = '';
  myName = 'My002251Component';
}
