// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002230',
  templateUrl: './my.002230.component.html'
})
export class My002230Component {
  @Input() parentName = '';
  myName = 'My002230Component';
}
