// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002302',
  templateUrl: './my.002302.component.html'
})
export class My002302Component {
  @Input() parentName = '';
  myName = 'My002302Component';
}
