// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002299',
  templateUrl: './my.002299.component.html'
})
export class My002299Component {
  @Input() parentName = '';
  myName = 'My002299Component';
}
