// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002231',
  templateUrl: './my.002231.component.html'
})
export class My002231Component {
  @Input() parentName = '';
  myName = 'My002231Component';
}
