// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002235',
  templateUrl: './my.002235.component.html'
})
export class My002235Component {
  @Input() parentName = '';
  myName = 'My002235Component';
}
