// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002227',
  templateUrl: './my.002227.component.html'
})
export class My002227Component {
  @Input() parentName = '';
  myName = 'My002227Component';
}
