// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002279',
  templateUrl: './my.002279.component.html'
})
export class My002279Component {
  @Input() parentName = '';
  myName = 'My002279Component';
}
