// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002305',
  templateUrl: './my.002305.component.html'
})
export class My002305Component {
  @Input() parentName = '';
  myName = 'My002305Component';
}
