// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002244',
  templateUrl: './my.002244.component.html'
})
export class My002244Component {
  @Input() parentName = '';
  myName = 'My002244Component';
}
