// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002232',
  templateUrl: './my.002232.component.html'
})
export class My002232Component {
  @Input() parentName = '';
  myName = 'My002232Component';
}
