// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002278',
  templateUrl: './my.002278.component.html'
})
export class My002278Component {
  @Input() parentName = '';
  myName = 'My002278Component';
}
