// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002294',
  templateUrl: './my.002294.component.html'
})
export class My002294Component {
  @Input() parentName = '';
  myName = 'My002294Component';
}
