// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002286',
  templateUrl: './my.002286.component.html'
})
export class My002286Component {
  @Input() parentName = '';
  myName = 'My002286Component';
}
