// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002258',
  templateUrl: './my.002258.component.html'
})
export class My002258Component {
  @Input() parentName = '';
  myName = 'My002258Component';
}
