// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002268',
  templateUrl: './my.002268.component.html'
})
export class My002268Component {
  @Input() parentName = '';
  myName = 'My002268Component';
}
