// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002313',
  templateUrl: './my.002313.component.html'
})
export class My002313Component {
  @Input() parentName = '';
  myName = 'My002313Component';
}
