// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-002236',
  templateUrl: './my.002236.component.html'
})
export class My002236Component {
  @Input() parentName = '';
  myName = 'My002236Component';
}
