// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005098',
  templateUrl: './my.005098.component.html'
})
export class My005098Component {
  @Input() parentName = '';
  myName = 'My005098Component';
}
