// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005079',
  templateUrl: './my.005079.component.html'
})
export class My005079Component {
  @Input() parentName = '';
  myName = 'My005079Component';
}
