// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005080',
  templateUrl: './my.005080.component.html'
})
export class My005080Component {
  @Input() parentName = '';
  myName = 'My005080Component';
}
