// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005055',
  templateUrl: './my.005055.component.html'
})
export class My005055Component {
  @Input() parentName = '';
  myName = 'My005055Component';
}
