// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005128',
  templateUrl: './my.005128.component.html'
})
export class My005128Component {
  @Input() parentName = '';
  myName = 'My005128Component';
}
