// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005061',
  templateUrl: './my.005061.component.html'
})
export class My005061Component {
  @Input() parentName = '';
  myName = 'My005061Component';
}
