// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005125',
  templateUrl: './my.005125.component.html'
})
export class My005125Component {
  @Input() parentName = '';
  myName = 'My005125Component';
}
