// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005112',
  templateUrl: './my.005112.component.html'
})
export class My005112Component {
  @Input() parentName = '';
  myName = 'My005112Component';
}
