// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005083',
  templateUrl: './my.005083.component.html'
})
export class My005083Component {
  @Input() parentName = '';
  myName = 'My005083Component';
}
