// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005117',
  templateUrl: './my.005117.component.html'
})
export class My005117Component {
  @Input() parentName = '';
  myName = 'My005117Component';
}
