// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005110',
  templateUrl: './my.005110.component.html'
})
export class My005110Component {
  @Input() parentName = '';
  myName = 'My005110Component';
}
