// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005120',
  templateUrl: './my.005120.component.html'
})
export class My005120Component {
  @Input() parentName = '';
  myName = 'My005120Component';
}
