// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005094',
  templateUrl: './my.005094.component.html'
})
export class My005094Component {
  @Input() parentName = '';
  myName = 'My005094Component';
}
