// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005100',
  templateUrl: './my.005100.component.html'
})
export class My005100Component {
  @Input() parentName = '';
  myName = 'My005100Component';
}
