// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005072',
  templateUrl: './my.005072.component.html'
})
export class My005072Component {
  @Input() parentName = '';
  myName = 'My005072Component';
}
