// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005137',
  templateUrl: './my.005137.component.html'
})
export class My005137Component {
  @Input() parentName = '';
  myName = 'My005137Component';
}
