// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005136',
  templateUrl: './my.005136.component.html'
})
export class My005136Component {
  @Input() parentName = '';
  myName = 'My005136Component';
}
