// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005135',
  templateUrl: './my.005135.component.html'
})
export class My005135Component {
  @Input() parentName = '';
  myName = 'My005135Component';
}
