// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-005132',
  templateUrl: './my.005132.component.html'
})
export class My005132Component {
  @Input() parentName = '';
  myName = 'My005132Component';
}
