// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007546',
  templateUrl: './my.007546.component.html'
})
export class My007546Component {
  @Input() parentName = '';
  myName = 'My007546Component';
}
