// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007525',
  templateUrl: './my.007525.component.html'
})
export class My007525Component {
  @Input() parentName = '';
  myName = 'My007525Component';
}
