// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007501',
  templateUrl: './my.007501.component.html'
})
export class My007501Component {
  @Input() parentName = '';
  myName = 'My007501Component';
}
