// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007492',
  templateUrl: './my.007492.component.html'
})
export class My007492Component {
  @Input() parentName = '';
  myName = 'My007492Component';
}
