// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007539',
  templateUrl: './my.007539.component.html'
})
export class My007539Component {
  @Input() parentName = '';
  myName = 'My007539Component';
}
