// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007536',
  templateUrl: './my.007536.component.html'
})
export class My007536Component {
  @Input() parentName = '';
  myName = 'My007536Component';
}
