// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007478',
  templateUrl: './my.007478.component.html'
})
export class My007478Component {
  @Input() parentName = '';
  myName = 'My007478Component';
}
