// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007549',
  templateUrl: './my.007549.component.html'
})
export class My007549Component {
  @Input() parentName = '';
  myName = 'My007549Component';
}
