// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007545',
  templateUrl: './my.007545.component.html'
})
export class My007545Component {
  @Input() parentName = '';
  myName = 'My007545Component';
}
