// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007479',
  templateUrl: './my.007479.component.html'
})
export class My007479Component {
  @Input() parentName = '';
  myName = 'My007479Component';
}
