// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007488',
  templateUrl: './my.007488.component.html'
})
export class My007488Component {
  @Input() parentName = '';
  myName = 'My007488Component';
}
