// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007505',
  templateUrl: './my.007505.component.html'
})
export class My007505Component {
  @Input() parentName = '';
  myName = 'My007505Component';
}
