// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007533',
  templateUrl: './my.007533.component.html'
})
export class My007533Component {
  @Input() parentName = '';
  myName = 'My007533Component';
}
