// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007520',
  templateUrl: './my.007520.component.html'
})
export class My007520Component {
  @Input() parentName = '';
  myName = 'My007520Component';
}
