// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007547',
  templateUrl: './my.007547.component.html'
})
export class My007547Component {
  @Input() parentName = '';
  myName = 'My007547Component';
}
