// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003891',
  templateUrl: './my.003891.component.html'
})
export class My003891Component {
  @Input() parentName = '';
  myName = 'My003891Component';
}
