// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003912',
  templateUrl: './my.003912.component.html'
})
export class My003912Component {
  @Input() parentName = '';
  myName = 'My003912Component';
}
