// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003850',
  templateUrl: './my.003850.component.html'
})
export class My003850Component {
  @Input() parentName = '';
  myName = 'My003850Component';
}
