// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003894',
  templateUrl: './my.003894.component.html'
})
export class My003894Component {
  @Input() parentName = '';
  myName = 'My003894Component';
}
