// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003930',
  templateUrl: './my.003930.component.html'
})
export class My003930Component {
  @Input() parentName = '';
  myName = 'My003930Component';
}
