// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003880',
  templateUrl: './my.003880.component.html'
})
export class My003880Component {
  @Input() parentName = '';
  myName = 'My003880Component';
}
