// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003915',
  templateUrl: './my.003915.component.html'
})
export class My003915Component {
  @Input() parentName = '';
  myName = 'My003915Component';
}
