// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003855',
  templateUrl: './my.003855.component.html'
})
export class My003855Component {
  @Input() parentName = '';
  myName = 'My003855Component';
}
