// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003866',
  templateUrl: './my.003866.component.html'
})
export class My003866Component {
  @Input() parentName = '';
  myName = 'My003866Component';
}
