// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003937',
  templateUrl: './my.003937.component.html'
})
export class My003937Component {
  @Input() parentName = '';
  myName = 'My003937Component';
}
