// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003932',
  templateUrl: './my.003932.component.html'
})
export class My003932Component {
  @Input() parentName = '';
  myName = 'My003932Component';
}
