// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003916',
  templateUrl: './my.003916.component.html'
})
export class My003916Component {
  @Input() parentName = '';
  myName = 'My003916Component';
}
