// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003923',
  templateUrl: './my.003923.component.html'
})
export class My003923Component {
  @Input() parentName = '';
  myName = 'My003923Component';
}
