// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003867',
  templateUrl: './my.003867.component.html'
})
export class My003867Component {
  @Input() parentName = '';
  myName = 'My003867Component';
}
