// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003904',
  templateUrl: './my.003904.component.html'
})
export class My003904Component {
  @Input() parentName = '';
  myName = 'My003904Component';
}
