// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003924',
  templateUrl: './my.003924.component.html'
})
export class My003924Component {
  @Input() parentName = '';
  myName = 'My003924Component';
}
