// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003927',
  templateUrl: './my.003927.component.html'
})
export class My003927Component {
  @Input() parentName = '';
  myName = 'My003927Component';
}
