// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003931',
  templateUrl: './my.003931.component.html'
})
export class My003931Component {
  @Input() parentName = '';
  myName = 'My003931Component';
}
