// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003917',
  templateUrl: './my.003917.component.html'
})
export class My003917Component {
  @Input() parentName = '';
  myName = 'My003917Component';
}
