// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My007676Component } from './my.007676.component';
import { My007677Component } from './my.007677.component';
import { My007678Component } from './my.007678.component';
import { My007679Component } from './my.007679.component';
import { My007680Component } from './my.007680.component';
import { My007681Component } from './my.007681.component';
import { My007682Component } from './my.007682.component';
import { My007683Component } from './my.007683.component';
import { My007684Component } from './my.007684.component';
import { My007685Component } from './my.007685.component';
import { My007686Component } from './my.007686.component';
import { My007687Component } from './my.007687.component';
import { My007688Component } from './my.007688.component';
import { My007689Component } from './my.007689.component';
import { My007690Component } from './my.007690.component';
import { My007691Component } from './my.007691.component';
import { My007692Component } from './my.007692.component';
import { My007693Component } from './my.007693.component';
import { My007694Component } from './my.007694.component';
import { My007695Component } from './my.007695.component';
import { My007696Component } from './my.007696.component';
import { My007697Component } from './my.007697.component';
import { My007698Component } from './my.007698.component';
import { My007699Component } from './my.007699.component';
import { My007700Component } from './my.007700.component';
import { My007701Component } from './my.007701.component';
import { My007702Component } from './my.007702.component';
import { My007703Component } from './my.007703.component';
import { My007704Component } from './my.007704.component';
import { My007705Component } from './my.007705.component';
import { My007706Component } from './my.007706.component';
import { My007707Component } from './my.007707.component';
import { My007708Component } from './my.007708.component';
import { My007709Component } from './my.007709.component';
import { My007710Component } from './my.007710.component';
import { My007711Component } from './my.007711.component';
import { My007712Component } from './my.007712.component';
import { My007713Component } from './my.007713.component';
import { My007714Component } from './my.007714.component';
import { My007715Component } from './my.007715.component';
import { My007716Component } from './my.007716.component';
import { My007717Component } from './my.007717.component';
import { My007718Component } from './my.007718.component';
import { My007719Component } from './my.007719.component';
import { My007720Component } from './my.007720.component';
import { My007721Component } from './my.007721.component';
import { My007722Component } from './my.007722.component';
import { My007723Component } from './my.007723.component';
import { My007724Component } from './my.007724.component';
import { My007725Component } from './my.007725.component';
import { My007726Component } from './my.007726.component';
import { My007727Component } from './my.007727.component';
import { My007728Component } from './my.007728.component';
import { My007729Component } from './my.007729.component';
import { My007730Component } from './my.007730.component';
import { My007731Component } from './my.007731.component';
import { My007732Component } from './my.007732.component';
import { My007733Component } from './my.007733.component';
import { My007734Component } from './my.007734.component';
import { My007735Component } from './my.007735.component';
import { My007736Component } from './my.007736.component';
import { My007737Component } from './my.007737.component';
import { My007738Component } from './my.007738.component';
import { My007739Component } from './my.007739.component';
import { My007740Component } from './my.007740.component';
import { My007741Component } from './my.007741.component';
import { My007742Component } from './my.007742.component';
import { My007743Component } from './my.007743.component';
import { My007744Component } from './my.007744.component';
import { My007745Component } from './my.007745.component';
import { My007746Component } from './my.007746.component';
import { My007747Component } from './my.007747.component';
import { My007748Component } from './my.007748.component';
import { My007749Component } from './my.007749.component';
import { My007750Component } from './my.007750.component';
import { My007751Component } from './my.007751.component';
import { My007752Component } from './my.007752.component';
import { My007753Component } from './my.007753.component';
import { My007754Component } from './my.007754.component';
import { My007755Component } from './my.007755.component';
import { My007756Component } from './my.007756.component';
import { My007757Component } from './my.007757.component';
import { My007758Component } from './my.007758.component';
import { My007759Component } from './my.007759.component';
import { My007760Component } from './my.007760.component';
import { My007761Component } from './my.007761.component';
import { My007762Component } from './my.007762.component';
import { My007763Component } from './my.007763.component';
import { My007764Component } from './my.007764.component';
import { My007765Component } from './my.007765.component';
import { My007766Component } from './my.007766.component';
import { My007767Component } from './my.007767.component';
import { My007768Component } from './my.007768.component';
import { My007769Component } from './my.007769.component';
import { My007770Component } from './my.007770.component';
import { My007771Component } from './my.007771.component';
import { My007772Component } from './my.007772.component';
import { My007773Component } from './my.007773.component';
import { My007774Component } from './my.007774.component';
import { My007775Component } from './my.007775.component';
import { My007776Component } from './my.007776.component';

@NgModule({
  declarations: [
    My007676Component,
    My007677Component,
    My007678Component,
    My007679Component,
    My007680Component,
    My007681Component,
    My007682Component,
    My007683Component,
    My007684Component,
    My007685Component,
    My007686Component,
    My007687Component,
    My007688Component,
    My007689Component,
    My007690Component,
    My007691Component,
    My007692Component,
    My007693Component,
    My007694Component,
    My007695Component,
    My007696Component,
    My007697Component,
    My007698Component,
    My007699Component,
    My007700Component,
    My007701Component,
    My007702Component,
    My007703Component,
    My007704Component,
    My007705Component,
    My007706Component,
    My007707Component,
    My007708Component,
    My007709Component,
    My007710Component,
    My007711Component,
    My007712Component,
    My007713Component,
    My007714Component,
    My007715Component,
    My007716Component,
    My007717Component,
    My007718Component,
    My007719Component,
    My007720Component,
    My007721Component,
    My007722Component,
    My007723Component,
    My007724Component,
    My007725Component,
    My007726Component,
    My007727Component,
    My007728Component,
    My007729Component,
    My007730Component,
    My007731Component,
    My007732Component,
    My007733Component,
    My007734Component,
    My007735Component,
    My007736Component,
    My007737Component,
    My007738Component,
    My007739Component,
    My007740Component,
    My007741Component,
    My007742Component,
    My007743Component,
    My007744Component,
    My007745Component,
    My007746Component,
    My007747Component,
    My007748Component,
    My007749Component,
    My007750Component,
    My007751Component,
    My007752Component,
    My007753Component,
    My007754Component,
    My007755Component,
    My007756Component,
    My007757Component,
    My007758Component,
    My007759Component,
    My007760Component,
    My007761Component,
    My007762Component,
    My007763Component,
    My007764Component,
    My007765Component,
    My007766Component,
    My007767Component,
    My007768Component,
    My007769Component,
    My007770Component,
    My007771Component,
    My007772Component,
    My007773Component,
    My007774Component,
    My007775Component,
    My007776Component,
  ],
  imports: [CommonModule],
  exports: [
    My007676Component,
  ]
})
export class Module000076 { }
