// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007753',
  templateUrl: './my.007753.component.html'
})
export class My007753Component {
  @Input() parentName = '';
  myName = 'My007753Component';
}
