// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007760',
  templateUrl: './my.007760.component.html'
})
export class My007760Component {
  @Input() parentName = '';
  myName = 'My007760Component';
}
