// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007767',
  templateUrl: './my.007767.component.html'
})
export class My007767Component {
  @Input() parentName = '';
  myName = 'My007767Component';
}
