// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007698',
  templateUrl: './my.007698.component.html'
})
export class My007698Component {
  @Input() parentName = '';
  myName = 'My007698Component';
}
