// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007762',
  templateUrl: './my.007762.component.html'
})
export class My007762Component {
  @Input() parentName = '';
  myName = 'My007762Component';
}
