// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007680',
  templateUrl: './my.007680.component.html'
})
export class My007680Component {
  @Input() parentName = '';
  myName = 'My007680Component';
}
