// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007776',
  templateUrl: './my.007776.component.html'
})
export class My007776Component {
  @Input() parentName = '';
  myName = 'My007776Component';
}
