// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007723',
  templateUrl: './my.007723.component.html'
})
export class My007723Component {
  @Input() parentName = '';
  myName = 'My007723Component';
}
