// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007749',
  templateUrl: './my.007749.component.html'
})
export class My007749Component {
  @Input() parentName = '';
  myName = 'My007749Component';
}
