// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007707',
  templateUrl: './my.007707.component.html'
})
export class My007707Component {
  @Input() parentName = '';
  myName = 'My007707Component';
}
