// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007677',
  templateUrl: './my.007677.component.html'
})
export class My007677Component {
  @Input() parentName = '';
  myName = 'My007677Component';
}
