// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007705',
  templateUrl: './my.007705.component.html'
})
export class My007705Component {
  @Input() parentName = '';
  myName = 'My007705Component';
}
