// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-007678',
  templateUrl: './my.007678.component.html'
})
export class My007678Component {
  @Input() parentName = '';
  myName = 'My007678Component';
}
