// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003379',
  templateUrl: './my.003379.component.html'
})
export class My003379Component {
  @Input() parentName = '';
  myName = 'My003379Component';
}
