// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003402',
  templateUrl: './my.003402.component.html'
})
export class My003402Component {
  @Input() parentName = '';
  myName = 'My003402Component';
}
