// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003391',
  templateUrl: './my.003391.component.html'
})
export class My003391Component {
  @Input() parentName = '';
  myName = 'My003391Component';
}
