// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003422',
  templateUrl: './my.003422.component.html'
})
export class My003422Component {
  @Input() parentName = '';
  myName = 'My003422Component';
}
