// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003396',
  templateUrl: './my.003396.component.html'
})
export class My003396Component {
  @Input() parentName = '';
  myName = 'My003396Component';
}
