// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003334',
  templateUrl: './my.003334.component.html'
})
export class My003334Component {
  @Input() parentName = '';
  myName = 'My003334Component';
}
