// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003376',
  templateUrl: './my.003376.component.html'
})
export class My003376Component {
  @Input() parentName = '';
  myName = 'My003376Component';
}
