// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003419',
  templateUrl: './my.003419.component.html'
})
export class My003419Component {
  @Input() parentName = '';
  myName = 'My003419Component';
}
