// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003410',
  templateUrl: './my.003410.component.html'
})
export class My003410Component {
  @Input() parentName = '';
  myName = 'My003410Component';
}
