// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003405',
  templateUrl: './my.003405.component.html'
})
export class My003405Component {
  @Input() parentName = '';
  myName = 'My003405Component';
}
