// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003356',
  templateUrl: './my.003356.component.html'
})
export class My003356Component {
  @Input() parentName = '';
  myName = 'My003356Component';
}
