// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003432',
  templateUrl: './my.003432.component.html'
})
export class My003432Component {
  @Input() parentName = '';
  myName = 'My003432Component';
}
