// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003355',
  templateUrl: './my.003355.component.html'
})
export class My003355Component {
  @Input() parentName = '';
  myName = 'My003355Component';
}
