// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003381',
  templateUrl: './my.003381.component.html'
})
export class My003381Component {
  @Input() parentName = '';
  myName = 'My003381Component';
}
