// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003377',
  templateUrl: './my.003377.component.html'
})
export class My003377Component {
  @Input() parentName = '';
  myName = 'My003377Component';
}
