// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003383',
  templateUrl: './my.003383.component.html'
})
export class My003383Component {
  @Input() parentName = '';
  myName = 'My003383Component';
}
