// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-003398',
  templateUrl: './my.003398.component.html'
})
export class My003398Component {
  @Input() parentName = '';
  myName = 'My003398Component';
}
