// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My008686Component } from './my.008686.component';
import { My008687Component } from './my.008687.component';
import { My008688Component } from './my.008688.component';
import { My008689Component } from './my.008689.component';
import { My008690Component } from './my.008690.component';
import { My008691Component } from './my.008691.component';
import { My008692Component } from './my.008692.component';
import { My008693Component } from './my.008693.component';
import { My008694Component } from './my.008694.component';
import { My008695Component } from './my.008695.component';
import { My008696Component } from './my.008696.component';
import { My008697Component } from './my.008697.component';
import { My008698Component } from './my.008698.component';
import { My008699Component } from './my.008699.component';
import { My008700Component } from './my.008700.component';
import { My008701Component } from './my.008701.component';
import { My008702Component } from './my.008702.component';
import { My008703Component } from './my.008703.component';
import { My008704Component } from './my.008704.component';
import { My008705Component } from './my.008705.component';
import { My008706Component } from './my.008706.component';
import { My008707Component } from './my.008707.component';
import { My008708Component } from './my.008708.component';
import { My008709Component } from './my.008709.component';
import { My008710Component } from './my.008710.component';
import { My008711Component } from './my.008711.component';
import { My008712Component } from './my.008712.component';
import { My008713Component } from './my.008713.component';
import { My008714Component } from './my.008714.component';
import { My008715Component } from './my.008715.component';
import { My008716Component } from './my.008716.component';
import { My008717Component } from './my.008717.component';
import { My008718Component } from './my.008718.component';
import { My008719Component } from './my.008719.component';
import { My008720Component } from './my.008720.component';
import { My008721Component } from './my.008721.component';
import { My008722Component } from './my.008722.component';
import { My008723Component } from './my.008723.component';
import { My008724Component } from './my.008724.component';
import { My008725Component } from './my.008725.component';
import { My008726Component } from './my.008726.component';
import { My008727Component } from './my.008727.component';
import { My008728Component } from './my.008728.component';
import { My008729Component } from './my.008729.component';
import { My008730Component } from './my.008730.component';
import { My008731Component } from './my.008731.component';
import { My008732Component } from './my.008732.component';
import { My008733Component } from './my.008733.component';
import { My008734Component } from './my.008734.component';
import { My008735Component } from './my.008735.component';
import { My008736Component } from './my.008736.component';
import { My008737Component } from './my.008737.component';
import { My008738Component } from './my.008738.component';
import { My008739Component } from './my.008739.component';
import { My008740Component } from './my.008740.component';
import { My008741Component } from './my.008741.component';
import { My008742Component } from './my.008742.component';
import { My008743Component } from './my.008743.component';
import { My008744Component } from './my.008744.component';
import { My008745Component } from './my.008745.component';
import { My008746Component } from './my.008746.component';
import { My008747Component } from './my.008747.component';
import { My008748Component } from './my.008748.component';
import { My008749Component } from './my.008749.component';
import { My008750Component } from './my.008750.component';
import { My008751Component } from './my.008751.component';
import { My008752Component } from './my.008752.component';
import { My008753Component } from './my.008753.component';
import { My008754Component } from './my.008754.component';
import { My008755Component } from './my.008755.component';
import { My008756Component } from './my.008756.component';
import { My008757Component } from './my.008757.component';
import { My008758Component } from './my.008758.component';
import { My008759Component } from './my.008759.component';
import { My008760Component } from './my.008760.component';
import { My008761Component } from './my.008761.component';
import { My008762Component } from './my.008762.component';
import { My008763Component } from './my.008763.component';
import { My008764Component } from './my.008764.component';
import { My008765Component } from './my.008765.component';
import { My008766Component } from './my.008766.component';
import { My008767Component } from './my.008767.component';
import { My008768Component } from './my.008768.component';
import { My008769Component } from './my.008769.component';
import { My008770Component } from './my.008770.component';
import { My008771Component } from './my.008771.component';
import { My008772Component } from './my.008772.component';
import { My008773Component } from './my.008773.component';
import { My008774Component } from './my.008774.component';
import { My008775Component } from './my.008775.component';
import { My008776Component } from './my.008776.component';
import { My008777Component } from './my.008777.component';
import { My008778Component } from './my.008778.component';
import { My008779Component } from './my.008779.component';
import { My008780Component } from './my.008780.component';
import { My008781Component } from './my.008781.component';
import { My008782Component } from './my.008782.component';
import { My008783Component } from './my.008783.component';
import { My008784Component } from './my.008784.component';
import { My008785Component } from './my.008785.component';
import { My008786Component } from './my.008786.component';

@NgModule({
  declarations: [
    My008686Component,
    My008687Component,
    My008688Component,
    My008689Component,
    My008690Component,
    My008691Component,
    My008692Component,
    My008693Component,
    My008694Component,
    My008695Component,
    My008696Component,
    My008697Component,
    My008698Component,
    My008699Component,
    My008700Component,
    My008701Component,
    My008702Component,
    My008703Component,
    My008704Component,
    My008705Component,
    My008706Component,
    My008707Component,
    My008708Component,
    My008709Component,
    My008710Component,
    My008711Component,
    My008712Component,
    My008713Component,
    My008714Component,
    My008715Component,
    My008716Component,
    My008717Component,
    My008718Component,
    My008719Component,
    My008720Component,
    My008721Component,
    My008722Component,
    My008723Component,
    My008724Component,
    My008725Component,
    My008726Component,
    My008727Component,
    My008728Component,
    My008729Component,
    My008730Component,
    My008731Component,
    My008732Component,
    My008733Component,
    My008734Component,
    My008735Component,
    My008736Component,
    My008737Component,
    My008738Component,
    My008739Component,
    My008740Component,
    My008741Component,
    My008742Component,
    My008743Component,
    My008744Component,
    My008745Component,
    My008746Component,
    My008747Component,
    My008748Component,
    My008749Component,
    My008750Component,
    My008751Component,
    My008752Component,
    My008753Component,
    My008754Component,
    My008755Component,
    My008756Component,
    My008757Component,
    My008758Component,
    My008759Component,
    My008760Component,
    My008761Component,
    My008762Component,
    My008763Component,
    My008764Component,
    My008765Component,
    My008766Component,
    My008767Component,
    My008768Component,
    My008769Component,
    My008770Component,
    My008771Component,
    My008772Component,
    My008773Component,
    My008774Component,
    My008775Component,
    My008776Component,
    My008777Component,
    My008778Component,
    My008779Component,
    My008780Component,
    My008781Component,
    My008782Component,
    My008783Component,
    My008784Component,
    My008785Component,
    My008786Component,
  ],
  imports: [CommonModule],
  exports: [
    My008686Component,
  ]
})
export class Module000086 { }
