// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008777',
  templateUrl: './my.008777.component.html'
})
export class My008777Component {
  @Input() parentName = '';
  myName = 'My008777Component';
}
