// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008753',
  templateUrl: './my.008753.component.html'
})
export class My008753Component {
  @Input() parentName = '';
  myName = 'My008753Component';
}
