// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008768',
  templateUrl: './my.008768.component.html'
})
export class My008768Component {
  @Input() parentName = '';
  myName = 'My008768Component';
}
