// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008737',
  templateUrl: './my.008737.component.html'
})
export class My008737Component {
  @Input() parentName = '';
  myName = 'My008737Component';
}
