// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008701',
  templateUrl: './my.008701.component.html'
})
export class My008701Component {
  @Input() parentName = '';
  myName = 'My008701Component';
}
