// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008779',
  templateUrl: './my.008779.component.html'
})
export class My008779Component {
  @Input() parentName = '';
  myName = 'My008779Component';
}
