// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008754',
  templateUrl: './my.008754.component.html'
})
export class My008754Component {
  @Input() parentName = '';
  myName = 'My008754Component';
}
