// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008776',
  templateUrl: './my.008776.component.html'
})
export class My008776Component {
  @Input() parentName = '';
  myName = 'My008776Component';
}
