// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008750',
  templateUrl: './my.008750.component.html'
})
export class My008750Component {
  @Input() parentName = '';
  myName = 'My008750Component';
}
