// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008715',
  templateUrl: './my.008715.component.html'
})
export class My008715Component {
  @Input() parentName = '';
  myName = 'My008715Component';
}
