// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008775',
  templateUrl: './my.008775.component.html'
})
export class My008775Component {
  @Input() parentName = '';
  myName = 'My008775Component';
}
