// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008749',
  templateUrl: './my.008749.component.html'
})
export class My008749Component {
  @Input() parentName = '';
  myName = 'My008749Component';
}
