// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008704',
  templateUrl: './my.008704.component.html'
})
export class My008704Component {
  @Input() parentName = '';
  myName = 'My008704Component';
}
