// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008690',
  templateUrl: './my.008690.component.html'
})
export class My008690Component {
  @Input() parentName = '';
  myName = 'My008690Component';
}
