// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008725',
  templateUrl: './my.008725.component.html'
})
export class My008725Component {
  @Input() parentName = '';
  myName = 'My008725Component';
}
