// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008806',
  templateUrl: './my.008806.component.html'
})
export class My008806Component {
  @Input() parentName = '';
  myName = 'My008806Component';
}
