// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008814',
  templateUrl: './my.008814.component.html'
})
export class My008814Component {
  @Input() parentName = '';
  myName = 'My008814Component';
}
