// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008884',
  templateUrl: './my.008884.component.html'
})
export class My008884Component {
  @Input() parentName = '';
  myName = 'My008884Component';
}
