// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008794',
  templateUrl: './my.008794.component.html'
})
export class My008794Component {
  @Input() parentName = '';
  myName = 'My008794Component';
}
