// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008846',
  templateUrl: './my.008846.component.html'
})
export class My008846Component {
  @Input() parentName = '';
  myName = 'My008846Component';
}
