// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008845',
  templateUrl: './my.008845.component.html'
})
export class My008845Component {
  @Input() parentName = '';
  myName = 'My008845Component';
}
