// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008787',
  templateUrl: './my.008787.component.html'
})
export class My008787Component {
  @Input() parentName = '';
  myName = 'My008787Component';
}
