// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008886',
  templateUrl: './my.008886.component.html'
})
export class My008886Component {
  @Input() parentName = '';
  myName = 'My008886Component';
}
