// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008877',
  templateUrl: './my.008877.component.html'
})
export class My008877Component {
  @Input() parentName = '';
  myName = 'My008877Component';
}
