// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008862',
  templateUrl: './my.008862.component.html'
})
export class My008862Component {
  @Input() parentName = '';
  myName = 'My008862Component';
}
