// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008849',
  templateUrl: './my.008849.component.html'
})
export class My008849Component {
  @Input() parentName = '';
  myName = 'My008849Component';
}
