// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-008809',
  templateUrl: './my.008809.component.html'
})
export class My008809Component {
  @Input() parentName = '';
  myName = 'My008809Component';
}
