// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009590',
  templateUrl: './my.009590.component.html'
})
export class My009590Component {
  @Input() parentName = '';
  myName = 'My009590Component';
}
