// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009584',
  templateUrl: './my.009584.component.html'
})
export class My009584Component {
  @Input() parentName = '';
  myName = 'My009584Component';
}
