// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009563',
  templateUrl: './my.009563.component.html'
})
export class My009563Component {
  @Input() parentName = '';
  myName = 'My009563Component';
}
