// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009577',
  templateUrl: './my.009577.component.html'
})
export class My009577Component {
  @Input() parentName = '';
  myName = 'My009577Component';
}
