// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009570',
  templateUrl: './my.009570.component.html'
})
export class My009570Component {
  @Input() parentName = '';
  myName = 'My009570Component';
}
