// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009583',
  templateUrl: './my.009583.component.html'
})
export class My009583Component {
  @Input() parentName = '';
  myName = 'My009583Component';
}
