// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009494',
  templateUrl: './my.009494.component.html'
})
export class My009494Component {
  @Input() parentName = '';
  myName = 'My009494Component';
}
