// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009510',
  templateUrl: './my.009510.component.html'
})
export class My009510Component {
  @Input() parentName = '';
  myName = 'My009510Component';
}
