// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009515',
  templateUrl: './my.009515.component.html'
})
export class My009515Component {
  @Input() parentName = '';
  myName = 'My009515Component';
}
