// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009506',
  templateUrl: './my.009506.component.html'
})
export class My009506Component {
  @Input() parentName = '';
  myName = 'My009506Component';
}
