// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009527',
  templateUrl: './my.009527.component.html'
})
export class My009527Component {
  @Input() parentName = '';
  myName = 'My009527Component';
}
