// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009519',
  templateUrl: './my.009519.component.html'
})
export class My009519Component {
  @Input() parentName = '';
  myName = 'My009519Component';
}
