// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009512',
  templateUrl: './my.009512.component.html'
})
export class My009512Component {
  @Input() parentName = '';
  myName = 'My009512Component';
}
