// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009503',
  templateUrl: './my.009503.component.html'
})
export class My009503Component {
  @Input() parentName = '';
  myName = 'My009503Component';
}
