// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-009497',
  templateUrl: './my.009497.component.html'
})
export class My009497Component {
  @Input() parentName = '';
  myName = 'My009497Component';
}
